{
  "hash": "12aa6177c000bd058daf3337ac9fe754",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Matching-Adjusted Indirect Comparison (MAIC)\"\nauthor: \"Xiaoge Zhang\"\ndate: \"06/05/2026\"\nengine: knitr\nformat: \n  html:\n    theme: cosmo\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    code-summary: \"View the code\"\n    number-sections: true\n---\n\n*Bridging the Gap When Patient-Level Data is Only Partially Available*\n\n```{=html}\n<!--\n## 📑 Table of Contents {.unnumbered}\n\n1.  [**Executive Summary: When NMA Fails**](#1-executive-summary)\n2.  [**The Minimal Mock Case: Unanchored MAIC**](#2-mock-case)\n3.  [**Methodological Foundation: The Method of Moments**](#3-methodology)\n4.  [**Custom R Implementation: Calculating Weights from Scratch**](#4-custom-r-implementation)\n5.  [**Industry Standard Alternative: `maic` Package**](#5-maic-package)\n-->\n```\n\n## Executive Summary: Bridging Data Asymmetry in HTA {#1-executive-summary}\n\nIn real-world Health Technology Assessment (HTA) submissions to bodies like NICE, we often face a critical data asymmetry when trying to compare a new drug with its competitors:\n\n1. **Our Drug (Drug A)**: We have conducted a randomized controlled trial (Drug A vs. Standard of Care) and possess the full **Individual Patient Data (IPD)**.\n2. **Competitor Drug (Drug B)**: The competitor has also run a trial against the same Standard of Care, but we only have access to the published **Aggregate Data (AgD)** from their literature.\n\nWhile the evidence network is technically connected via the common comparator (Standard of Care), a standard Network Meta-Analysis (NMA) relies on the assumption that the patient populations across these trials are similar. In reality, they almost always differ (e.g., Trial A enrolled younger, healthier patients than Trial B). Directly pooling the relative effects without adjusting for these population differences yields biased estimates.\n\nIf we had IPD for both trials, we would perform a gold-standard **Full IPD NMA**. However, constrained by the competitor's aggregate data, we must use a workaround.\n\n**Matching-Adjusted Indirect Comparison (MAIC)** is a statistical workaround designed precisely for this \"asymmetric data\" scenario (specifically **Anchored MAIC**). It utilizes the flexibility of our IPD to adjust for population differences. MAIC assigns a statistical weight to every individual patient in Trial A such that the *weighted* baseline characteristics perfectly match the *published* aggregate characteristics of Trial B. Once the populations are aligned, we compare the relative treatment effects against the common comparator.\n\nIn essence, MAIC is a **\"pseudo-IPD\" method**. It steps down to the lowest common denominator (aggregate level) to facilitate a fair, covariate-adjusted comparison that would otherwise be impossible due to data limitations.\n\n```{=html}\n<!-- Audit Point: Anchored vs Unanchored MAIC\nNICE DSU Technical Support Document (TSD) 18 outlines two types of MAIC:\n1. **Unanchored MAIC**: Used when there is no common comparator (e.g., comparing two single-arm trials). This relies on a very strong assumption: *all* relative effect modifiers and prognostic factors must be accounted for.\n2. **Anchored MAIC**: Used when both trials have a common comparator (e.g., Placebo), but we still want to adjust for population differences. This only requires accounting for relative effect modifiers, making it the preferred method by HTA bodies whenever possible.\nIn this chapter, we demonstrate the mathematical mechanism of weighting using the simpler Unanchored scenario to focus purely on the weighting mechanics.\n-->\n```\n\n## The Minimal Mock Case: Unanchored MAIC {#2-mock-case}\n\n### The Scenario\n\nWe are evaluating a new oncology drug with a continuous outcome (e.g., reduction in tumor size).\n\n- **Drug A (Our Drug)**: We have row-by-row IPD for $N=200$ patients from a single-arm Phase II trial.\n- **Drug B (Competitor)**: We only have a published paper showing aggregate baseline characteristics and an average outcome.\n\n### The Problem (Baseline Imbalance)\n\nFrom the published paper for Drug B, we know the mean age of their patients was exactly **65.0 years**. In our trial for Drug A, the mean age is **55.0 years**. Because age is a known prognostic factor (older patients generally have worse outcomes), simply comparing the average outcome of A vs. B would unfairly favor Drug A, as our population is systematically younger and healthier.\n\n### The Goal\n\nWe need to calculate a weight $w_i$ for each patient $i$ in Trial A so that the weighted mean age of Trial A exactly equals 65.0, allowing for a fair \"apples-to-apples\" comparison.\n\n## Methodological Foundation: The Method of Moments {#3-methodology}\n\nUnlike Bayesian NMA, the standard MAIC weight calculation is purely frequentist. The **weights are modeled as an exponential function of the baseline covariates** to ensure they remain strictly positive:\n\n$$w_i = \\exp(\\alpha_0 + x_i^T \\alpha_1)$$\n\nWhere:\n\n- $w_i$ is the final weight assigned to patient $i$ in Trial A.\n- $x_i$ represents the centered covariates for patient $i$ in Trial A (centered around the published aggregate mean of Trial B).\n- $x_i^T$: The transpose of the covariate vector $x_i$. This matrix notation represents the dot product of covariates and coefficients. For a single covariate, this simply implies scalar multiplication $x_i \\cdot \\alpha_1$.\n- $\\alpha_1$ is the vector of coefficients we need to estimate via optimization.\n- $\\alpha_0$ is a scaling constant (not an optimization parameter). It is calculated *after* finding the optimal $\\alpha_1$ to ensure that the sum of the weights equals the original sample size $N_A$ (i.e., $\\sum w_i = N_A$). Mathematically, $\\exp(\\alpha_0) = N_A / \\sum \\exp(x_i^T \\alpha_1)$.\n\nWe find the optimal $\\alpha_1$ by **minimizing an objective function** (using the Method of Moments). Specifically, we minimize the sum of the unnormalized weights:\n\n$$Q(\\alpha_1) = \\sum_{i=1}^N \\exp(x_i^T \\alpha_1)$$\n\nBy finding the $\\alpha_1$ that minimizes this convex function, its gradient becomes zero, which mathematically guarantees that the weighted mean of the centered covariates in Trial A equals zero (and thus matches Trial B).\n\n```{=html}\n<!-- Audit Point: Why alpha0 is calculated last\nTo understand the workflow of finding weights, think of it as a 3-step process:\n1. Find alpha1: Minimize Q(alpha1) to find the optimal coefficients that achieve balance.\n2. Calculate Raw Weights: Compute w_i_tilde = exp(x_i^T * alpha1) for each patient. These weights already achieve the perfect match!\n3. Normalize with alpha0: The sum of raw weights might not equal the original sample size N_A. To make the weights sum to N_A (a standard reporting practice), we multiply everyone by a constant factor C = N_A / sum(w_i_tilde). Since exp(alpha0) = C, this is where alpha0 comes from.\n-->\n```\n\n### Entropy Balancing vs. Inverse Probability Weighting (IPW)\n\nWhile MAIC is often categorized broadly as a propensity score method, its mathematical engine is distinct from traditional Inverse Probability Weighting (IPW):\n\n- **IPW (Propensity Score Weighting)**:\n  - **Mechanism**: Estimates the probability of a patient belonging to Trial A vs. Trial B (usually via logistic regression) and applies weights proportional to `1/PS`.\n  - **Limitations**: Requires Individual Patient Data (IPD) for both trials. Furthermore, it does not guarantee exact moment matching in small samples; it only achieves balance asymptotically.\n- **Entropy Balancing (The MAIC Approach)**:\n  - **Mechanism**: Directly searches for weights that satisfy the moment conditions (e.g., sample mean of A = published mean of B) while keeping the weights as close to uniform as possible (maximizing the entropy of the weights).\n  - **Advantages**: Only requires IPD for the index trial and Aggregate Data (AgD) for the target trial. It guarantees **perfect alignment** of the specified moments by design.\n\n### Effective Sample Size (ESS) Diagnosis\n\nAfter calculating the MAIC weights, the most critical diagnostic metric to evaluate is the **Effective Sample Size (ESS)**:\n\n$$ESS = \\frac{(\\sum w_i)^2}{\\sum w_i^2}$$\n\nIn HTA audits, the ESS is scrutinized under the following principles:\n\n1.  **The Threshold of Validity**: A severe drop in ESS (e.g., from 200 patients down to an ESS of 20, or \\<15% of the original sample size) indicates that the populations of Trial A and Trial B have very little overlap.\n2.  **Weight Distribution**: If the ESS is small, the matching relies heavily on just a few outlier patients in Trial A who happen to look like the average patient in Trial B. These patients will receive massive weights, making the final comparison highly unstable and unrepresentative.\n3.  **Reporting Requirements**: Manufacturers are required to report both the original sample size and the ESS, alongside **histograms of the weight distribution** to prove that no single patient dominates the analysis.\n\n## Custom R Implementation: Calculating Weights from Scratch {#4-custom-r-implementation}\n\nTo demonstrate a deep understanding of the underlying mathematics, we will manually implement the objective function and use R's `optim()` to solve for the weights, rather than hiding behind a black-box package.\n\n```{=html}\n<!-- Audit Point: Real-world Workflow vs Simulation\nIn real-world practice, you DO NOT simulate the outcome Y_A. You receive the IPD dataset with real outcomes for each patient. \nThe workflow is:\n1. Calculate weights using ONLY covariates (ignoring Y_A entirely to prevent bias).\n2. Apply the weights to Y_A to get the weighted mean for Trial A.\n3. Compare that single weighted mean with the published mean of Trial B.\n-->\n```\n\n::: {.callout-note collapse=\"true\" appearance=\"minimal\"}\n# Click to view R Simulation and Custom MAIC Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n\n# ---------------------------------------------------------\n# 1. Simulate Mock Data\n# ---------------------------------------------------------\nN_A <- 200\n# Drug A (IPD): Mean age = 55, SD = 8\nage_A <- rnorm(N_A, mean = 55, sd = 8)\n# True outcome for Drug A (True effect = 10, minus 0.5 per year of age)\ny_A <- rnorm(N_A, mean = 10 - 0.5 * (age_A - 55), sd = 2)\ndf_A <- data.frame(id = 1:N_A, age = age_A, y = y_A)\n\n# Drug B (AgD published data)\nmean_age_B <- 65.0\n# True outcome for B if they were age 65 would be, say, 3.0\nmean_y_B_published <- 3.0\n\n# Naive comparison (Unadjusted)\nmean_y_A_naive <- mean(df_A$y)\n\n# ---------------------------------------------------------\n# 2. Custom MAIC Weight Calculation (Method of Moments)\n# ---------------------------------------------------------\n# Step A: Center the IPD covariates around the AgD targets\n# This makes the math easier: we want the weighted mean of the centered covariate to be 0.\ndf_A$age_centered <- df_A$age - mean_age_B\n\n# Step B: Define the Objective Function to minimize\n# The objective is sum(exp(X * alpha1))\nobj_fn <- function(alpha1, X) {\n    sum(exp(X %*% alpha1))\n}\n\n# Step C: Define the Gradient Function (for faster/stable optimization)\n# The gradient is sum(X * exp(X * alpha1))\ngrad_fn <- function(alpha1, X) {\n    colSums(X * as.vector(exp(X %*% alpha1)))\n}\n\n# Step D: Optimize to find alpha1\nX_matrix <- as.matrix(df_A$age_centered)\nopt_res <- optim(\n    par = 0, # Initial guess\n    fn = obj_fn,\n    gr = grad_fn,\n    X = X_matrix,\n    method = \"BFGS\"\n)\nalpha1 <- opt_res$par\n\n# Step E: Calculate individual weights\nunnormalized_w <- exp(X_matrix %*% alpha1)\n# Normalize so sum(w) = N_A (optional, but standard for interpretability)\nw <- unnormalized_w / sum(unnormalized_w) * N_A\ndf_A$weight <- as.vector(w)\n\n# ---------------------------------------------------------\n# 3. Validation & Outcome Comparison\n# ---------------------------------------------------------\n# Check covariate balance\nweighted_mean_age_A <- sum(df_A$age * df_A$weight) / sum(df_A$weight)\n\n# Calculate Effective Sample Size (ESS)\nESS <- (sum(df_A$weight)^2) / sum(df_A$weight^2)\n\n# Calculate MAIC-adjusted outcome for Drug A\nmean_y_A_maic <- sum(df_A$y * df_A$weight) / sum(df_A$weight)\n```\n:::\n\n:::\n\n### Results & Validation\n\nAfter running the custom optimization, we can verify that the weights successfully matched the baseline characteristics:\n\n| Metric | Drug A (Naive IPD) | Drug A (MAIC Weighted) | Drug B (AgD Target) |\n|:-----------------|:----------------:|:----------------:|:----------------:|\n| **Mean Age** | 54.9 | **65** | 65 |\n| **Effective Sample Size (ESS)** | 200 | **41** | N/A |\n| **Mean Outcome** $y$ | 10.12 | **5.37** | 3 |\n\nNotice that the naive comparison (10.12 vs 3) is highly biased because Trial A patients are much younger. After MAIC weighting, the mean age of Trial A is artificially shifted to exactly 65, and the adjusted outcome drops to 5.37. This provides a much fairer \"apples-to-apples\" comparison against Drug B, albeit at the cost of statistical power (ESS dropped to 41).\n\n## Industry Standard Alternative: `maicplus` Package {#5-maic-package}\n\nWhile calculating the weights via `optim()` demonstrates the mathematical rigor behind the method, industry practitioners typically use dedicated R packages like **`maicplus`** (developed by the Roche team and available on CRAN) to streamline the process, handle multiple covariates, and automatically compute standard errors.\n\nHere is how the above analysis would be executed using the `maicplus` package (syntax example):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(maicplus)\n\n# Add ARM column (required by maicplus by default)\ndf_A$ARM <- \"A\"\n\n# Use the manually centered variable 'age_centered' created earlier\nmaic_res <- estimate_weights(\n    data = df_A,\n    centered_colnames = \"age_centered\"\n)\n\n# View Effective Sample Size (ESS) calculated by the package\ncat(\"ESS calculated by maicplus: \", maic_res$ess, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nESS calculated by maicplus:  40.984 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate MAIC-adjusted outcome using the package's scaled weights\nmean_y_A_maicplus <- sum(maic_res$data$y * maic_res$data$scaled_weights) / sum(maic_res$data$scaled_weights)\ncat(\"Adjusted mean outcome: \", mean_y_A_maicplus, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAdjusted mean outcome:  5.370661 \n```\n\n\n:::\n:::\n\n\n## Outcome Analysis: The Final Comparison {#6-outcome-analysis}\n\nNow that we have the matched weights and the adjusted outcome for Drug A, we can complete the indirect comparison.\n\n```{=html}\n<!-- Audit Point: The Fundamental Limitation of MAIC (Pseudo-IPD)\nNotice that in the final comparison, we are reducing Trial A's IPD to a single weighted summary number to compare it with Trial B's published summary. \nThis means MAIC is actually an Aggregate-Level comparison at the end. \n- Why? Because we don't have IPD for Trial B, we are forced to step down to the lowest common denominator.\n- Does it waste IPD? IPD is used as a source of flexibility to match the populations. Without it, we couldn't adjust at all. But it is not a full individual-level regression.\n-->\n```\n\n### Point Estimate of the Treatment Effect\n\nIn our unanchored scenario, the comparative treatment effect ($\\Delta$) is simply the difference between the MAIC-adjusted mean outcome of Drug A and the published mean outcome of Drug B.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Point Estimate\ntreatment_effect <- mean_y_A_maic - mean_y_B_published\ncat(\"Point Estimate of Treatment Effect (A vs B): \", treatment_effect, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPoint Estimate of Treatment Effect (A vs B):  2.370661 \n```\n\n\n:::\n:::\n\n\n### Quantifying Uncertainty via Bootstrapping\n\nWe cannot use standard t-test formulas to calculate the standard error of this treatment effect because the weights themselves are random variables estimated from the data.\n\nIn real-world HTA submissions, practitioners use **Bootstrapping** to calculate the 95% Confidence Interval. This involves repeatedly resampling the IPD data with replacement, recalculating the MAIC weights each time, and generating a distribution of the treatment effect.\n\nHere is a minimal demonstration of the bootstrapping workflow (using 100 iterations for speed, though 2000+ is standard in practice):\n\n::: {.callout-note collapse=\"true\" appearance=\"minimal\"}\n# Click to view Bootstrapping Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_boot <- 100\nboot_effects <- numeric(n_boot)\n\nfor (b in 1:n_boot) {\n    # Step A: Resample IPD with replacement\n    boot_idx <- sample(1:N_A, size = N_A, replace = TRUE)\n    df_A_boot <- df_A[boot_idx, ]\n\n    # Step B: Recalculate weights (using our custom optim approach)\n    X_boot <- as.matrix(df_A_boot$age_centered)\n    opt_boot <- optim(par = 0, fn = obj_fn, gr = grad_fn, X = X_boot, method = \"BFGS\")\n\n    w_boot <- exp(X_boot %*% opt_boot$par)\n    w_boot <- w_boot / sum(w_boot) * N_A\n\n    # Step C: Calculate weighted outcome for A and the Delta\n    mean_y_A_boot <- sum(df_A_boot$y * w_boot) / sum(w_boot)\n    boot_effects[b] <- mean_y_A_boot - mean_y_B_published\n}\n\n# Calculate 95% CI from percentiles\nci_lower <- quantile(boot_effects, 0.025)\nci_upper <- quantile(boot_effects, 0.975)\nse_boot <- sd(boot_effects)\ncat(\"Bootstrapped SE: \", se_boot, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrapped SE:  0.2711255 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Bootstrapped 95% CI: [\", ci_lower, \", \", ci_upper, \"]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBootstrapped 95% CI: [ 1.822798 ,  2.895264 ]\n```\n\n\n:::\n:::\n\n:::\n\n### Final Results\n\nWith the point estimate and the bootstrapped standard error, we can now present the complete MAIC indirect comparison results as they would appear in an HTA dossier:\n\n| Metric | Estimate | 95% CI Lower | 95% CI Upper |\n|:-----------------|:----------------:|:----------------:|:----------------:|\n| **Naive Difference** | 7.12 | N/A | N/A |\n| **MAIC Adjusted Difference** | **2.37** | **1.82** | **2.9** |\n\n```{=html}\n<!-- Audit Point: Sandwich vs Bootstrap\nWhile bootstrapping is universally accepted by HTA bodies like NICE, it can be computationally intensive, especially with large datasets or complex models. An alternative is the **Sandwich Estimator** (Robust Standard Errors), which calculates the variance analytically without simulation. The `maicplus` package supports both methods.\n-->\n```\n\n## Sensitivity Analysis in MAIC {#7-sensitivity}\n\nHTA agencies (such as NICE) rarely accept a single MAIC result. Because the method relies on the unverified assumption that all effect modifiers have been accounted for, rigorous sensitivity analyses are mandatory:\n\n```{=html}\n<!-- Audit Point: Covariate Selection and the Bias-Variance Trade-off\nIn our simple mock case, we only have one covariate (Age), so there is no choice to make. However, in real-world HTA submissions, the competitor's publication might report a dozen baseline characteristics. \nModellers face a severe \"Bias-Variance Trade-off\":\n- Matching on all available covariates guarantees perfect balance but often causes the ESS to plummet to an unacceptably low number (as extreme weights are assigned to a few patients to achieve balance in a high-dimensional space).\n- Matching on too few covariates preserves a large ESS but risks leaving residual confounding.\nThis is why presenting multiple \"Covariate Selection Scenarios\" is a mandatory part of any MAIC sensitivity analysis requested by agencies like NICE.\n-->\n```\n\n1.  **Covariate Selection Scenarios**: Modellers must present results using different sets of matching covariates:\n    - Base Case: Matching only on covariates agreed upon in the Statistical Analysis Plan (SAP) or clinical consensus.\n    - Scenario A: Adding borderline prognostic factors.\n    - Scenario B: Dropping covariates with high missingness.\n2.  **Matching Higher Moments**: Standard MAIC matches the means (first moment). Sensitivity analysis involves matching both the means and the variances (second moment, by including squared terms of covariates in the matching algorithm) to ensure the distribution shapes are comparable.\n3.  **The Bias-Variance Trade-off Curve**: As more covariates are added to the matching algorithm, bias decreases but the weights become more extreme, causing the ESS to plummet (variance inflates). Presenting a curve of Treatment Effect vs. ESS helps reviewers judge the robustness of the matching strategy.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}