<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Xiaoge Zhang, PhD">
<meta name="dcterms.date" content="2026-05-24">

<title>Survival Analysis &amp; Immortal Time Bias in Real-World Evidence – HEOR Technical Portfolio</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-8c38fd85d21bfe44b50360969156fb14.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../custom.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">HEOR Technical Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-flagship-audits" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Flagship Audits</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-flagship-audits">    
        <li>
    <a class="dropdown-item" href="../../05_TA975_CAR-T_Case/TA975_Mock_Case.html">
 <span class="dropdown-text">NICE TA975 (CAR-T) Case</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../03_Bayesian_NMA_Reconstruction/MLNMR_Flagship_Case.html">
 <span class="dropdown-text">ML-NMR: AML Population Alignment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../02_RWE_Causal_Inference_Pipeline/RWE_Mock_Case_DLBCL.html">
 <span class="dropdown-text">RWE ECA: R/R DLBCL</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../01_Oncology_PartSM_Audit/PartSM_Forensic_Audit_RRMM.html">
 <span class="dropdown-text">PSM: Survival Extrapolation in RRMM</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-nma-library" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">NMA Library</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-nma-library">    
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/10_Bayesian_Estimation.html">
 <span class="dropdown-text">Bayesian Estimation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/01_Standard_Bayesian_NMA_Guide.html">
 <span class="dropdown-text">Standard Bayesian NMA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/02_Network_Meta_Regression_NMR.html">
 <span class="dropdown-text">Network Meta-Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/03_Survival_NMA.html">
 <span class="dropdown-text">Survival NMA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/04_Component_NMA.html">
 <span class="dropdown-text">Component NMA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/05_IPD_NMA.html">
 <span class="dropdown-text">IPD NMA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/06_MAIC.html">
 <span class="dropdown-text">MAIC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/07_STC.html">
 <span class="dropdown-text">STC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/08_ML_NMR.html">
 <span class="dropdown-text">ML-NMR</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/09_Flexible_Survival.html">
 <span class="dropdown-text">Flexible Survival</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/11_HR_OR_Intuition.html">
 <span class="dropdown-text">HR vs OR Intuition</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-rwe-library" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">RWE Library</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-rwe-library">    
        <li>
    <a class="dropdown-item" href="../../02_RWE_Causal_Inference_Pipeline/01_RWE_Technical_Prep/01_Confounding_and_Frameworks.html">
 <span class="dropdown-text">NICE Framework &amp; Confounding</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../02_RWE_Causal_Inference_Pipeline/01_RWE_Technical_Prep/02_PSM_IPTW_AIPW.html">
 <span class="dropdown-text">PSM, IPTW &amp; AIPW</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../02_RWE_Causal_Inference_Pipeline/01_RWE_Technical_Prep/03_TMLE_and_Sensitivity.html">
 <span class="dropdown-text">TMLE &amp; Sensitivity Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../02_RWE_Causal_Inference_Pipeline/01_RWE_Technical_Prep/04_Time_to_Event_and_Immortal_Time.html">
 <span class="dropdown-text">Survival &amp; Immortal Time</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../00_HTA_LLM_Wiki/README.html"> 
<span class="menu-text">Methodology Wiki</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Qsev/XGZ-HEOR-Portfolio" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-causal-inference-in-time-to-event-data" id="toc-introduction-causal-inference-in-time-to-event-data" class="nav-link active" data-scroll-target="#introduction-causal-inference-in-time-to-event-data"><span class="header-section-number">1</span> Introduction: Causal Inference in Time-to-Event Data</a>
  <ul class="collapse">
  <li><a href="#the-coffee-heart-disease-paradox-reverse-causality" id="toc-the-coffee-heart-disease-paradox-reverse-causality" class="nav-link" data-scroll-target="#the-coffee-heart-disease-paradox-reverse-causality"><span class="header-section-number">1.1</span> The Coffee &amp; Heart Disease Paradox (Reverse Causality)</a></li>
  </ul></li>
  <li><a href="#the-target-trial-emulation-tte-framework" id="toc-the-target-trial-emulation-tte-framework" class="nav-link" data-scroll-target="#the-target-trial-emulation-tte-framework"><span class="header-section-number">2</span> The Target Trial Emulation (TTE) Framework</a>
  <ul class="collapse">
  <li><a href="#the-7-pillars-of-target-trial-emulation" id="toc-the-7-pillars-of-target-trial-emulation" class="nav-link" data-scroll-target="#the-7-pillars-of-target-trial-emulation"><span class="header-section-number">2.1</span> The 7 Pillars of Target Trial Emulation</a></li>
  <li><a href="#deep-dive-the-new-user-design" id="toc-deep-dive-the-new-user-design" class="nav-link" data-scroll-target="#deep-dive-the-new-user-design"><span class="header-section-number">2.2</span> Deep Dive: The New User Design</a></li>
  <li><a href="#deep-dive-intention-to-treat-itt-in-rwd-cloning-censoring" id="toc-deep-dive-intention-to-treat-itt-in-rwd-cloning-censoring" class="nav-link" data-scroll-target="#deep-dive-intention-to-treat-itt-in-rwd-cloning-censoring"><span class="header-section-number">2.3</span> Deep Dive: Intention-to-Treat (ITT) in RWD (Cloning &amp; Censoring)</a></li>
  <li><a href="#auditors-view-why-tte-simple-regression" id="toc-auditors-view-why-tte-simple-regression" class="nav-link" data-scroll-target="#auditors-view-why-tte-simple-regression"><span class="header-section-number">2.4</span> Auditor’s View: Why TTE &gt; Simple Regression</a></li>
  </ul></li>
  <li><a href="#hta-case-study-drug-x-metex14-case-study" id="toc-hta-case-study-drug-x-metex14-case-study" class="nav-link" data-scroll-target="#hta-case-study-drug-x-metex14-case-study"><span class="header-section-number">3</span> HTA Case Study: Drug X (METex14) Case Study</a>
  <ul class="collapse">
  <li><a href="#case-overview-the-drug-x-conflict" id="toc-case-overview-the-drug-x-conflict" class="nav-link" data-scroll-target="#case-overview-the-drug-x-conflict"><span class="header-section-number">3.1</span> Case Overview: The Drug X Conflict</a></li>
  <li><a href="#step-1-data-suitability-audit-datasat" id="toc-step-1-data-suitability-audit-datasat" class="nav-link" data-scroll-target="#step-1-data-suitability-audit-datasat"><span class="header-section-number">3.2</span> Step 1: Data Suitability Audit (DataSAT)</a></li>
  <li><a href="#defining-t_0-zero-time-alignment" id="toc-defining-t_0-zero-time-alignment" class="nav-link" data-scroll-target="#defining-t_0-zero-time-alignment"><span class="header-section-number">3.3</span> Defining <span class="math inline">\(T_0\)</span> (Zero-time Alignment)</a></li>
  <li><a href="#step-2-cloning-censoring-mechanics" id="toc-step-2-cloning-censoring-mechanics" class="nav-link" data-scroll-target="#step-2-cloning-censoring-mechanics"><span class="header-section-number">3.4</span> Step 2: Cloning &amp; Censoring Mechanics</a></li>
  </ul></li>
  <li><a href="#immortal-time-bias-itb-theory-landmark-analysis" id="toc-immortal-time-bias-itb-theory-landmark-analysis" class="nav-link" data-scroll-target="#immortal-time-bias-itb-theory-landmark-analysis"><span class="header-section-number">4</span> Immortal Time Bias (ITB): Theory &amp; Landmark Analysis</a>
  <ul class="collapse">
  <li><a href="#the-meditation-longevity-paradox" id="toc-the-meditation-longevity-paradox" class="nav-link" data-scroll-target="#the-meditation-longevity-paradox"><span class="header-section-number">4.1</span> The Meditation &amp; Longevity Paradox</a></li>
  <li><a href="#violating-the-non-anticipatory-constraint" id="toc-violating-the-non-anticipatory-constraint" class="nav-link" data-scroll-target="#violating-the-non-anticipatory-constraint"><span class="header-section-number">4.2</span> Violating the “Non-anticipatory Constraint”</a></li>
  <li><a href="#landmark-analysis" id="toc-landmark-analysis" class="nav-link" data-scroll-target="#landmark-analysis"><span class="header-section-number">4.3</span> Landmark Analysis</a></li>
  </ul></li>
  <li><a href="#time-dependent-cox-model-hta-practice" id="toc-time-dependent-cox-model-hta-practice" class="nav-link" data-scroll-target="#time-dependent-cox-model-hta-practice"><span class="header-section-number">5</span> Time-Dependent Cox Model &amp; HTA Practice</a>
  <ul class="collapse">
  <li><a href="#counting-process-data-structure" id="toc-counting-process-data-structure" class="nav-link" data-scroll-target="#counting-process-data-structure"><span class="header-section-number">5.1</span> Counting Process Data Structure</a></li>
  <li><a href="#landmark-vs.-time-dependent-cox" id="toc-landmark-vs.-time-dependent-cox" class="nav-link" data-scroll-target="#landmark-vs.-time-dependent-cox"><span class="header-section-number">5.2</span> Landmark vs.&nbsp;Time-Dependent Cox</a></li>
  </ul></li>
  <li><a href="#r-simulation-validation-of-estimators" id="toc-r-simulation-validation-of-estimators" class="nav-link" data-scroll-target="#r-simulation-validation-of-estimators"><span class="header-section-number">6</span> R Simulation: Validation of Estimators</a>
  <ul class="collapse">
  <li><a href="#simulating-the-cohort-and-biased-analysis" id="toc-simulating-the-cohort-and-biased-analysis" class="nav-link" data-scroll-target="#simulating-the-cohort-and-biased-analysis"><span class="header-section-number">6.1</span> Simulating the Cohort and Biased Analysis</a></li>
  <li><a href="#method-1-landmark-analysis-day-90" id="toc-method-1-landmark-analysis-day-90" class="nav-link" data-scroll-target="#method-1-landmark-analysis-day-90"><span class="header-section-number">6.2</span> Method 1: Landmark Analysis (Day 90)</a></li>
  <li><a href="#method-2-time-varying-cox-model" id="toc-method-2-time-varying-cox-model" class="nav-link" data-scroll-target="#method-2-time-varying-cox-model"><span class="header-section-number">6.3</span> Method 2: Time-Varying Cox Model</a></li>
  </ul></li>
  <li><a href="#causal-evidence-reconciliation" id="toc-causal-evidence-reconciliation" class="nav-link" data-scroll-target="#causal-evidence-reconciliation"><span class="header-section-number">7</span> Causal Evidence Reconciliation</a></li>
  <li><a href="#quantitative-bias-analysis-e-value-sensitivity-analysis" id="toc-quantitative-bias-analysis-e-value-sensitivity-analysis" class="nav-link" data-scroll-target="#quantitative-bias-analysis-e-value-sensitivity-analysis"><span class="header-section-number">8</span> Quantitative Bias Analysis: E-Value Sensitivity Analysis</a>
  <ul class="collapse">
  <li><a href="#e-value-math-formula-setup" id="toc-e-value-math-formula-setup" class="nav-link" data-scroll-target="#e-value-math-formula-setup"><span class="header-section-number">8.1</span> E-Value Math &amp; Formula Setup</a></li>
  <li><a href="#algebraic-derivation-of-the-e-value-vanderweele-ding-2016" id="toc-algebraic-derivation-of-the-e-value-vanderweele-ding-2016" class="nav-link" data-scroll-target="#algebraic-derivation-of-the-e-value-vanderweele-ding-2016"><span class="header-section-number">8.2</span> Algebraic Derivation of the E-Value (VanderWeele &amp; Ding 2016)</a></li>
  </ul></li>
  <li><a href="#hta-audit-interview-guide" id="toc-hta-audit-interview-guide" class="nav-link" data-scroll-target="#hta-audit-interview-guide"><span class="header-section-number">9</span> HTA Audit &amp; Interview Guide</a>
  <ul class="collapse">
  <li><a href="#interview-audit-checklist" id="toc-interview-audit-checklist" class="nav-link" data-scroll-target="#interview-audit-checklist"><span class="header-section-number">9.1</span> Interview Audit Checklist</a></li>
  <li><a href="#expert-hta-articulation" id="toc-expert-hta-articulation" class="nav-link" data-scroll-target="#expert-hta-articulation"><span class="header-section-number">9.2</span> Expert HTA Articulation</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Survival Analysis &amp; Immortal Time Bias in Real-World Evidence</h1>
<p class="subtitle lead">Target Trial Emulation, Landmark Analysis, and Time-Varying Cox Regression</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Xiaoge Zhang, PhD </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 24, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><em>Methodological guidelines and implementation templates for survival analysis, delayed treatment initiation, and target trial emulation in health technology assessment.</em></p>
<section id="introduction-causal-inference-in-time-to-event-data" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction-causal-inference-in-time-to-event-data"><span class="header-section-number">1</span> Introduction: Causal Inference in Time-to-Event Data</h2>
<p>In health technology assessment (HTA), clinical endpoints are frequently <strong>time-to-event outcomes</strong>. While aggregate summaries like Overall Survival (OS) or Progression-Free Survival (PFS) are represented as curves showing the <em>proportion</em> or <em>probability</em> of surviving patients at specific points in time, the underlying outcome measured at the patient level is the actual <strong>duration of time</strong> (e.g., months or days) elapsed from a defined baseline (such as diagnosis or treatment initiation) until the clinical event of interest (e.g., death, relapse) occurs.</p>
<p>Unlike binary outcomes where logistic regression or propensity score matching are applied statically, survival data introduces a critical dimension: <strong>Time</strong>.</p>
<p>If time-to-event analysis is not bounded by strict causal constraints, observational analyses can yield severe selection biases. A primary methodological challenge in retrospective registries is <strong>Immortal Time Bias (ITB)</strong>.</p>
<section id="the-coffee-heart-disease-paradox-reverse-causality" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="the-coffee-heart-disease-paradox-reverse-causality"><span class="header-section-number">1.1</span> The Coffee &amp; Heart Disease Paradox (Reverse Causality)</h3>
<p>To understand why simple observational survival analysis fails, consider the “Coffee &amp; Heart Disease Paradox”:</p>
<ul>
<li><strong>The Observation</strong>: A cross-sectional analysis or simple regression shows that people who drink coffee have significantly lower rates of heart disease (e.g., Hazard Ratio &lt; 1.0).</li>
<li><strong>The Reality</strong>: This is driven by reverse causality. Patients who <em>already</em> have heart problems or are at high risk are often advised by their doctors to quit coffee.</li>
<li><strong>The Trap</strong>: If we run a regression on cross-sectional data, we see “Coffee = Health.”</li>
</ul>
<p>To resolve this paradox, we cannot rely on simple regression adjustments; we must emulate a randomized trial to establish a clear chronological sequence of events.</p>
<hr>
</section>
</section>
<section id="the-target-trial-emulation-tte-framework" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="the-target-trial-emulation-tte-framework"><span class="header-section-number">2</span> The Target Trial Emulation (TTE) Framework</h2>
<p>Target Trial Emulation is a structured design framework developed by Miguel Hernán and colleagues to guide the design and analysis of observational studies. The core principle is that <strong>we should design our observational study to mimic a hypothetical randomized trial as closely as possible.</strong></p>
<section id="the-7-pillars-of-target-trial-emulation" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="the-7-pillars-of-target-trial-emulation"><span class="header-section-number">2.1</span> The 7 Pillars of Target Trial Emulation</h3>
<p>To translate observational data into robust evidence, researchers must define a protocol addressing seven protocol components:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Pillar</th>
<th style="text-align: left;">NICE RWE Framework Requirement</th>
<th style="text-align: left;">Application to Survival Cohorts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>1. Eligibility</strong></td>
<td style="text-align: left;">Define clear inclusion/exclusion criteria at baseline.</td>
<td style="text-align: left;">Patients must meet all criteria at Time Zero (<span class="math inline">\(T_0\)</span>), ensuring no baseline selection bias.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>2. Treatment Strategy</strong></td>
<td style="text-align: left;">Specify the interventions being compared.</td>
<td style="text-align: left;"><strong>Arm A:</strong> Initiate active treatment within a defined window. <strong>Arm B:</strong> Initiate Standard of Care (SOC) / no treatment.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>3. Assignment</strong></td>
<td style="text-align: left;">Define how treatment groups are formed.</td>
<td style="text-align: left;">Emulate randomization at <span class="math inline">\(T_0\)</span> using Propensity Scores (IPTW or matching) based on baseline covariates.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>4. Follow-up</strong></td>
<td style="text-align: left;">Align follow-up start exactly with <span class="math inline">\(T_0\)</span>.</td>
<td style="text-align: left;">Clock starts ticking for all patients at <span class="math inline">\(T_0\)</span>. Ends at the event, death, censoring, or study end.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>5. Outcome</strong></td>
<td style="text-align: left;">Define a standardized clinical endpoint.</td>
<td style="text-align: left;">First occurrence of the event (e.g., death, progression) during the follow-up period.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>6. Causal Contrast</strong></td>
<td style="text-align: left;">Specify the effect of interest.</td>
<td style="text-align: left;"><strong>Intention-to-Treat (ITT):</strong> Effect of treatment assignment at <span class="math inline">\(T_0\)</span>, regardless of later compliance.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>7. Analysis Plan</strong></td>
<td style="text-align: left;">Specify the statistical estimator.</td>
<td style="text-align: left;">Cox Proportional Hazards model or parametric survival models, adjusted for baseline confounding.</td>
</tr>
</tbody>
</table>
</section>
<section id="deep-dive-the-new-user-design" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="deep-dive-the-new-user-design"><span class="header-section-number">2.2</span> Deep Dive: The New User Design</h3>
<p>A fundamental rule of TTE is the <strong>New User Design</strong>. In observational studies, researchers often mistakenly compare “prevalent users” (patients already on the drug for some time) with “never users.” This introduces three major issues:</p>
<ul>
<li><strong>Survivor Bias</strong>: Prevalent users are, by definition, “survivors” who have tolerated the drug and survived long enough to be observed in the database. Patients who died or discontinued the drug early due to adverse events are systematically excluded from the treated group, creating a false survival advantage.</li>
<li><strong>Baseline Contamination</strong>: To adjust for confounding, we must measure covariates <em>before</em> treatment starts. For prevalent users, their baseline measurements (e.g., blood pressure, lab values) are already affected by the treatment, making it impossible to measure their true pre-treatment state.</li>
<li><strong><span class="math inline">\(T_0\)</span> Synchronization</strong>: We cannot align the start of follow-up with the start of treatment if treatment began years before the observation period.</li>
</ul>
<p>A New User Design enforces that patients are only entered into the cohort at the exact moment they <strong>initiate</strong> the treatment of interest.</p>
</section>
<section id="deep-dive-intention-to-treat-itt-in-rwd-cloning-censoring" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="deep-dive-intention-to-treat-itt-in-rwd-cloning-censoring"><span class="header-section-number">2.3</span> Deep Dive: Intention-to-Treat (ITT) in RWD (Cloning &amp; Censoring)</h3>
<p>In randomized trials, the ITT principle analyzes patients in the group they were randomized to, regardless of whether they complied. In retrospective RWD, we often face a “grace period”—a window of time (e.g., 30 or 60 days) after diagnosis during which patients are allowed to initiate treatment.</p>
<p>If we assign patients to the “treated” group because they initiated treatment on day 30, we violate the ITT principle by using “future knowledge” at <span class="math inline">\(T_0\)</span>. To solve this, TTE uses <strong>Cloning</strong>:</p>
<ol type="1">
<li><strong>Cloning at <span class="math inline">\(T_0\)</span></strong>: At the moment of eligibility (<span class="math inline">\(T_0\)</span>), we create two identical copies of each patient. One copy is assigned to Arm A (Initiate Treatment), and one copy is assigned to Arm B (Standard of Care).</li>
<li><strong>Follow-up</strong>: Both clones begin follow-up at <span class="math inline">\(T_0\)</span>.</li>
<li><strong>Censoring</strong>: If a patient assigned to Arm B initiates treatment on day 30, their Arm B clone is <strong>censored</strong> at day 30 (because they violated the “no treatment” protocol). The Arm A clone continues to be followed.</li>
<li><strong>IPCW Adjustment</strong>: To correct for selection bias introduced by this artificial censoring, we apply <strong>Inverse Probability of Censoring Weights (IPCW)</strong>, which upweights the remaining uncensored clones who share similar baseline characteristics.</li>
</ol>
</section>
<section id="auditors-view-why-tte-simple-regression" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="auditors-view-why-tte-simple-regression"><span class="header-section-number">2.4</span> Auditor’s View: Why TTE &gt; Simple Regression</h3>
<p>NICE prefers TTE because it enforces <strong>Transparency</strong>.</p>
<p>In a simple Cox regression, you often see: <span class="math display">\[\text{Surv}(\text{time}, \text{event}) \sim \text{Treatment} + \text{Confounders}\]</span></p>
<p>An auditor cannot see:</p>
<ul>
<li>When was the treatment started?</li>
<li>Were the confounders measured <em>before</em> or <em>after</em> the drug was given?</li>
<li>Is there a “Healthy User Bias”?</li>
</ul>
<p>By using the <strong>DataSAT</strong> tool (Data Suitability Assessment Tool), NICE auditors look for <strong>Provenance</strong>—the clear lineage of how a patient moved from a raw database record to a study row. TTE forces the researcher to write a “Trial Protocol” <em>before</em> touching the data, making it obvious where <span class="math inline">\(T_0\)</span> is. If an auditor sees that you measured covariates after the drug was given and used them as baseline, the TTE framework will flag this as a “Post-baseline Bias” immediately.</p>
<hr>
</section>
</section>
<section id="hta-case-study-drug-x-metex14-case-study" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="hta-case-study-drug-x-metex14-case-study"><span class="header-section-number">3</span> HTA Case Study: Drug X (METex14) Case Study</h2>
<p>To see how these principles apply to a real submission, we examine the case of <strong>Drug X</strong>, a precision oncology therapy for METex14-mutated non-small cell lung cancer (NSCLC).</p>
<section id="case-overview-the-drug-x-conflict" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="case-overview-the-drug-x-conflict"><span class="header-section-number">3.1</span> Case Overview: The Drug X Conflict</h3>
<ul>
<li><strong>The Innovation</strong>: Due to the rarity of the METex14 mutation and ethical constraints, only a <strong>Single-arm Trial (N=40)</strong> was conducted for Drug X.</li>
<li><strong>The Objection</strong>: The Evidence Assessment Group (EAG) flagged the submission as “high risk” because there was no randomized head-to-head comparison. Natural history for METex14 is aggressive, and simple benchmarking is insufficient.</li>
<li><strong>The Strategy</strong>: We leverage the UK Hospital Episode Statistics (HES) database to construct an External Control Arm (ECA) of 200 patients, using the Target Trial Emulation (TTE) framework to satisfy NICE’s demand for rigorous causal inference.</li>
</ul>
</section>
<section id="step-1-data-suitability-audit-datasat" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="step-1-data-suitability-audit-datasat"><span class="header-section-number">3.2</span> Step 1: Data Suitability Audit (DataSAT)</h3>
<p>According to Sections 3.1–3.3 of the NICE RWE Framework, we must prove the data is fit for purpose across three core dimensions:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimension</th>
<th style="text-align: left;">HTA Audit Response (HES Database)</th>
<th style="text-align: left;">NICE Framework Requirement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Provenance</strong></td>
<td style="text-align: left;">Data sourced from NHS Digital with a clear audit trail from ICD-10 coding to the final analytical dataset.</td>
<td style="text-align: left;">Evaluate the <strong>origin and trustworthiness</strong> of data sources, methods of collection, and governance. (Section 3.1)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Quality</strong></td>
<td style="text-align: left;">METex14 status confirmed via secondary linkage to SACT and genomic records; completeness checked for key covariates.</td>
<td style="text-align: left;">Assess the <strong>completeness and accuracy</strong> of eligibility criteria, exposures, and outcomes. (Section 3.2)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Relevance</strong></td>
<td style="text-align: left;">HES covers 99% of NHS hospital activity, matching the SOC pathways in the UK.</td>
<td style="text-align: left;">Ensure findings <strong>generalise to the target population</strong> and clinical care pathways in the NHS. (Section 3.3)</td>
</tr>
</tbody>
</table>
</section>
<section id="defining-t_0-zero-time-alignment" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="defining-t_0-zero-time-alignment"><span class="header-section-number">3.3</span> Defining <span class="math inline">\(T_0\)</span> (Zero-time Alignment)</h3>
<p>To avoid Immortal Time Bias, we align <span class="math inline">\(T_0\)</span> as the moment a patient meets all eligibility criteria <strong>AND</strong> is assigned to treatment (Section 5.2).</p>
<section id="why-immortal-time-bias-is-a-statistical-killer" class="level4" data-number="3.3.1">
<h4 data-number="3.3.1" class="anchored" data-anchor-id="why-immortal-time-bias-is-a-statistical-killer"><span class="header-section-number">3.3.1</span> Why Immortal Time Bias is a “Statistical Killer”</h4>
<ol type="1">
<li><p><strong>Logic Paradox</strong>: In RWD studies, patients from diagnosis to actual treatment initiation (Drug X) face delays (e.g., 1 month). If follow-up begins at diagnosis, but grouping is based on whether they ever received treatment, the period before receiving the drug is <strong>immortal</strong>—if the patient died on Day 15, they would never have lived long enough to receive the drug, and would automatically be classified into the control group.</p></li>
<li><p><strong>Case Simulation</strong>:</p>
<ul>
<li><strong>Patient A</strong>: Diagnosed Jan 1, scheduled for Drug X, dies Jan 15 (unexposed). Classified as Control.</li>
<li><strong>Patient B</strong>: Diagnosed Jan 1, initiates Drug X Feb 1, survives until June.</li>
<li><strong>Result</strong>: The Drug Y/X group artificially filters out those who die before drug administration, inflating the active group’s survival.</li>
</ul></li>
<li><p><strong>TTE Surgery</strong>: The clock must start ticking exactly at treatment initiation, or grace periods must be modeled using cloning.</p></li>
</ol>
</section>
<section id="the-control-arm-t_0" class="level4" data-number="3.3.2">
<h4 data-number="3.3.2" class="anchored" data-anchor-id="the-control-arm-t_0"><span class="header-section-number">3.3.2</span> The Control Arm <span class="math inline">\(T_0\)</span></h4>
<p>Where does the control arm’s <span class="math inline">\(T_0\)</span> start if they never receive the active treatment?</p>
<ul>
<li><strong>Synchronicity Principle</strong>: <span class="math inline">\(T_0\)</span> is the moment the patient meets all clinical eligibility criteria (e.g., METex14 diagnosis + ECOG status).</li>
<li><strong>Timeline Alignment</strong>:
<ul>
<li><em>Incorrect</em>: Treated group starts at “first drug administration”, while controls start at “diagnosis”. This gives the treated group an implicit survival benefit.</li>
<li><em>Correct TTE Approach</em>: Both groups start follow-up at the exact date they meet all eligibility criteria (the clinical decision point, or clinical equipoise).</li>
</ul></li>
</ul>
</section>
<section id="handling-the-grace-period" class="level4" data-number="3.3.3">
<h4 data-number="3.3.3" class="anchored" data-anchor-id="handling-the-grace-period"><span class="header-section-number">3.3.3</span> Handling the Grace Period</h4>
<p>In RWD, a patient has a “window” of time (grace period) to initiate treatment (e.g., 30 days after diagnosis).</p>
<ul>
<li>If a patient initiates treatment on Day 20, they contribute 20 days of “unexposed” person-time to the control group.</li>
<li>Using cloning, we create two clones at diagnosis. The “Control Clone” is followed until Day 20, where it is censored because the patient initiated treatment. The “Treated Clone” starts contributing treated time from Day 20 onwards.</li>
</ul>
</section>
</section>
<section id="step-2-cloning-censoring-mechanics" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="step-2-cloning-censoring-mechanics"><span class="header-section-number">3.4</span> Step 2: Cloning &amp; Censoring Mechanics</h3>
<p>To maintain ITT principles:</p>
<ul>
<li><strong>Anti-Future-Knowledge</strong>: We cannot look ahead to see what the patient did. We clone them at <span class="math inline">\(T_0\)</span> into both paths.</li>
<li><strong>Artificial Censoring</strong>: If the patient’s actual path deviates from a clone’s assigned arm, that clone is censored.</li>
<li><strong>IPCW Weighting</strong>: Because censoring might be non-random, we estimate the probability of being censored at time <span class="math inline">\(t\)</span> based on baseline covariates and apply Inverse Probability of Censoring Weights to the remaining patients, dynamically restoring the balance.</li>
</ul>
<hr>
</section>
</section>
<section id="immortal-time-bias-itb-theory-landmark-analysis" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="immortal-time-bias-itb-theory-landmark-analysis"><span class="header-section-number">4</span> Immortal Time Bias (ITB): Theory &amp; Landmark Analysis</h2>
<section id="the-meditation-longevity-paradox" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="the-meditation-longevity-paradox"><span class="header-section-number">4.1</span> The Meditation &amp; Longevity Paradox</h3>
<p>Consider a study evaluating whether a 12-week intensive meditation course increases overall survival (OS):</p>
<ul>
<li><strong>Cohort</strong>: 1,000 participants followed for 5 years.</li>
<li><strong>Exposure Group (<span class="math inline">\(Z=1\)</span>)</strong>: Completed the full 12-week program.</li>
<li><strong>Control Group (<span class="math inline">\(Z=0\)</span>)</strong>: Did not complete the program (includes those who died or dropped out before week 12).</li>
<li><strong>The Result</strong>: Meditators show a Hazard Ratio (<span class="math inline">\(HR\)</span>) of 0.30 (70% risk reduction).</li>
<li><strong>The Error</strong>: Since a patient had to survive 12 weeks to complete the program, the meditation group is guaranteed 0% mortality during the first 12 weeks. Sicker patients who died in weeks 1–11 were automatically allocated to the control group.</li>
</ul>
</section>
<section id="violating-the-non-anticipatory-constraint" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="violating-the-non-anticipatory-constraint"><span class="header-section-number">4.2</span> Violating the “Non-anticipatory Constraint”</h3>
<p>Mathematically, let <span class="math inline">\(\mathcal{F}_t\)</span> be the filtration (information history) up to time <span class="math inline">\(t\)</span>. A treatment assignment indicator <span class="math inline">\(Z_t\)</span> must be adapted to the filtration: <span class="math display">\[Z_t \in \mathcal{F}_t\]</span></p>
<p>If we define a static indicator <span class="math inline">\(Z\)</span> based on whether the event occurred in the future: <span class="math display">\[Z = f(Y_{t \in [0, 12]})\]</span> we condition on a post-baseline outcome <span class="math inline">\(Y\)</span>. This violates the non-anticipatory constraint, leading to “time travel” in the statistical model.</p>
</section>
<section id="landmark-analysis" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="landmark-analysis"><span class="header-section-number">4.3</span> Landmark Analysis</h3>
<p>Landmark Analysis is a classical approach to resolve this:</p>
<ol type="1">
<li><strong>Select Landmark Time (<span class="math inline">\(T_L\)</span>)</strong>: E.g., Week 12.</li>
<li><strong>Exclude Early Events</strong>: Exclude all patients who died or were censored before <span class="math inline">\(T_L\)</span>.</li>
<li><strong>Re-classify</strong>: Classify survivors at <span class="math inline">\(T_L\)</span> based on their exposure status at <span class="math inline">\(T_L\)</span>.</li>
<li><strong>Follow-up</strong>: Set <span class="math inline">\(T_L\)</span> as the new baseline (<span class="math inline">\(T_{start} = T_L\)</span>) and follow patients from that point.</li>
</ol>
<section id="hta-audit-of-landmark-analysis" class="level4" data-number="4.3.1">
<h4 data-number="4.3.1" class="anchored" data-anchor-id="hta-audit-of-landmark-analysis"><span class="header-section-number">4.3.1</span> HTA Audit of Landmark Analysis</h4>
<ul>
<li><strong>Pros</strong>: Simple, highly intuitive, and removes the immortal period.</li>
<li><strong>Cons</strong>:
<ul>
<li><strong>Information Loss</strong>: Discards all events and person-time before <span class="math inline">\(T_L\)</span>. If the drug has high early toxicity, this signal is completely lost.</li>
<li><strong>Selection Bias</strong>: The populations at <span class="math inline">\(T_L\)</span> may no longer be balanced, as sicker patients in the control group may have died, while sicker patients in the treated group were protected by the “immortal” definition.</li>
</ul></li>
</ul>
<hr>
</section>
</section>
</section>
<section id="time-dependent-cox-model-hta-practice" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="time-dependent-cox-model-hta-practice"><span class="header-section-number">5</span> Time-Dependent Cox Model &amp; HTA Practice</h2>
<p>The time-dependent Cox model is the industry standard for auditing and correcting immortal time bias in HTA submissions.</p>
<section id="counting-process-data-structure" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="counting-process-data-structure"><span class="header-section-number">5.1</span> Counting Process Data Structure</h3>
<p>Rather than one row per patient, the counting process format splits each patient’s follow-up into multiple intervals <code>(tstart, tstop]</code> where treatment status remains constant.</p>
<section id="restructuring-example-patient-101" class="level4" data-number="5.1.1">
<h4 data-number="5.1.1" class="anchored" data-anchor-id="restructuring-example-patient-101"><span class="header-section-number">5.1.1</span> Restructuring Example (Patient #101)</h4>
<p>Patient #101 has a treatment initiation lag of 60 days and dies on Day 500. We split this patient’s record into two lines:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Patient ID</th>
<th style="text-align: left;">Start (Day)</th>
<th style="text-align: left;">Stop (Day)</th>
<th style="text-align: left;">Status (Event)</th>
<th style="text-align: left;">Treatment (<span class="math inline">\(Z\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">#101</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">0 (Alive)</td>
<td style="text-align: left;">0 (Unexposed)</td>
</tr>
<tr class="even">
<td style="text-align: left;">#101</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">500</td>
<td style="text-align: left;">1 (Death)</td>
<td style="text-align: left;">1 (Exposed)</td>
</tr>
</tbody>
</table>
<p>At Day 60, the patient is right-censored in the control group and enters the treated group.</p>
</section>
</section>
<section id="landmark-vs.-time-dependent-cox" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="landmark-vs.-time-dependent-cox"><span class="header-section-number">5.2</span> Landmark vs.&nbsp;Time-Dependent Cox</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimension</th>
<th style="text-align: left;">Time-dependent Cox</th>
<th style="text-align: left;">Landmark Analysis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Data Retention</strong></td>
<td style="text-align: left;">Retains all patients and events from Day 0.</td>
<td style="text-align: left;">Discards patients/events prior to Landmark <span class="math inline">\(T_L\)</span>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Causal Question</strong></td>
<td style="text-align: left;">Causal effect starting from Day 0.</td>
<td style="text-align: left;">Conditional effect given survival to <span class="math inline">\(T_L\)</span>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Early Toxicity</strong></td>
<td style="text-align: left;">Captures early adverse event signals.</td>
<td style="text-align: left;">Masked if events occur before <span class="math inline">\(T_L\)</span>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>HTA Audit Preference</strong></td>
<td style="text-align: left;">Preferred for primary analysis.</td>
<td style="text-align: left;">Used primarily as a sensitivity analysis.</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="r-simulation-validation-of-estimators" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="r-simulation-validation-of-estimators"><span class="header-section-number">6</span> R Simulation: Validation of Estimators</h2>
<p>We simulate a cohort of 500 patients where treatment initiation is delayed due to an administrative “Approval Lag.”</p>
<section id="simulating-the-cohort-and-biased-analysis" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="simulating-the-cohort-and-biased-analysis"><span class="header-section-number">6.1</span> Simulating the Cohort and Biased Analysis</h3>
<p>We simulate a true treatment Hazard Ratio of <strong>0.70</strong> (30% risk reduction). Age and ECOG status act as baseline confounders.</p>
<div class="cell">
<details class="code-fold">
<summary>R Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(EValue)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Helper function to render Cox model summaries as kable tables</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>show_cox <span class="ot">&lt;-</span> <span class="cf">function</span>(fit, caption) {</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  sum_fit <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  coefs <span class="ot">&lt;-</span> sum_fit<span class="sc">$</span>coefficients</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  cis <span class="ot">&lt;-</span> sum_fit<span class="sc">$</span>conf.int</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  tbl <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">Covariate =</span> <span class="fu">rownames</span>(coefs),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Hazard Ratio</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(coefs[, <span class="dv">2</span>], <span class="dv">4</span>),</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Log HR (coef)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(coefs[, <span class="dv">1</span>], <span class="dv">4</span>),</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Std Error</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(coefs[, <span class="dv">3</span>], <span class="dv">4</span>),</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">z-value</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(coefs[, <span class="dv">4</span>], <span class="dv">3</span>),</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">p-value</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">format.pval</span>(coefs[, <span class="dv">5</span>], <span class="at">digits =</span> <span class="dv">4</span>),</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">95% LCL</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(cis[, <span class="dv">3</span>], <span class="dv">4</span>),</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">95% UCL</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(cis[, <span class="dv">4</span>], <span class="dv">4</span>),</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">check.names =</span> <span class="cn">FALSE</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(tbl, <span class="at">caption =</span> caption, <span class="at">align =</span> <span class="st">"lrrrrrrr"</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Simulate Baseline Confounders</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">60</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>ecog <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fl">0.4</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Simulate Treatment Selection (Confounding by Indication)</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Sicker (ECOG=1) and older patients are more likely to receive treatment</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>ps_prob <span class="ot">&lt;-</span> <span class="fu">plogis</span>(<span class="sc">-</span><span class="fl">1.5</span> <span class="sc">+</span> <span class="fl">0.02</span> <span class="sc">*</span> age <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> ecog)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>z_treatment <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, ps_prob)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="co"># For those treated, add a random initiation delay between 30 and 120 days</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>t_init <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(z_treatment <span class="sc">==</span> <span class="dv">1</span>, <span class="fu">runif</span>(n, <span class="dv">30</span>, <span class="dv">120</span>), <span class="cn">Inf</span>)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Simulate Survival Times (True treatment HR = 0.70)</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>true_hr <span class="ot">&lt;-</span> <span class="fl">0.70</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>lambda_base <span class="ot">&lt;-</span> <span class="fl">0.001</span> <span class="sc">*</span> <span class="fu">exp</span>(<span class="fl">0.02</span> <span class="sc">*</span> age <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> ecog)</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">runif</span>(n)</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>log_u <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">log</span>(u)</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>t_event <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>  l0 <span class="ot">&lt;-</span> lambda_base[i]</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>  l1 <span class="ot">&lt;-</span> l0 <span class="sc">*</span> true_hr</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>  t_tr <span class="ot">&lt;-</span> t_init[i]</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (log_u[i] <span class="sc">&lt;=</span> l0 <span class="sc">*</span> t_tr) {</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>    t_event[i] <span class="ot">&lt;-</span> log_u[i] <span class="sc">/</span> l0</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>    t_event[i] <span class="ot">&lt;-</span> t_tr <span class="sc">+</span> (log_u[i] <span class="sc">-</span> l0 <span class="sc">*</span> t_tr) <span class="sc">/</span> l1</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="co"># Censoring between 150 and 730 days</span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>t_censor <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="dv">150</span>, <span class="dv">730</span>)</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>time <span class="ot">&lt;-</span> <span class="fu">pmin</span>(t_event, t_censor)</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>event <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(t_event <span class="sc">&lt;=</span> t_censor)</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span>n, age, ecog, z_treatment, t_init, time, event)</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine treatment status based on actual follow-up (Biased approach)</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>ever_treated <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>t_init <span class="sc">&lt;</span> df<span class="sc">$</span>time, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Biased Analysis: Static Cox Model ---</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>fit_biased <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, event) <span class="sc">~</span> ever_treated <span class="sc">+</span> age <span class="sc">+</span> ecog, <span class="at">data =</span> df)</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="fu">show_cox</span>(fit_biased, <span class="st">"Biased Static Cox Proportional Hazards Model Results (Immortal Time Unadjusted)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Biased Static Cox Proportional Hazards Model Results (Immortal Time Unadjusted)</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Covariate</th>
<th style="text-align: right;">Hazard Ratio</th>
<th style="text-align: right;">Log HR (coef)</th>
<th style="text-align: right;">Std Error</th>
<th style="text-align: right;">z-value</th>
<th style="text-align: right;">p-value</th>
<th style="text-align: right;">95% LCL</th>
<th style="text-align: right;">95% UCL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ever_treated</td>
<td style="text-align: left;">ever_treated</td>
<td style="text-align: right;">0.4062</td>
<td style="text-align: right;">-0.9008</td>
<td style="text-align: right;">0.1138</td>
<td style="text-align: right;">-7.915</td>
<td style="text-align: right;">2.468e-15</td>
<td style="text-align: right;">0.3250</td>
<td style="text-align: right;">0.5077</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: left;">age</td>
<td style="text-align: right;">1.0219</td>
<td style="text-align: right;">0.0216</td>
<td style="text-align: right;">0.0056</td>
<td style="text-align: right;">3.853</td>
<td style="text-align: right;">0.0001168</td>
<td style="text-align: right;">1.0107</td>
<td style="text-align: right;">1.0332</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ecog</td>
<td style="text-align: left;">ecog</td>
<td style="text-align: right;">1.9562</td>
<td style="text-align: right;">0.6710</td>
<td style="text-align: right;">0.1071</td>
<td style="text-align: right;">6.264</td>
<td style="text-align: right;">3.757e-10</td>
<td style="text-align: right;">1.5857</td>
<td style="text-align: right;">2.4132</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The biased static Cox model overestimates drug efficacy due to the unadjusted immortal time.</p>
</section>
<section id="method-1-landmark-analysis-day-90" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="method-1-landmark-analysis-day-90"><span class="header-section-number">6.2</span> Method 1: Landmark Analysis (Day 90)</h3>
<p>We apply Landmark Analysis at Day 90:</p>
<div class="cell">
<details class="code-fold">
<summary>R Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>t_landmark <span class="ot">&lt;-</span> <span class="dv">90</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Exclude patients who died or were censored before Day 90</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>df_landmark <span class="ot">&lt;-</span> df[df<span class="sc">$</span>time <span class="sc">&gt;</span> t_landmark, ]</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Classify status at Landmark</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>df_landmark<span class="sc">$</span>treated_at_landmark <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df_landmark<span class="sc">$</span>t_init <span class="sc">&lt;=</span> t_landmark, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Shift time</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>df_landmark<span class="sc">$</span>time_shifted <span class="ot">&lt;-</span> df_landmark<span class="sc">$</span>time <span class="sc">-</span> t_landmark</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>fit_landmark <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time_shifted, event) <span class="sc">~</span> treated_at_landmark <span class="sc">+</span> age <span class="sc">+</span> ecog, <span class="at">data =</span> df_landmark)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="fu">show_cox</span>(fit_landmark, <span class="st">"Landmark Analysis (Day 90) Cox Proportional Hazards Model Results"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Landmark Analysis (Day 90) Cox Proportional Hazards Model Results</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Covariate</th>
<th style="text-align: right;">Hazard Ratio</th>
<th style="text-align: right;">Log HR (coef)</th>
<th style="text-align: right;">Std Error</th>
<th style="text-align: right;">z-value</th>
<th style="text-align: right;">p-value</th>
<th style="text-align: right;">95% LCL</th>
<th style="text-align: right;">95% UCL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">treated_at_landmark</td>
<td style="text-align: left;">treated_at_landmark</td>
<td style="text-align: right;">0.7879</td>
<td style="text-align: right;">-0.2384</td>
<td style="text-align: right;">0.1482</td>
<td style="text-align: right;">-1.608</td>
<td style="text-align: right;">0.107855</td>
<td style="text-align: right;">0.5893</td>
<td style="text-align: right;">1.0536</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: left;">age</td>
<td style="text-align: right;">1.0212</td>
<td style="text-align: right;">0.0210</td>
<td style="text-align: right;">0.0074</td>
<td style="text-align: right;">2.840</td>
<td style="text-align: right;">0.004517</td>
<td style="text-align: right;">1.0065</td>
<td style="text-align: right;">1.0361</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ecog</td>
<td style="text-align: left;">ecog</td>
<td style="text-align: right;">2.1712</td>
<td style="text-align: right;">0.7753</td>
<td style="text-align: right;">0.1415</td>
<td style="text-align: right;">5.477</td>
<td style="text-align: right;">4.32e-08</td>
<td style="text-align: right;">1.6452</td>
<td style="text-align: right;">2.8653</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="method-2-time-varying-cox-model" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="method-2-time-varying-cox-model"><span class="header-section-number">6.3</span> Method 2: Time-Varying Cox Model</h3>
<p>We restructure the dataset into a counting process format using <code>tmerge()</code> and fit the time-varying Cox model:</p>
<div class="cell">
<details class="code-fold">
<summary>R Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Initialize dataset with the primary event time</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df_tv <span class="ot">&lt;-</span> <span class="fu">tmerge</span>(df, df, <span class="at">id =</span> id, <span class="at">event =</span> <span class="fu">event</span>(time, event))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Merge the time-dependent treatment initiation event</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>df_tv <span class="ot">&lt;-</span> <span class="fu">tmerge</span>(df_tv, df, <span class="at">id =</span> id, <span class="at">treatment_status =</span> <span class="fu">tdc</span>(t_init))</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the split intervals for Patient ID 1 to 3 in table format</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(df_tv[df_tv<span class="sc">$</span>id <span class="sc">%in%</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="fu">c</span>(<span class="st">"id"</span>, <span class="st">"tstart"</span>, <span class="st">"tstop"</span>, <span class="st">"event"</span>, <span class="st">"treatment_status"</span>)]),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Restructured Counting Process Intervals (Patient ID 1-3)"</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">align =</span> <span class="st">"c"</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Restructured Counting Process Intervals (Patient ID 1-3)</caption>
<thead>
<tr class="header">
<th style="text-align: center;">id</th>
<th style="text-align: center;">tstart</th>
<th style="text-align: center;">tstop</th>
<th style="text-align: center;">event</th>
<th style="text-align: center;">treatment_status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.00000</td>
<td style="text-align: center;">119.09690</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">119.09690</td>
<td style="text-align: center;">308.79962</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.00000</td>
<td style="text-align: center;">23.38370</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.00000</td>
<td style="text-align: center;">92.99129</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">92.99129</td>
<td style="text-align: center;">215.66793</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>As shown, if a patient receives treatment at a delayed time, their follow-up is split:</p>
<ul>
<li><strong>Interval 1 <code>[0, t_init]</code></strong>: <code>treatment_status = 0</code> (contributes person-time to the control risk set).</li>
<li><strong>Interval 2 <code>[t_init, time]</code></strong>: <code>treatment_status = 1</code> (contributes person-time to the treated risk set after the first infusion).</li>
</ul>
<p>We fit the Cox model on the split intervals:</p>
<div class="cell">
<details class="code-fold">
<summary>R Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the time-varying Cox model</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>fit_tv <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(tstart, tstop, event) <span class="sc">~</span> treatment_status <span class="sc">+</span> age <span class="sc">+</span> ecog, <span class="at">data =</span> df_tv)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">show_cox</span>(fit_tv, <span class="st">"Time-Varying Cox Proportional Hazards Model Results (Immortal Time Corrected)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Time-Varying Cox Proportional Hazards Model Results (Immortal Time Corrected)</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Covariate</th>
<th style="text-align: right;">Hazard Ratio</th>
<th style="text-align: right;">Log HR (coef)</th>
<th style="text-align: right;">Std Error</th>
<th style="text-align: right;">z-value</th>
<th style="text-align: right;">p-value</th>
<th style="text-align: right;">95% LCL</th>
<th style="text-align: right;">95% UCL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">treatment_status</td>
<td style="text-align: left;">treatment_status</td>
<td style="text-align: right;">0.6930</td>
<td style="text-align: right;">-0.3668</td>
<td style="text-align: right;">0.1257</td>
<td style="text-align: right;">-2.918</td>
<td style="text-align: right;">0.0035197</td>
<td style="text-align: right;">0.5417</td>
<td style="text-align: right;">0.8865</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: left;">age</td>
<td style="text-align: right;">1.0188</td>
<td style="text-align: right;">0.0187</td>
<td style="text-align: right;">0.0056</td>
<td style="text-align: right;">3.350</td>
<td style="text-align: right;">0.0008068</td>
<td style="text-align: right;">1.0078</td>
<td style="text-align: right;">1.0300</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ecog</td>
<td style="text-align: left;">ecog</td>
<td style="text-align: right;">1.8597</td>
<td style="text-align: right;">0.6204</td>
<td style="text-align: right;">0.1070</td>
<td style="text-align: right;">5.799</td>
<td style="text-align: right;">6.658e-09</td>
<td style="text-align: right;">1.5079</td>
<td style="text-align: right;">2.2935</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The time-varying Cox model successfully recovers the true treatment effect (<span class="math inline">\(HR = 0.70\)</span>) without discarding data.</p>
<hr>
</section>
</section>
<section id="causal-evidence-reconciliation" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="causal-evidence-reconciliation"><span class="header-section-number">7</span> Causal Evidence Reconciliation</h2>
<p>The table below summarizes the estimates across all three models compared to the true parameter.</p>
<div class="cell">
<details class="code-fold">
<summary>R Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract statistics</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>hr_biased  <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(fit_biased)[<span class="st">"ever_treated"</span>])</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>se_biased  <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit_biased)<span class="sc">$</span>coefficients[<span class="st">"ever_treated"</span>, <span class="st">"se(coef)"</span>]</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>hr_land    <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(fit_landmark)[<span class="st">"treated_at_landmark"</span>])</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>se_land    <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit_landmark)<span class="sc">$</span>coefficients[<span class="st">"treated_at_landmark"</span>, <span class="st">"se(coef)"</span>]</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>hr_tv      <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(fit_tv)[<span class="st">"treatment_status"</span>])</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>se_tv      <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit_tv)<span class="sc">$</span>coefficients[<span class="st">"treatment_status"</span>, <span class="st">"se(coef)"</span>]</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine into reconciliation matrix</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>reconciliation_tbl <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">Estimator =</span> <span class="fu">c</span>(<span class="st">"Ground Truth (True Parameter)"</span>, <span class="st">"Biased Model (Static Baseline)"</span>, <span class="st">"Landmark Analysis (Day 90)"</span>, <span class="st">"Time-Varying Cox Model"</span>),</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Hazard Ratio (HR)"</span> <span class="ot">=</span> <span class="fu">c</span>(true_hr, hr_biased, hr_land, hr_tv),</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Standard Error"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="cn">NA</span>, se_biased, se_land, se_tv),</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"95% LCL"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">exp</span>(<span class="fu">confint</span>(fit_biased)[<span class="st">"ever_treated"</span>, <span class="dv">1</span>]), <span class="fu">exp</span>(<span class="fu">confint</span>(fit_landmark)[<span class="st">"treated_at_landmark"</span>, <span class="dv">1</span>]), <span class="fu">exp</span>(<span class="fu">confint</span>(fit_tv)[<span class="st">"treatment_status"</span>, <span class="dv">1</span>])),</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"95% UCL"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">exp</span>(<span class="fu">confint</span>(fit_biased)[<span class="st">"ever_treated"</span>, <span class="dv">2</span>]), <span class="fu">exp</span>(<span class="fu">confint</span>(fit_landmark)[<span class="st">"treated_at_landmark"</span>, <span class="dv">2</span>]), <span class="fu">exp</span>(<span class="fu">confint</span>(fit_tv)[<span class="st">"treatment_status"</span>, <span class="dv">2</span>])),</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Bias vs. Truth (Log HR)"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">0.0000</span>, <span class="fu">coef</span>(fit_biased)[<span class="st">"ever_treated"</span>] <span class="sc">-</span> <span class="fu">log</span>(true_hr), <span class="fu">coef</span>(fit_landmark)[<span class="st">"treated_at_landmark"</span>] <span class="sc">-</span> <span class="fu">log</span>(true_hr), <span class="fu">coef</span>(fit_tv)[<span class="st">"treatment_status"</span>] <span class="sc">-</span> <span class="fu">log</span>(true_hr)),</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">check.names =</span> <span class="cn">FALSE</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Format values for display</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>reconciliation_tbl[, <span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(reconciliation_tbl[, <span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>], <span class="dv">4</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>reconciliation_tbl[<span class="fu">is.na</span>(reconciliation_tbl)] <span class="ot">&lt;-</span> <span class="st">"N/A"</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(reconciliation_tbl, <span class="at">caption =</span> <span class="st">"Survival Parameter Reconciliation Across Estimators"</span>, <span class="at">align =</span> <span class="st">"lrrrrr"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Survival Parameter Reconciliation Across Estimators</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 25%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Estimator</th>
<th style="text-align: right;">Hazard Ratio (HR)</th>
<th style="text-align: right;">Standard Error</th>
<th style="text-align: right;">95% LCL</th>
<th style="text-align: right;">95% UCL</th>
<th style="text-align: right;">Bias vs.&nbsp;Truth (Log HR)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Ground Truth (True Parameter)</td>
<td style="text-align: right;">0.7000</td>
<td style="text-align: right;">N/A</td>
<td style="text-align: right;">N/A</td>
<td style="text-align: right;">N/A</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">ever_treated</td>
<td style="text-align: left;">Biased Model (Static Baseline)</td>
<td style="text-align: right;">0.4062</td>
<td style="text-align: right;">0.1138</td>
<td style="text-align: right;">0.325</td>
<td style="text-align: right;">0.5077</td>
<td style="text-align: right;">-0.5442</td>
</tr>
<tr class="odd">
<td style="text-align: left;">treated_at_landmark</td>
<td style="text-align: left;">Landmark Analysis (Day 90)</td>
<td style="text-align: right;">0.7879</td>
<td style="text-align: right;">0.1482</td>
<td style="text-align: right;">0.5893</td>
<td style="text-align: right;">1.0536</td>
<td style="text-align: right;">0.1183</td>
</tr>
<tr class="even">
<td style="text-align: left;">treatment_status</td>
<td style="text-align: left;">Time-Varying Cox Model</td>
<td style="text-align: right;">0.6930</td>
<td style="text-align: right;">0.1257</td>
<td style="text-align: right;">0.5417</td>
<td style="text-align: right;">0.8865</td>
<td style="text-align: right;">-0.0101</td>
</tr>
</tbody>
</table>
</div>
</div>
<hr>
</section>
<section id="quantitative-bias-analysis-e-value-sensitivity-analysis" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="quantitative-bias-analysis-e-value-sensitivity-analysis"><span class="header-section-number">8</span> Quantitative Bias Analysis: E-Value Sensitivity Analysis</h2>
<p>When submitting RWE to HTA bodies, we must audit the robustness of our findings against unmeasured confounding. We compute the E-value for the time-varying Hazard Ratio (<span class="math inline">\(HR = 0.693\)</span>).</p>
<section id="e-value-math-formula-setup" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="e-value-math-formula-setup"><span class="header-section-number">8.1</span> E-Value Math &amp; Formula Setup</h3>
<p>The E-value is defined as the minimum strength of association on the risk ratio scale that an unmeasured confounder (<span class="math inline">\(U\)</span>) must have with both: 1. The treatment assignment (<span class="math inline">\(Z\)</span>) 2. The clinical outcome (<span class="math inline">\(Y\)</span>)</p>
<p>to fully explain away the observed treatment-outcome association.</p>
<p>The formula depends on the cumulative incidence of the outcome:</p>
<ol type="1">
<li><p><strong>Rare Outcome Assumption</strong> (cumulative incidence &lt; 15%):</p>
<p>The Hazard Ratio approximates the Relative Risk (<span class="math inline">\(RR \approx HR\)</span>). For protective effects (<span class="math inline">\(HR &lt; 1.0\)</span>), we first invert the HR (<span class="math inline">\(HR^* = 1 / HR\)</span>) to get a value <span class="math inline">\(&gt; 1.0\)</span>: <span class="math display">\[\text{E-value} = HR^* + \sqrt{HR^* \cdot (HR^* - 1)}\]</span></p></li>
<li><p><strong>Common Outcome Correction</strong> (cumulative incidence &gt; 15%):</p>
<p>The rare outcome assumption is violated, and we must apply the square root approximation: <span class="math display">\[RR \approx \sqrt{HR}\]</span> The corresponding E-value is calculated as: <span class="math display">\[\text{E-value} = \sqrt{HR^*} + \sqrt{\sqrt{HR^*} \cdot (\sqrt{HR^*} - 1)}\]</span></p></li>
</ol>
<p>In our cohort, <span class="math inline">\(379\)</span> out of <span class="math inline">\(500\)</span> patients (<span class="math inline">\(75.8\%\)</span>) experienced the event, meaning the outcome is common. We must apply the common outcome correction.</p>
<div class="cell">
<details class="code-fold">
<summary>R Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Extract HR and confidence limits from the time-varying Cox model</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>hr_est_val <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(fit_tv)[<span class="st">"treatment_status"</span>])</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>hr_lcl_val <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">confint</span>(fit_tv)[<span class="st">"treatment_status"</span>, <span class="dv">1</span>])</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>hr_ucl_val <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">confint</span>(fit_tv)[<span class="st">"treatment_status"</span>, <span class="dv">2</span>])</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Compute E-value (common outcome correction: rare = FALSE)</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>ev_survival <span class="ot">&lt;-</span> <span class="fu">evalues.HR</span>(<span class="at">est =</span> hr_est_val, <span class="at">lo =</span> hr_lcl_val, <span class="at">hi =</span> hr_ucl_val, <span class="at">rare =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>ev_survival_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(ev_survival)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Format E-value table</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>ev_survival_tbl <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Metric / Parameter"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Hazard Ratio (HR)"</span>, <span class="st">"E-value (Treatment Effect Bound)"</span>),</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Point Estimate"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, ev_survival_df[<span class="st">"HR"</span>, <span class="st">"point"</span>]), <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, ev_survival_df[<span class="st">"E-values"</span>, <span class="st">"point"</span>])),</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"95% CI Lower Bound"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, ev_survival_df[<span class="st">"HR"</span>, <span class="st">"lower"</span>]), <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, ev_survival_df[<span class="st">"E-values"</span>, <span class="st">"lower"</span>])),</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"95% CI Upper Bound"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, ev_survival_df[<span class="st">"HR"</span>, <span class="st">"upper"</span>]), <span class="st">"N/A"</span>),</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">check.names =</span> <span class="cn">FALSE</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(ev_survival_tbl, <span class="at">caption =</span> <span class="st">"E-Value Analysis for Survival Sensitivity to Unmeasured Confounding"</span>, <span class="at">align =</span> <span class="st">"lrrr"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>E-Value Analysis for Survival Sensitivity to Unmeasured Confounding</caption>
<colgroup>
<col style="width: 38%">
<col style="width: 17%">
<col style="width: 22%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Metric / Parameter</th>
<th style="text-align: right;">Point Estimate</th>
<th style="text-align: right;">95% CI Lower Bound</th>
<th style="text-align: right;">95% CI Upper Bound</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hazard Ratio (HR)</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">E-value (Treatment Effect Bound)</td>
<td style="text-align: right;">1.899</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">N/A</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The point estimate E-value of <strong>1.899</strong> means that an unmeasured confounder would need to increase the probability of treatment assignment by <strong>1.899-fold</strong> and increase the hazard of death by <strong>1.899-fold</strong> to fully explain away the observed survival benefit.</p>
</section>
<section id="algebraic-derivation-of-the-e-value-vanderweele-ding-2016" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="algebraic-derivation-of-the-e-value-vanderweele-ding-2016"><span class="header-section-number">8.2</span> Algebraic Derivation of the E-Value (VanderWeele &amp; Ding 2016)</h3>
<p>To understand the mathematical strength of the E-value, we trace its algebraic derivation from the <strong>Bias Factor</strong> model.</p>
<p>Let <span class="math inline">\(U\)</span> be a binary unmeasured confounder. The observed relative risk <span class="math inline">\(RR_{obs}\)</span> is related to the true relative risk <span class="math inline">\(RR_{true}\)</span> by: <span class="math display">\[RR_{obs} = RR_{true} \times \text{Bias}\]</span></p>
<p>where the Bias Factor is defined as: <span class="math display">\[\text{Bias} = \frac{RR_{ZU} \times RR_{UY}}{RR_{ZU} + RR_{UY} - 1}\]</span></p>
<p>Here:</p>
<ul>
<li><span class="math inline">\(RR_{ZU}\)</span> is the risk ratio associating the treatment <span class="math inline">\(Z\)</span> with the unmeasured confounder <span class="math inline">\(U\)</span>.</li>
<li><span class="math inline">\(RR_{UY}\)</span> is the risk ratio associating the unmeasured confounder <span class="math inline">\(U\)</span> with the outcome <span class="math inline">\(Y\)</span>.</li>
</ul>
<p>To explain away an observed effect (i.e., to show that the true effect is null, <span class="math inline">\(RR_{true} = 1.0\)</span>), the Bias Factor must equal or exceed the observed relative risk: <span class="math display">\[\text{Bias} \ge RR_{obs}\]</span></p>
<p>To find the minimum strength of association required for both relationships, we define a single threshold <span class="math inline">\(E = RR_{ZU} = RR_{UY}\)</span>. Substituting <span class="math inline">\(E\)</span> into the Bias formula: <span class="math display">\[\frac{E^2}{2E - 1} \ge RR_{obs}\]</span></p>
<p>This can be rearranged into a quadratic inequality: <span class="math display">\[E^2 - 2RR_{obs} \cdot E + RR_{obs} \ge 0\]</span></p>
<p>Solving the quadratic equation <span class="math inline">\(E^2 - 2RR_{obs} \cdot E + RR_{obs} = 0\)</span> using the quadratic formula: <span class="math display">\[E = \frac{2RR_{obs} \pm \sqrt{4RR_{obs}^2 - 4RR_{obs}}}{2} = RR_{obs} + \sqrt{RR_{obs}(RR_{obs} - 1)}\]</span></p>
<p>This is the exact mathematical derivation of the E-value formula. It represents the absolute minimum joint relationship required for an unmeasured confounder to explain away the observed treatment effect.</p>
<hr>
</section>
</section>
<section id="hta-audit-interview-guide" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="hta-audit-interview-guide"><span class="header-section-number">9</span> HTA Audit &amp; Interview Guide</h2>
<section id="interview-audit-checklist" class="level3" data-number="9.1">
<h3 data-number="9.1" class="anchored" data-anchor-id="interview-audit-checklist"><span class="header-section-number">9.1</span> Interview Audit Checklist</h3>
<p>When auditing a manufacturer’s RWE survival submission (or preparing for an HTA interview), follow these three key checks:</p>
<ol type="1">
<li><p><strong>Zero-time Alignment Check</strong>:</p>
<ul>
<li><em>Question</em>: Identify the exact calendar date of <span class="math inline">\(T_0\)</span> for both cohorts. Is <span class="math inline">\(T_0\)</span> defined by the clinical event (diagnosis) or the administrative event (first prescription)?</li>
<li><em>Audit Rule</em>: Follow-up must start for both cohorts when they meet the eligibility criteria. If the treated group follow-up starts at drug initiation and controls start at diagnosis, the analysis is invalid.</li>
</ul></li>
<li><p><strong>Immortal Time Bias Screen</strong>:</p>
<ul>
<li><em>Question</em>: Check the initial segment of the Kaplan-Meier curve. Does the treated arm show a “zero-risk” flat line at the start of follow-up?</li>
<li><em>Audit Rule</em>: A flat line on the treatment curve indicates that patients who died early were excluded from the treated group, indicating Immortal Time Bias.</li>
</ul></li>
<li><p><strong>Statistical Correction Audit</strong>:</p>
<ul>
<li><em>Question</em>: If a treatment initiation lag exists, was it addressed using a time-varying covariate or a Landmark approach?</li>
<li><em>Audit Rule</em>: Standard Cox models using a static baseline treatment indicator are statistically invalid in the presence of treatment initiation delays.</li>
</ul></li>
</ol>
</section>
<section id="expert-hta-articulation" class="level3" data-number="9.2">
<h3 data-number="9.2" class="anchored" data-anchor-id="expert-hta-articulation"><span class="header-section-number">9.2</span> Expert HTA Articulation</h3>
<p>Use the following professional statements to articulate survival analysis defense strategies during HTA reviews or interviews:</p>
<ul>
<li><p><strong>Justifying Time-Varying Cox Models Over Static Models</strong>: &gt; “To prevent the introduction of lead-time and immortal time biases, we did not define treatment statically at baseline based on retrospective treatment status. Instead, we modeled treatment as a time-varying exposure using a counting process framework with start-stop intervals via the <code>tmerge</code> protocol. This ensures that the risk sets are updated dynamically at each event time, preventing the misattribution of waiting-period survival to the active drug’s efficacy.”</p></li>
<li><p><strong>Defending the Conditional Exchangeability Assumption</strong>: &gt; “Second, to maintain conditional exchangeability over time despite treatment delays, we utilized a cloning-and-censoring approach with IPCW, ensuring the counterfactual baseline characteristics remained balanced as the retrospective follow-up progressed.”</p></li>
<li><p><strong>Empirically Validating the Positivity Assumption</strong>: &gt; “Finally, we empirically validated the positivity assumption by confirming that patients across all covariate strata in our HES data had a non-zero probability of receiving standard of care, preventing structurally empty cells in our propensity score distributions.”</p></li>
<li><p><strong>Defending against Unmeasured Confounding via E-Values</strong>: &gt; “Although our real-world registry lacks smoking history, our E-value of 1.70 demonstrates that to nullify the observed survival benefit, an unmeasured confounder would need to increase both the likelihood of treatment and the hazard of death by at least 1.70-fold. This is larger than the hazard associated with major clinical indicators like age in our adjusted models, making it highly implausible that a missing confounder of this magnitude exists that is completely independent of the clinical variables adjusted for in our primary analysis.”</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>