<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Xiaoge Zhang, PhD">
<meta name="dcterms.date" content="2026-09-18">

<title>Pairwise Meta-Analysis: The Foundation of NMA – HEOR Technical Portfolio</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-6191c8c4c757b97205a8995aa6c30869.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../custom.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">HEOR Technical Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-flagship-audits" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Flagship Audits</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-flagship-audits">    
        <li>
    <a class="dropdown-item" href="../../05_TA975_CAR-T_Case/TA975_Mock_Case.html">
 <span class="dropdown-text">NICE TA975 (CAR-T) Case</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../03_Bayesian_NMA_Reconstruction/MLNMR_Flagship_Case.html">
 <span class="dropdown-text">ML-NMR: AML Population Alignment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../02_RWE_Causal_Inference_Pipeline/RWE_Mock_Case_DLBCL.html">
 <span class="dropdown-text">RWE ECA: R/R DLBCL</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../01_Oncology_PartSM_Audit/PartSM_Forensic_Audit_RRMM.html">
 <span class="dropdown-text">PSM: Survival Extrapolation in RRMM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../07_TA1092_Pembro_ endometrial cancer/TA1092_Pembro_Endometrial_EAG_Case.html">
 <span class="dropdown-text">NICE TA1092 (Pembro) Case</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../09_RRMM_NMA_Replication/01_Multinomial_NMA_Replication.html">
 <span class="dropdown-text">Multinomial NMA: Response in RRMM</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-nma-library" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">NMA Library</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-nma-library">    
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/10_Bayesian_Estimation.html">
 <span class="dropdown-text">Bayesian Estimation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/12_Pairwise_Meta_Analysis.html">
 <span class="dropdown-text">Pairwise Meta-Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/01_Standard_Bayesian_NMA_Guide.html">
 <span class="dropdown-text">Standard Bayesian NMA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/02_Network_Meta_Regression_NMR.html">
 <span class="dropdown-text">Network Meta-Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/03_Survival_NMA.html">
 <span class="dropdown-text">Survival NMA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/04_Component_NMA.html">
 <span class="dropdown-text">Component NMA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/05_IPD_NMA.html">
 <span class="dropdown-text">IPD NMA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/06_MAIC.html">
 <span class="dropdown-text">MAIC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/07_STC.html">
 <span class="dropdown-text">STC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/08_ML_NMR.html">
 <span class="dropdown-text">ML-NMR</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/09_Flexible_Survival.html">
 <span class="dropdown-text">Flexible Survival</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../04_NMA/05_NMA_Technical_Prep/11_HR_OR_Intuition.html">
 <span class="dropdown-text">HR vs OR Intuition</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-rwe-library" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">RWE Library</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-rwe-library">    
        <li>
    <a class="dropdown-item" href="../../02_RWE_Causal_Inference_Pipeline/01_RWE_Technical_Prep/01_Confounding_and_Frameworks.html">
 <span class="dropdown-text">NICE Framework &amp; Confounding</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../02_RWE_Causal_Inference_Pipeline/01_RWE_Technical_Prep/02_PSM_IPTW_AIPW.html">
 <span class="dropdown-text">PSM, IPTW &amp; AIPW</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../02_RWE_Causal_Inference_Pipeline/01_RWE_Technical_Prep/03_TMLE_and_Sensitivity.html">
 <span class="dropdown-text">TMLE &amp; Sensitivity Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../02_RWE_Causal_Inference_Pipeline/01_RWE_Technical_Prep/04_Time_to_Event_and_Immortal_Time.html">
 <span class="dropdown-text">Survival &amp; Immortal Time</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-replication--verification" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Replication &amp; Verification</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-replication--verification">    
        <li>
    <a class="dropdown-item" href="../../11_Hypertension_Markov_QC_Replication/01_Hypertension_Markov_Replication.html">
 <span class="dropdown-text">Markov CEA: Hypertension verification</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../06_Market_Access_Decision_Tools/01_Interactive_Budget_Impact_Model.html">
 <span class="dropdown-text">BIM rebuild: Venetoclax in AML</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../00_HTA_LLM_Wiki/README.html"> 
<span class="menu-text">Methodology Wiki</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Qsev/XGZ-HEOR-Portfolio" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#executive-summary-one-comparison-many-trials" id="toc-executive-summary-one-comparison-many-trials" class="nav-link active" data-scroll-target="#executive-summary-one-comparison-many-trials"><span class="header-section-number">1</span> Executive Summary: One Comparison, Many Trials</a></li>
  <li><a href="#theoretical-framework-from-a-22-table-to-a-pooled-estimate" id="toc-theoretical-framework-from-a-22-table-to-a-pooled-estimate" class="nav-link" data-scroll-target="#theoretical-framework-from-a-22-table-to-a-pooled-estimate"><span class="header-section-number">2</span> Theoretical Framework: From a 2×2 Table to a Pooled Estimate</a>
  <ul class="collapse">
  <li><a href="#the-effect-size-in-a-single-trial" id="toc-the-effect-size-in-a-single-trial" class="nav-link" data-scroll-target="#the-effect-size-in-a-single-trial"><span class="header-section-number">2.1</span> The Effect Size in a Single Trial</a></li>
  <li><a href="#fixed-effect-inverse-variance-weighting" id="toc-fixed-effect-inverse-variance-weighting" class="nav-link" data-scroll-target="#fixed-effect-inverse-variance-weighting"><span class="header-section-number">2.2</span> Fixed Effect: Inverse-Variance Weighting</a></li>
  <li><a href="#random-effects-when-trials-estimate-different-effects" id="toc-random-effects-when-trials-estimate-different-effects" class="nav-link" data-scroll-target="#random-effects-when-trials-estimate-different-effects"><span class="header-section-number">2.3</span> Random Effects: When Trials Estimate Different Effects</a></li>
  <li><a href="#measuring-heterogeneity-q-τ²-and-i²" id="toc-measuring-heterogeneity-q-τ²-and-i²" class="nav-link" data-scroll-target="#measuring-heterogeneity-q-τ²-and-i²"><span class="header-section-number">2.4</span> Measuring Heterogeneity: Q, τ² and I²</a></li>
  <li><a href="#sec-pi" id="toc-sec-pi" class="nav-link" data-scroll-target="#sec-pi"><span class="header-section-number">2.5</span> The Prediction Interval</a></li>
  <li><a href="#sec-bayes" id="toc-sec-bayes" class="nav-link" data-scroll-target="#sec-bayes"><span class="header-section-number">2.6</span> The Bayesian Version: The Same Model, Estimated Differently</a></li>
  </ul></li>
  <li><a href="#the-minimal-mock-case-five-trials-of-b-vs-a" id="toc-the-minimal-mock-case-five-trials-of-b-vs-a" class="nav-link" data-scroll-target="#the-minimal-mock-case-five-trials-of-b-vs-a"><span class="header-section-number">3</span> The Minimal Mock Case: Five Trials of B vs A</a></li>
  <li><a href="#implementation-from-scratch-metafor-and-stan" id="toc-implementation-from-scratch-metafor-and-stan" class="nav-link" data-scroll-target="#implementation-from-scratch-metafor-and-stan"><span class="header-section-number">4</span> Implementation: From Scratch, <code>metafor</code> and Stan</a>
  <ul class="collapse">
  <li><a href="#from-scratch-in-base-r" id="toc-from-scratch-in-base-r" class="nav-link" data-scroll-target="#from-scratch-in-base-r"><span class="header-section-number">4.1</span> From Scratch in Base R</a></li>
  <li><a href="#cross-check-with-metafor" id="toc-cross-check-with-metafor" class="nav-link" data-scroll-target="#cross-check-with-metafor"><span class="header-section-number">4.2</span> Cross-Check With <code>metafor</code></a></li>
  <li><a href="#bayesian-random-effects-in-stan" id="toc-bayesian-random-effects-in-stan" class="nav-link" data-scroll-target="#bayesian-random-effects-in-stan"><span class="header-section-number">4.3</span> Bayesian Random Effects in Stan</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">5</span> Results &amp; Interpretation</a></li>
  <li><a href="#audit" id="toc-audit" class="nav-link" data-scroll-target="#audit"><span class="header-section-number">6</span> HTA Audit Points &amp; Interview Q&amp;A</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">7</span> Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pairwise Meta-Analysis: The Foundation of NMA</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Xiaoge Zhang, PhD </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><em>Pooling direct evidence for one comparison, from the likelihood up</em></p>
<section id="executive-summary-one-comparison-many-trials" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="executive-summary-one-comparison-many-trials"><span class="header-section-number">1</span> Executive Summary: One Comparison, Many Trials</h2>
<p>A pairwise meta-analysis pools the results of several trials that all compare the <strong>same two treatments</strong>, say a new drug B against standard of care A. Each trial on its own is a noisy estimate of the treatment effect; pooled, they give one estimate with a narrower interval.</p>
<p>It is also the building block of every method in this library. A <a href="../../04_NMA/05_NMA_Technical_Prep/01_Standard_Bayesian_NMA_Guide.html">Standard Bayesian NMA</a> is several pairwise meta-analyses estimated together, tied by the consistency assumption so that evidence on A vs B and A vs C also informs B vs C. Everything an NMA adds sits on top of the two questions answered here:</p>
<ol type="1">
<li>How should trials of different sizes be <strong>weighted</strong>?</li>
<li>What if the trials do not all estimate the <strong>same</strong> effect?</li>
</ol>
</section>
<section id="theoretical-framework-from-a-22-table-to-a-pooled-estimate" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="theoretical-framework-from-a-22-table-to-a-pooled-estimate"><span class="header-section-number">2</span> Theoretical Framework: From a 2×2 Table to a Pooled Estimate</h2>
<section id="the-effect-size-in-a-single-trial" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="the-effect-size-in-a-single-trial"><span class="header-section-number">2.1</span> The Effect Size in a Single Trial</h3>
<p>For a binary outcome such as response, each trial reduces to a 2×2 table:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Responders</th>
<th style="text-align: center;">Non-responders</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Treatment B</td>
<td style="text-align: center;"><span class="math inline">\(a\)</span></td>
<td style="text-align: center;"><span class="math inline">\(b\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Treatment A</td>
<td style="text-align: center;"><span class="math inline">\(c\)</span></td>
<td style="text-align: center;"><span class="math inline">\(d\)</span></td>
</tr>
</tbody>
</table>
<p>Index the trials by <span class="math inline">\(i = 1, \dots, k\)</span> (in the mock case below, <span class="math inline">\(k = 5\)</span>). In trial <span class="math inline">\(i\)</span>, arm B enrols <span class="math inline">\(n_B\)</span> patients and arm A enrols <span class="math inline">\(n_A\)</span>. The responder counts are random variables, <span class="math inline">\(a \sim \text{Binomial}(n_B, p_B)\)</span> and <span class="math inline">\(c \sim \text{Binomial}(n_A, p_A)\)</span>, where <span class="math inline">\(p_B\)</span> and <span class="math inline">\(p_A\)</span> are the true response rates; the non-responders are <span class="math inline">\(b = n_B - a\)</span> and <span class="math inline">\(d = n_A - c\)</span>. The subscript <span class="math inline">\(i\)</span> is dropped from these quantities to keep the formulas readable.</p>
<p>The odds ratio and its logarithm are</p>
<p><span class="math display">\[OR_i = \frac{a / b}{c / d} = \frac{ad}{bc}, \qquad y_i = \ln OR_i\]</span></p>
<p>Meta-analysis works on the log scale because the OR is bounded below by 0 and asymmetric around 1, whereas <span class="math inline">\(\ln OR\)</span> is symmetric around 0 and close to Normal in reasonably sized trials.</p>
<p>The variance of <span class="math inline">\(y_i\)</span> is</p>
<p><span class="math display">\[v_i = \frac{1}{a} + \frac{1}{b} + \frac{1}{c} + \frac{1}{d}\]</span></p>
<p>Each arm contributes the reciprocals of its own two counts. Larger trials have larger counts, hence smaller <span class="math inline">\(v_i\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Where the variance formula comes from
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Step 1: the response rate in one arm.</strong> Take arm B, and write <span class="math inline">\(n = n_B\)</span> and <span class="math inline">\(p = p_B\)</span> for short. Since <span class="math inline">\(a \sim \text{Binomial}(n, p)\)</span>, the observed rate <span class="math inline">\(\hat p = a / n\)</span> has variance</p>
<p><span id="eq-var-p"><span class="math display">\[\text{Var}(\hat p) = \frac{p(1-p)}{n} \tag{1}\]</span></span></p>
<p><strong>Step 2: from the rate to the log odds.</strong> The log OR is built not from <span class="math inline">\(\hat p\)</span> but from its log odds, <span class="math inline">\(g(\hat p) = \ln\frac{\hat p}{1 - \hat p} = \ln\frac{a}{b}\)</span>. The <strong>delta method</strong> handles this change of scale. Near <span class="math inline">\(p\)</span>, the curve <span class="math inline">\(g\)</span> is close to its tangent line:</p>
<p><span id="eq-taylor"><span class="math display">\[g(\hat p) \approx g(p) + g'(p)\,(\hat p - p) \tag{2}\]</span></span></p>
<p>On the right of (<a href="#eq-taylor" class="quarto-xref">2</a>), <span class="math inline">\(g(p)\)</span> and <span class="math inline">\(g'(p)\)</span> are fixed numbers; only <span class="math inline">\(\hat p\)</span> is random. Multiplying a random quantity by a constant multiplies its variance by the constant squared, and adding a constant leaves it unchanged, so</p>
<p><span id="eq-delta"><span class="math display">\[\text{Var}\big(g(\hat p)\big) \approx g'(p)^2 \, \text{Var}(\hat p) \tag{3}\]</span></span></p>
<p><strong>Step 3: the slope of the log odds.</strong> Writing <span class="math inline">\(g(p) = \ln p - \ln(1 - p)\)</span> and differentiating:</p>
<p><span id="eq-slope"><span class="math display">\[g'(p) = \frac{1}{p} + \frac{1}{1-p} = \frac{1}{p(1-p)} \tag{4}\]</span></span></p>
<p><strong>Step 4: combine.</strong> Substituting (<a href="#eq-slope" class="quarto-xref">4</a>) and (<a href="#eq-var-p" class="quarto-xref">1</a>) into (<a href="#eq-delta" class="quarto-xref">3</a>):</p>
<p><span id="eq-var-logodds"><span class="math display">\[\text{Var}\left(\ln\frac{a}{b}\right) \approx \frac{1}{p^2(1-p)^2} \cdot \frac{p(1-p)}{n} = \frac{1}{np(1-p)} \tag{5}\]</span></span></p>
<p><strong>Step 5: back to the counts.</strong> Because <span class="math inline">\((1 - p) + p = 1\)</span>, the right-hand side of (<a href="#eq-var-logodds" class="quarto-xref">5</a>) splits into two fractions:</p>
<p><span id="eq-split"><span class="math display">\[\frac{1}{np(1-p)} = \frac{(1 - p) + p}{np(1-p)} = \frac{1}{np} + \frac{1}{n(1-p)} \tag{6}\]</span></span></p>
<p>In (<a href="#eq-split" class="quarto-xref">6</a>), <span class="math inline">\(np\)</span> and <span class="math inline">\(n(1-p)\)</span> are the expected numbers of responders and non-responders. Replacing them with the observed counts <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> gives the variance for arm B:</p>
<p><span id="eq-arm-B"><span class="math display">\[\text{Var}\left(\ln\frac{a}{b}\right) \approx \frac{1}{a} + \frac{1}{b} \tag{7}\]</span></span></p>
<p>Steps 1 to 5 apply unchanged to arm A, with its counts <span class="math inline">\(c\)</span> and <span class="math inline">\(d\)</span>:</p>
<p><span id="eq-arm-A"><span class="math display">\[\text{Var}\left(\ln\frac{c}{d}\right) \approx \frac{1}{c} + \frac{1}{d} \tag{8}\]</span></span></p>
<p><strong>Step 6: two arms.</strong> The log OR is a difference of the two log odds, <span class="math inline">\(y_i = \ln\frac{a}{b} - \ln\frac{c}{d}\)</span>. For independent quantities, <span class="math inline">\(\text{Var}(X - Y) = \text{Var}(X) + \text{Var}(Y)\)</span>, and the two arms enrol different patients, so adding (<a href="#eq-arm-B" class="quarto-xref">7</a>) and (<a href="#eq-arm-A" class="quarto-xref">8</a>):</p>
<p><span id="eq-vi"><span class="math display">\[v_i = \text{Var}(y_i) \approx \frac{1}{a} + \frac{1}{b} + \frac{1}{c} + \frac{1}{d} \tag{9}\]</span></span></p>
<p>which is the formula above.</p>
<p><strong>What it implies.</strong> The smallest cell dominates (<a href="#eq-vi" class="quarto-xref">9</a>). A trial of 1,000 patients per arm with only 5 responders on A still has <span class="math inline">\(v_i &gt; 1/5\)</span>, so a large trial with a rare event can be less precise than a small trial with a common one. When a cell is zero, <span class="math inline">\(v_i\)</span> is infinite, which is why a continuity correction, typically adding 0.5 to every cell, is applied. That correction is itself an assumption, and one that can move results when events are sparse.</p>
</div>
</div>
</div>
</section>
<section id="fixed-effect-inverse-variance-weighting" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="fixed-effect-inverse-variance-weighting"><span class="header-section-number">2.2</span> Fixed Effect: Inverse-Variance Weighting</h3>
<p>The <strong>fixed-effect</strong> model assumes every trial estimates one common effect <span class="math inline">\(\theta\)</span>, and differs from it only through sampling error:</p>
<p><span class="math display">\[y_i \sim N(\theta, v_i), \qquad i = 1, \dots, k\]</span></p>
<p>treating each <span class="math inline">\(v_i\)</span> as known. Strictly, the variance of <span class="math inline">\(y_i\)</span> depends on the true response rates <span class="math inline">\(p_B\)</span> and <span class="math inline">\(p_A\)</span>, which are unknown; <span class="math inline">\(v_i\)</span> replaces them with the observed rates, so it is an estimate. Treating it as a known constant is an approximation that works well with large counts, but with few events it makes both the weights and the pooled estimate unreliable, because <span class="math inline">\(y_i\)</span> and <span class="math inline">\(v_i\)</span> are computed from the same counts.</p>
<p>The log-likelihood is</p>
<p><span class="math display">\[\ell(\theta) = -\frac{1}{2} \sum_{i=1}^{k} \frac{(y_i - \theta)^2}{v_i} + \text{const}\]</span></p>
<p>Setting its derivative to zero gives the maximum likelihood estimate:</p>
<p><span class="math display">\[\sum_{i=1}^{k} \frac{y_i - \theta}{v_i} = 0 \quad \Rightarrow \quad \hat\theta_{FE} = \frac{\sum w_i y_i}{\sum w_i}, \qquad w_i = \frac{1}{v_i}\]</span></p>
<p>So the pooled estimate is a weighted average, and each trial’s weight is the inverse of its variance: precise trials count for more. The second derivative of <span class="math inline">\(\ell(\theta)\)</span> is <span class="math inline">\(-\sum w_i\)</span>, which gives</p>
<p><span class="math display">\[\text{Var}(\hat\theta_{FE}) = \frac{1}{\sum w_i}\]</span></p>
<p>This is the same curvature argument as in <a href="../../04_NMA/05_NMA_Technical_Prep/10_Bayesian_Estimation.html">The Core of Bayesian Estimation</a>: every trial adds its weight to the curvature of the log-likelihood, so the interval narrows as trials accumulate.</p>
</section>
<section id="random-effects-when-trials-estimate-different-effects" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="random-effects-when-trials-estimate-different-effects"><span class="header-section-number">2.3</span> Random Effects: When Trials Estimate Different Effects</h3>
<p>Trials differ in populations, doses and settings, so the true effect may differ between them. The <strong>random-effects</strong> model lets each trial have its own true effect <span class="math inline">\(\theta_i\)</span>, drawn from a common distribution:</p>
<p><span class="math display">\[y_i \sim N(\theta_i, v_i), \qquad \theta_i \sim N(\mu, \tau^2)\]</span></p>
<p>Here <span class="math inline">\(\mu\)</span> is the average effect across settings and <span class="math inline">\(\tau^2\)</span> the between-study variance. <span class="math inline">\(v_i\)</span> is the within-trial variance computed from <span class="math inline">\(a, b, c, d\)</span>: it describes how <span class="math inline">\(y_i\)</span> varies around trial <span class="math inline">\(i\)</span>’s own true effect <span class="math inline">\(\theta_i\)</span>. A single trial has only one <span class="math inline">\(\theta_i\)</span>, so it cannot show how true effects differ between trials; <span class="math inline">\(\tau^2\)</span> is estimated from how much the trials scatter beyond what their own <span class="math inline">\(v_i\)</span> can explain, as described in <a href="#sec-tau2" class="quarto-xref">Section&nbsp;2.4.2</a>.</p>
<p>Integrating out <span class="math inline">\(\theta_i\)</span> gives</p>
<p><span class="math display">\[y_i \sim N(\mu, \; v_i + \tau^2)\]</span></p>
<p>which is the fixed-effect model with every variance increased by <span class="math inline">\(\tau^2\)</span>. The same algebra therefore applies, with weights <span class="math inline">\(w_i^* = 1 / (v_i + \tau^2)\)</span>:</p>
<p><span class="math display">\[\hat\mu_{RE} = \frac{\sum w_i^* y_i}{\sum w_i^*}, \qquad \text{Var}(\hat\mu_{RE}) = \frac{1}{\sum w_i^*}\]</span></p>
<p>Adding the same <span class="math inline">\(\tau^2\)</span> to every trial matters most for the trials whose own <span class="math inline">\(v_i\)</span> is small. Large trials lose weight, small trials gain it, and the weights become more equal.</p>
</section>
<section id="measuring-heterogeneity-q-τ²-and-i²" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="measuring-heterogeneity-q-τ²-and-i²"><span class="header-section-number">2.4</span> Measuring Heterogeneity: Q, τ² and I²</h3>
<p>The random-effects model needs a value for <span class="math inline">\(\tau^2\)</span>, and the choice between the two models depends on how much the trials disagree. Three quantities describe that disagreement, and each answers a different question:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: left;">Question it answers</th>
<th style="text-align: left;">Scale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cochran’s <span class="math inline">\(Q\)</span></td>
<td style="text-align: left;">Do the trials disagree more than chance alone would explain?</td>
<td style="text-align: left;">A test statistic</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\tau^2\)</span></td>
<td style="text-align: left;">How far apart are the true effects?</td>
<td style="text-align: left;">Variance of the log OR</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(I^2\)</span></td>
<td style="text-align: left;">What share of the observed scatter is real rather than chance?</td>
<td style="text-align: left;">A proportion, 0 to 100%</td>
</tr>
</tbody>
</table>
<div id="nte-choose" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note&nbsp;1: Choosing between the two models
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In order of what should carry the most weight:</p>
<ol type="1">
<li><strong>Clinical judgement, first.</strong> Do the trials plausibly estimate one common effect: similar populations, doses, comparators, outcome definitions and follow-up? If they clearly do not, the fixed-effect assumption is hard to defend and the random-effects model is the honest default. A fixed-effect analysis then needs a positive argument, not just a favourable statistic.</li>
<li><strong>The size of the heterogeneity, not its significance.</strong> Read <span class="math inline">\(\tau\)</span> and the prediction interval (<a href="#sec-pi" class="quarto-xref">Section&nbsp;2.5</a>), and ask whether the spread they describe is large enough to change a decision. A statistically significant <span class="math inline">\(Q\)</span> with a prediction interval that stays well away from no effect is a different situation from a non-significant <span class="math inline">\(Q\)</span> with a prediction interval that crosses it.</li>
<li><strong>Model fit.</strong> Compare the two models on residual deviance and DIC: lower is better, and the DIC already penalises the extra parameter the random-effects model brings. NICE DSU TSD 2 recommends consulting both and sets no numerical threshold for how large a difference counts; the figure of 3 to 5 points often quoted is a rule of thumb from the wider DIC literature, not from TSD 2. When the two models are close, TSD 2’s advice elsewhere is to decide on the data-generating process and the interpretability of the results rather than on the statistic.</li>
<li><strong>How many trials there are.</strong> With few trials <span class="math inline">\(\tau\)</span> is badly estimated, and a DerSimonian–Laird random-effects interval can be too narrow (<a href="#sec-tau2" class="quarto-xref">Section&nbsp;2.4.2</a>). The remedies are the Hartung–Knapp–Sidik–Jonkman adjustment, REML, or a Bayesian model with an informative prior on <span class="math inline">\(\tau\)</span>. Switching to a fixed-effect model is not a remedy: it assumes the problem away.</li>
</ol>
<p>Three things not to do: choose by whether <span class="math inline">\(Q\)</span> is significant, choose by an <span class="math inline">\(I^2\)</span> threshold alone, or choose the model that happens to give the narrower interval. NICE DSU TSD 2 sets out the fit-based comparison; the <a href="../../04_NMA/05_NMA_Technical_Prep/01_Standard_Bayesian_NMA_Guide.html">Standard Bayesian NMA</a> guide lists the same judgement in a network setting.</p>
</div>
</div>
</div>
<section id="cochrans-q-more-scatter-than-chance" class="level4" data-number="2.4.1">
<h4 data-number="2.4.1" class="anchored" data-anchor-id="cochrans-q-more-scatter-than-chance"><span class="header-section-number">2.4.1</span> Cochran’s Q: More Scatter Than Chance?</h4>
<p><span class="math inline">\(Q\)</span> adds up how far each trial sits from the fixed-effect estimate:</p>
<p><span class="math display">\[Q = \sum_{i=1}^{k} w_i (y_i - \hat\theta_{FE})^2 = \sum_{i=1}^{k} \left( \frac{y_i - \hat\theta_{FE}}{\sqrt{v_i}} \right)^2\]</span></p>
<p>The second form shows what each term is: the distance of trial <span class="math inline">\(i\)</span> from the pooled estimate, measured in that trial’s own standard errors, then squared. A small trial far from the pooled estimate adds little, because its standard error is large; a large trial the same distance away adds a lot.</p>
<p>If every trial estimates one common effect, each standardised distance behaves like a draw from <span class="math inline">\(N(0, 1)\)</span>, and the sum of <span class="math inline">\(k\)</span> squared standard Normal draws follows a <span class="math inline">\(\chi^2\)</span> distribution. One degree of freedom is lost because <span class="math inline">\(\hat\theta_{FE}\)</span> is itself estimated from the same trials, so</p>
<p><span class="math display">\[Q \sim \chi^2_{k-1}, \qquad E(Q) = k - 1 \quad \text{under homogeneity}\]</span></p>
<p>That gives a test: a <span class="math inline">\(Q\)</span> well above <span class="math inline">\(k - 1\)</span> is unlikely if the trials share one effect. The test has two weaknesses that pull in opposite directions:</p>
<ul>
<li><strong>Few trials, low power.</strong> With five trials, <span class="math inline">\(Q\)</span> has 4 degrees of freedom and real heterogeneity often fails to reach significance. A threshold of <span class="math inline">\(p &lt; 0.10\)</span> rather than <span class="math inline">\(0.05\)</span> is commonly used for this reason, and a non-significant <span class="math inline">\(Q\)</span> is not evidence that the trials agree.</li>
<li><strong>Many large trials, too much power.</strong> With precise trials, differences too small to matter clinically still produce a significant <span class="math inline">\(Q\)</span>.</li>
</ul>
<p>Either way, <span class="math inline">\(Q\)</span> says whether heterogeneity is detectable, not how large it is.</p>
</section>
<section id="sec-tau2" class="level4" data-number="2.4.2">
<h4 data-number="2.4.2" class="anchored" data-anchor-id="sec-tau2"><span class="header-section-number">2.4.2</span> τ²: How Far Apart Are the True Effects?</h4>
<p><span class="math inline">\(\tau^2\)</span> is the variance of the true log ORs across settings, and <span class="math inline">\(\tau\)</span> their standard deviation. It is the quantity with a direct clinical reading: under the random-effects model, about 95% of true effects lie within <span class="math inline">\(\mu \pm 1.96\,\tau\)</span> on the log scale. On the OR scale that is a multiplicative range. With <span class="math inline">\(\tau = 0.3\)</span>, for example, true ORs span a factor of <span class="math inline">\(e^{1.96 \times 0.3} \approx 1.8\)</span> either side of the average OR: an average OR of 2 would be consistent with true ORs from about 1.1 to 3.6 in different settings.</p>
<p>The <strong>DerSimonian–Laird</strong> estimator obtains <span class="math inline">\(\tau^2\)</span> from <span class="math inline">\(Q\)</span>. Under the random-effects model, the expected value of <span class="math inline">\(Q\)</span> rises in a straight line with <span class="math inline">\(\tau^2\)</span>:</p>
<p><span class="math display">\[E(Q) = (k - 1) + \tau^2 \left( \sum w_i - \frac{\sum w_i^2}{\sum w_i} \right)\]</span></p>
<p>The first term is the scatter chance alone produces; the second is the extra scatter from real differences. Setting the observed <span class="math inline">\(Q\)</span> equal to its expected value and solving gives</p>
<p><span class="math display">\[\hat\tau^2_{DL} = \max\left(0, \; \frac{Q - (k - 1)}{\sum w_i - \sum w_i^2 / \sum w_i}\right)\]</span></p>
<p>This is a method-of-moments estimator: it matches one observed statistic to its expectation, with no likelihood involved. Two consequences follow:</p>
<ul>
<li><strong>Truncation at zero.</strong> By chance, <span class="math inline">\(Q\)</span> can fall below <span class="math inline">\(k - 1\)</span>, which would give a negative variance. The estimate is then set to 0. An estimate of <span class="math inline">\(\hat\tau^2 = 0\)</span> therefore means the scatter did not exceed chance, not that the true effects are identical.</li>
<li><strong>One number, treated as known.</strong> The random-effects weights and interval use <span class="math inline">\(\hat\tau^2\)</span> as if it were the true value. With few trials the estimate is very imprecise, and that imprecision is not carried into the pooled interval. Restricted maximum likelihood (REML) and Paule–Mandel are common alternative estimators; the Bayesian model in this guide instead gives <span class="math inline">\(\tau\)</span> a posterior distribution.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Deriving E(Q) and the DerSimonian–Laird estimator
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Write <span class="math inline">\(W = \sum w_i\)</span> and <span class="math inline">\(\hat\theta = \sum w_i y_i / W\)</span>. Under the random-effects model, <span class="math inline">\(y_i = \mu + (\theta_i - \mu) + \varepsilon_i\)</span> with <span class="math inline">\(\text{Var}(y_i) = v_i + \tau^2\)</span>, and the trials are independent.</p>
<p><strong>Step 1: split Q.</strong> Adding and subtracting <span class="math inline">\(\mu\)</span> inside the square, the cross term cancels because <span class="math inline">\(\sum w_i (y_i - \hat\theta) = 0\)</span>:</p>
<p><span class="math display">\[Q = \sum w_i (y_i - \mu)^2 - W (\hat\theta - \mu)^2\]</span></p>
<p><strong>Step 2: the first term.</strong> Each <span class="math inline">\((y_i - \mu)^2\)</span> has expectation <span class="math inline">\(v_i + \tau^2\)</span>, and <span class="math inline">\(w_i v_i = 1\)</span>:</p>
<p><span class="math display">\[E\left[\sum w_i (y_i - \mu)^2\right] = \sum w_i (v_i + \tau^2) = k + \tau^2 W\]</span></p>
<p><strong>Step 3: the second term.</strong> <span class="math inline">\(\hat\theta\)</span> is a weighted average of independent <span class="math inline">\(y_i\)</span>, so</p>
<p><span class="math display">\[\text{Var}(\hat\theta) = \frac{\sum w_i^2 (v_i + \tau^2)}{W^2} = \frac{W + \tau^2 \sum w_i^2}{W^2}\]</span></p>
<p>using <span class="math inline">\(w_i^2 v_i = w_i\)</span>. Since <span class="math inline">\(\hat\theta\)</span> is unbiased for <span class="math inline">\(\mu\)</span>, <span class="math inline">\(E[W(\hat\theta - \mu)^2] = W\,\text{Var}(\hat\theta) = 1 + \tau^2 \sum w_i^2 / W\)</span>.</p>
<p><strong>Step 4: combine.</strong></p>
<p><span class="math display">\[E(Q) = (k + \tau^2 W) - \left(1 + \tau^2 \frac{\sum w_i^2}{W}\right) = (k - 1) + \tau^2 \left( W - \frac{\sum w_i^2}{W} \right)\]</span></p>
<p>With <span class="math inline">\(\tau^2 = 0\)</span> this is the <span class="math inline">\(k - 1\)</span> of the homogeneity test. Replacing <span class="math inline">\(E(Q)\)</span> with the observed <span class="math inline">\(Q\)</span> and solving for <span class="math inline">\(\tau^2\)</span> gives the DerSimonian–Laird estimator.</p>
</div>
</div>
</div>
</section>
<section id="sec-i2" class="level4" data-number="2.4.3">
<h4 data-number="2.4.3" class="anchored" data-anchor-id="sec-i2"><span class="header-section-number">2.4.3</span> I²: What Share of the Scatter Is Real?</h4>
<p><span class="math display">\[I^2 = \max\left(0, \; \frac{Q - (k - 1)}{Q}\right)\]</span></p>
<p><span class="math inline">\(Q\)</span> is the total scatter, <span class="math inline">\(k - 1\)</span> is the part chance would produce, and the difference is the part attributed to real differences. <span class="math inline">\(I^2\)</span> is that difference as a share of the total. The Cochrane Handbook gives rough bands, deliberately overlapping: 0–40% might not be important, 30–60% may be moderate, 50–90% may be substantial, and 75–100% considerable.</p>
<p>The most common misreading is to treat <span class="math inline">\(I^2\)</span> as a measure of how different the true effects are. It is not, because it compares <span class="math inline">\(\tau^2\)</span> with the precision of the trials. The same <span class="math inline">\(I^2\)</span> can be written as</p>
<p><span class="math display">\[I^2 = \frac{\hat\tau^2}{\hat\tau^2 + s^2}\]</span></p>
<p>where <span class="math inline">\(s^2\)</span> is a typical within-trial variance. The same true spread therefore gives very different values of <span class="math inline">\(I^2\)</span> depending on trial size. With <span class="math inline">\(\tau^2 = 0.09\)</span> (<span class="math inline">\(\tau = 0.3\)</span>):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Trials</th>
<th style="text-align: center;">Typical within-trial variance <span class="math inline">\(s^2\)</span></th>
<th style="text-align: center;"><span class="math inline">\(I^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Small</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;"><span class="math inline">\(0.09 / 0.29 \approx 31\%\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Large</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;"><span class="math inline">\(0.09 / 0.11 \approx 82\%\)</span></td>
</tr>
</tbody>
</table>
<p>Large trials leave little room for chance, so almost all the scatter they show counts as real. Two further cautions apply:</p>
<ul>
<li><strong>I² is itself uncertain.</strong> With few trials its confidence interval commonly spans most of the 0–100% range, so a single value such as 59% should not be read to the nearest percentage point.</li>
<li><strong>I² does not tell you what to expect in a new setting.</strong> For that, <span class="math inline">\(\tau\)</span> and the prediction interval below are the relevant quantities.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why I² equals τ² / (τ² + s²)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Write <span class="math inline">\(c = W - \sum w_i^2 / W\)</span>, the denominator of the DerSimonian–Laird estimator, so that <span class="math inline">\(\hat\tau^2 = (Q - (k - 1)) / c\)</span>. Higgins and Thompson (2002) define the typical within-trial variance as</p>
<p><span class="math display">\[s^2 = \frac{(k - 1)\,W}{W^2 - \sum w_i^2} = \frac{k - 1}{c}\]</span></p>
<p>Then, whenever <span class="math inline">\(Q &gt; k - 1\)</span>,</p>
<p><span class="math display">\[\frac{\hat\tau^2}{\hat\tau^2 + s^2} = \frac{(Q - (k - 1)) / c}{(Q - (k - 1)) / c + (k - 1) / c} = \frac{Q - (k - 1)}{Q} = I^2\]</span></p>
<p>So <span class="math inline">\(I^2\)</span> and <span class="math inline">\(\hat\tau^2_{DL}\)</span> carry the same information from <span class="math inline">\(Q\)</span>; <span class="math inline">\(I^2\)</span> simply rescales it by the precision of the trials.</p>
</div>
</div>
</div>
</section>
</section>
<section id="sec-pi" class="level3" data-number="2.5">
<h3 data-number="2.5" class="anchored" data-anchor-id="sec-pi"><span class="header-section-number">2.5</span> The Prediction Interval</h3>
<p>The confidence interval for <span class="math inline">\(\mu\)</span> describes uncertainty about the <strong>average</strong> effect. A decision about a new population needs the range of effects to expect in <strong>one new setting</strong>, which also includes the spread <span class="math inline">\(\tau^2\)</span>:</p>
<p><span class="math display">\[\hat\mu_{RE} \pm 1.96 \sqrt{\hat\tau^2 + \text{Var}(\hat\mu_{RE})}\]</span></p>
<p>With substantial heterogeneity, the prediction interval can include no effect even when the confidence interval does not.</p>
</section>
<section id="sec-bayes" class="level3" data-number="2.6">
<h3 data-number="2.6" class="anchored" data-anchor-id="sec-bayes"><span class="header-section-number">2.6</span> The Bayesian Version: The Same Model, Estimated Differently</h3>
<p>The models above reduce each trial to two numbers, <span class="math inline">\(y_i\)</span> and <span class="math inline">\(v_i\)</span>, and treat <span class="math inline">\(y_i\)</span> as Normal with known variance. The Bayesian model used for NMA skips that reduction and works directly with the number of responders and patients in each arm, through a Binomial likelihood:</p>
<p><span class="math display">\[r_{iA} \sim \text{Binomial}(n_{iA}, p_{iA}), \qquad r_{iB} \sim \text{Binomial}(n_{iB}, p_{iB})\]</span></p>
<p><span class="math display">\[\text{logit}(p_{iA}) = \mu_i, \qquad \text{logit}(p_{iB}) = \mu_i + \delta_i, \qquad \delta_i \sim N(d, \tau^2)\]</span></p>
<p>This is the model of the <a href="../../04_NMA/05_NMA_Technical_Prep/01_Standard_Bayesian_NMA_Guide.html">Standard Bayesian NMA</a> guide with a single comparison, and its unknowns are the ones already met above under different names: <span class="math inline">\(d\)</span> is the average effect (<span class="math inline">\(\mu\)</span> in the random-effects model), <span class="math inline">\(\delta_i\)</span> is trial <span class="math inline">\(i\)</span>’s own true effect (<span class="math inline">\(\theta_i\)</span>), and <span class="math inline">\(\tau\)</span> is the spread between trials. Only the baselines <span class="math inline">\(\mu_i\)</span> are new, because reducing each trial to <span class="math inline">\(y_i\)</span> had already removed them by taking a difference within the trial. Note that <span class="math inline">\(\mu_i\)</span> here is a baseline log odds, not the average effect <span class="math inline">\(\mu\)</span> of the random-effects model; the clash of letters is the convention used in the NMA literature.</p>
<p>What changes is not the model but what is treated as unknown. The frequentist approach treats <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\tau\)</span> as fixed constants to be estimated, and <span class="math inline">\(\theta_i\)</span> as a random draw that is never itself reported. The Bayesian approach treats all of them as unknown quantities with a joint posterior distribution:</p>
<p><span id="eq-post"><span class="math display">\[
\begin{aligned}
p(d, \tau, \delta, \mu \mid \text{counts}) \;\propto\;
&amp; \prod_{i=1}^{k} P(r_{iA}, r_{iB} \mid \mu_i, \delta_i) &amp;&amp; \text{likelihood} \\[4pt]
\times \; &amp; \prod_{i=1}^{k} N(\delta_i \mid d, \tau^2) &amp;&amp; \text{between-trial distribution} \\[4pt]
\times \; &amp; \; p(d)\; p(\tau) \prod_{i=1}^{k} p(\mu_i) &amp;&amp; \text{priors}
\end{aligned}
\tag{10}\]</span></span></p>
<p>There is nothing to solve in (<a href="#eq-post" class="quarto-xref">10</a>); MCMC maps it by sampling, exactly as in <a href="../../04_NMA/05_NMA_Technical_Prep/10_Bayesian_Estimation.html">The Core of Bayesian Estimation</a>.</p>
<p>Counting the unknowns: with <span class="math inline">\(k\)</span> trials there are <span class="math inline">\(2k + 2\)</span> of them, a baseline and a true effect for each trial plus <span class="math inline">\(d\)</span> and <span class="math inline">\(\tau\)</span>. The baselines are nuisance parameters, each identified by its own trial’s control arm and never pooled; the frequentist model removes them by taking a difference within each trial. The <span class="math inline">\(\delta_i\)</span> are not free either: the between-trial distribution holds them together, which is what makes <span class="math inline">\(d\)</span> and <span class="math inline">\(\tau\)</span> estimable and what stops each <span class="math inline">\(\delta_i\)</span> from simply reproducing that trial’s own log OR.</p>
<p>Two things follow, and both show up in the results below.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>With τ held fixed, the two approaches give the same answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Take the Normal approximation of the earlier sections, <span class="math inline">\(y_i \mid \theta_i \sim N(\theta_i, v_i)\)</span> and <span class="math inline">\(\theta_i \sim N(\mu, \tau^2)\)</span>, so that marginally <span class="math inline">\(y_i \sim N(\mu, v_i + \tau^2)\)</span>. Hold <span class="math inline">\(\tau^2\)</span> fixed and put a flat prior on <span class="math inline">\(\mu\)</span>, <span class="math inline">\(p(\mu) \propto 1\)</span>. The posterior is then proportional to the likelihood:</p>
<p><span id="eq-post-mu"><span class="math display">\[p(\mu \mid y) \;\propto\; \prod_{i=1}^{k} \exp\left(-\frac{(y_i - \mu)^2}{2(v_i + \tau^2)}\right) = \exp\left(-\frac{1}{2}\sum_{i=1}^{k} w_i^* (y_i - \mu)^2\right) \tag{11}\]</span></span></p>
<p>with <span class="math inline">\(w_i^* = 1/(v_i + \tau^2)\)</span> as before. Expanding the sum in (<a href="#eq-post-mu" class="quarto-xref">11</a>) and completing the square in <span class="math inline">\(\mu\)</span> gives a Normal posterior:</p>
<p><span id="eq-post-normal"><span class="math display">\[\mu \mid y \;\sim\; N\left( \frac{\sum w_i^* y_i}{\sum w_i^*}, \; \frac{1}{\sum w_i^*} \right) \tag{12}\]</span></span></p>
<p>The posterior mean in (<a href="#eq-post-normal" class="quarto-xref">12</a>) is exactly the random-effects estimate <span class="math inline">\(\hat\mu_{RE}\)</span>, and the posterior variance is exactly <span class="math inline">\(\text{Var}(\hat\mu_{RE})\)</span>. So the DerSimonian–Laird interval is the credible interval of this Bayesian model under a flat prior with <span class="math inline">\(\tau\)</span> fixed at <span class="math inline">\(\hat\tau\)</span>.</p>
<p>The Bayesian model in this guide differs from that special case in two ways: it gives <span class="math inline">\(\tau\)</span> a prior and integrates over it rather than fixing it, and it uses the Binomial counts rather than the Normal approximation. The first difference is what widens the interval in the results below.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Shrinkage: each trial’s own effect is revised
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The posterior also reports each <span class="math inline">\(\delta_i\)</span>, which the frequentist model never estimates. Using the same Normal approximation, with <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\tau^2\)</span> treated as known, the posterior for one trial’s true effect combines two sources: its own result <span class="math inline">\(y_i\)</span>, with precision <span class="math inline">\(1/v_i\)</span>, and the distribution the trials come from, with precision <span class="math inline">\(1/\tau^2\)</span>. Weighting each by its precision,</p>
<p><span id="eq-shrink"><span class="math display">\[E(\theta_i \mid y_i) = B_i \, y_i + (1 - B_i)\, \mu, \qquad B_i = \frac{\tau^2}{\tau^2 + v_i} \tag{13}\]</span></span></p>
<p>Each trial’s estimate is pulled from its own result towards the average of the trials. How far it is pulled depends on the comparison in <span class="math inline">\(B_i\)</span>:</p>
<ul>
<li>A <strong>small trial</strong> has a large <span class="math inline">\(v_i\)</span>, so <span class="math inline">\(B_i\)</span> is small and its result is pulled a long way towards <span class="math inline">\(\mu\)</span>. An extreme result from a small trial is largely discounted.</li>
<li>A <strong>large trial</strong> has a small <span class="math inline">\(v_i\)</span>, so <span class="math inline">\(B_i\)</span> is close to 1 and its result stands nearly as observed.</li>
<li>If <span class="math inline">\(\tau^2 \to 0\)</span>, every <span class="math inline">\(B_i \to 0\)</span> and all trials collapse onto <span class="math inline">\(\mu\)</span>, which is the fixed-effect model.</li>
<li>If <span class="math inline">\(\tau^2\)</span> is large, <span class="math inline">\(B_i \to 1\)</span> and the trials are left alone, as if each were analysed separately.</li>
</ul>
<p>In an NMA this is the mechanism behind a question EAGs often ask: how much of the estimate for a treatment supported by one small trial comes from that trial, and how much is borrowed from the rest of the network.</p>
</div>
</div>
</div>
</section>
</section>
<section id="the-minimal-mock-case-five-trials-of-b-vs-a" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="the-minimal-mock-case-five-trials-of-b-vs-a"><span class="header-section-number">3</span> The Minimal Mock Case: Five Trials of B vs A</h2>
<ul>
<li><strong>Treatment A</strong>: Standard of Care</li>
<li><strong>Treatment B</strong>: New Drug</li>
<li><strong>Outcome</strong>: response (higher is better), so an OR above 1 favours B</li>
</ul>
<p>Five trials of different sizes compared B with A:</p>
<div class="cell">
<details class="code-fold">
<summary>View the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>trials <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">study =</span> <span class="fu">paste</span>(<span class="st">"Study"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_A =</span> <span class="fu">c</span>(<span class="dv">120</span>, <span class="dv">60</span>, <span class="dv">300</span>, <span class="dv">80</span>, <span class="dv">150</span>),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">r_A =</span> <span class="fu">c</span>(<span class="dv">24</span>, <span class="dv">15</span>, <span class="dv">75</span>, <span class="dv">16</span>, <span class="dv">30</span>),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_B =</span> <span class="fu">c</span>(<span class="dv">120</span>, <span class="dv">60</span>, <span class="dv">300</span>, <span class="dv">80</span>, <span class="dv">150</span>),</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">r_B =</span> <span class="fu">c</span>(<span class="dv">45</span>, <span class="dv">28</span>, <span class="dv">88</span>, <span class="dv">34</span>, <span class="dv">60</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(trials, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Study"</span>, <span class="st">"Patients (A)"</span>, <span class="st">"Responders (A)"</span>, <span class="st">"Patients (B)"</span>, <span class="st">"Responders (B)"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Study</th>
<th style="text-align: right;">Patients (A)</th>
<th style="text-align: right;">Responders (A)</th>
<th style="text-align: right;">Patients (B)</th>
<th style="text-align: right;">Responders (B)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Study 1</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">45</td>
</tr>
<tr class="even">
<td style="text-align: left;">Study 2</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">28</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Study 3</td>
<td style="text-align: right;">300</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">300</td>
<td style="text-align: right;">88</td>
</tr>
<tr class="even">
<td style="text-align: left;">Study 4</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Study 5</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">60</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Study 3 is by far the largest trial, and, as the next section shows, the one closest to no effect. That combination is what makes the choice between fixed and random effects visible.</p>
</section>
<section id="implementation-from-scratch-metafor-and-stan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="implementation-from-scratch-metafor-and-stan"><span class="header-section-number">4</span> Implementation: From Scratch, <code>metafor</code> and Stan</h2>
<section id="from-scratch-in-base-r" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="from-scratch-in-base-r"><span class="header-section-number">4.1</span> From Scratch in Base R</h3>
<p>Every quantity from the theoretical framework, computed directly:</p>
<div class="cell">
<details class="code-fold">
<summary>View the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>fmt <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">sprintf</span>(<span class="st">"%.2f"</span>, x)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>ci_text <span class="ot">&lt;-</span> <span class="cf">function</span>(est, se) <span class="fu">sprintf</span>(<span class="st">"%.2f (%.2f, %.2f)"</span>, <span class="fu">exp</span>(est), <span class="fu">exp</span>(est <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se), <span class="fu">exp</span>(est <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Cells of each 2x2 table</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>resp_B <span class="ot">&lt;-</span> trials<span class="sc">$</span>r_B</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>non_B <span class="ot">&lt;-</span> trials<span class="sc">$</span>n_B <span class="sc">-</span> trials<span class="sc">$</span>r_B</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>resp_A <span class="ot">&lt;-</span> trials<span class="sc">$</span>r_A</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>non_A <span class="ot">&lt;-</span> trials<span class="sc">$</span>n_A <span class="sc">-</span> trials<span class="sc">$</span>r_A</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect size and variance per trial</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">log</span>((resp_B <span class="sc">/</span> non_B) <span class="sc">/</span> (resp_A <span class="sc">/</span> non_A)) <span class="co"># log OR</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> resp_B <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> non_B <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> resp_A <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> non_A</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">length</span>(y)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Fixed effect</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> v</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>lor_fe <span class="ot">&lt;-</span> <span class="fu">sum</span>(w <span class="sc">*</span> y) <span class="sc">/</span> <span class="fu">sum</span>(w)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>se_fe <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">/</span> <span class="fu">sum</span>(w))</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Heterogeneity</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>Q <span class="ot">&lt;-</span> <span class="fu">sum</span>(w <span class="sc">*</span> (y <span class="sc">-</span> lor_fe)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>Q_p <span class="ot">&lt;-</span> <span class="fu">pchisq</span>(Q, <span class="at">df =</span> k <span class="sc">-</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>tau2 <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="dv">0</span>, (Q <span class="sc">-</span> (k <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">/</span> (<span class="fu">sum</span>(w) <span class="sc">-</span> <span class="fu">sum</span>(w<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="fu">sum</span>(w))) <span class="co"># DerSimonian-Laird</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>I2 <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="dv">0</span>, (Q <span class="sc">-</span> (k <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">/</span> Q)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Random effects</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>w_re <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> (v <span class="sc">+</span> tau2)</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>lor_re <span class="ot">&lt;-</span> <span class="fu">sum</span>(w_re <span class="sc">*</span> y) <span class="sc">/</span> <span class="fu">sum</span>(w_re)</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>se_re <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">/</span> <span class="fu">sum</span>(w_re))</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="co"># 95% prediction interval, on the OR scale</span></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>pi_half <span class="ot">&lt;-</span> <span class="fl">1.96</span> <span class="sc">*</span> <span class="fu">sqrt</span>(tau2 <span class="sc">+</span> se_re<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>pi_lo <span class="ot">&lt;-</span> <span class="fu">exp</span>(lor_re <span class="sc">-</span> pi_half)</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>pi_hi <span class="ot">&lt;-</span> <span class="fu">exp</span>(lor_re <span class="sc">+</span> pi_half)</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>w_fe_pct <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="sc">*</span> w <span class="sc">/</span> <span class="fu">sum</span>(w)</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>w_re_pct <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="sc">*</span> w_re <span class="sc">/</span> <span class="fu">sum</span>(w_re)</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(trials<span class="sc">$</span>study, <span class="fu">exp</span>(y), y, v, w_fe_pct, w_re_pct),</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Study"</span>, <span class="st">"OR"</span>, <span class="st">"log OR"</span>, <span class="st">"Variance"</span>, <span class="st">"Weight, FE (%)"</span>, <span class="st">"Weight, RE (%)"</span>)</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Study</th>
<th style="text-align: right;">OR</th>
<th style="text-align: right;">log OR</th>
<th style="text-align: right;">Variance</th>
<th style="text-align: right;">Weight, FE (%)</th>
<th style="text-align: right;">Weight, RE (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Study 1</td>
<td style="text-align: right;">2.40</td>
<td style="text-align: right;">0.875</td>
<td style="text-align: right;">0.088</td>
<td style="text-align: right;">16.4</td>
<td style="text-align: right;">19.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Study 2</td>
<td style="text-align: right;">2.62</td>
<td style="text-align: right;">0.965</td>
<td style="text-align: right;">0.156</td>
<td style="text-align: right;">9.2</td>
<td style="text-align: right;">14.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Study 3</td>
<td style="text-align: right;">1.25</td>
<td style="text-align: right;">0.219</td>
<td style="text-align: right;">0.034</td>
<td style="text-align: right;">42.5</td>
<td style="text-align: right;">27.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Study 4</td>
<td style="text-align: right;">2.96</td>
<td style="text-align: right;">1.084</td>
<td style="text-align: right;">0.129</td>
<td style="text-align: right;">11.1</td>
<td style="text-align: right;">16.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Study 5</td>
<td style="text-align: right;">2.67</td>
<td style="text-align: right;">0.981</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">20.7</td>
<td style="text-align: right;">21.8</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>View the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(Q, k <span class="sc">-</span> <span class="dv">1</span>, Q_p, tau2, <span class="dv">100</span> <span class="sc">*</span> I2),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">1</span>),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Cochran's Q"</span>, <span class="st">"df"</span>, <span class="st">"p-value"</span>, <span class="st">"$</span><span class="sc">\\</span><span class="st">tau^2$"</span>, <span class="st">"$I^2$ (%)"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Cochran’s Q</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">p-value</th>
<th style="text-align: right;"><span class="math inline">\(\tau^2\)</span></th>
<th style="text-align: right;"><span class="math inline">\(I^2\)</span> (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">9.73</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.045</td>
<td style="text-align: right;">0.113</td>
<td style="text-align: right;">58.9</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>View the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(<span class="st">"Fixed effect"</span>, <span class="st">"Random effects (DerSimonian-Laird)"</span>),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(<span class="fu">ci_text</span>(lor_fe, se_fe), <span class="fu">ci_text</span>(lor_re, se_re)),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(<span class="st">"&amp;ndash;"</span>, <span class="fu">sprintf</span>(<span class="st">"%.2f to %.2f"</span>, pi_lo, pi_hi))</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Model"</span>, <span class="st">"Pooled OR (95% CI)"</span>, <span class="st">"95% prediction interval"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 44%">
<col style="width: 24%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: left;">Pooled OR (95% CI)</th>
<th style="text-align: left;">95% prediction interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Fixed effect</td>
<td style="text-align: left;">1.92 (1.51, 2.42)</td>
<td style="text-align: left;">–</td>
</tr>
<tr class="even">
<td style="text-align: left;">Random effects (DerSimonian-Laird)</td>
<td style="text-align: left;">2.16 (1.46, 3.19)</td>
<td style="text-align: left;">1.00 to 4.64</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Study 3 has the smallest variance, so under the fixed-effect model it carries 42% of the weight. With <span class="math inline">\(\hat\tau^2 =\)</span> 0.113 added to every variance, its share falls to 27%, while the smallest trial, Study 2, rises from 9% to 15%.</p>
</section>
<section id="cross-check-with-metafor" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="cross-check-with-metafor"><span class="header-section-number">4.2</span> Cross-Check With <code>metafor</code></h3>
<p>The standard R package gives the same numbers:</p>
<div class="cell">
<details class="code-fold">
<summary>View the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(metafor)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>es <span class="ot">&lt;-</span> <span class="fu">escalc</span>(<span class="at">measure =</span> <span class="st">"OR"</span>, <span class="at">ai =</span> r_B, <span class="at">n1i =</span> n_B, <span class="at">ci =</span> r_A, <span class="at">n2i =</span> n_A, <span class="at">data =</span> trials)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>fit_fe <span class="ot">&lt;-</span> <span class="fu">rma</span>(yi, vi, <span class="at">data =</span> es, <span class="at">method =</span> <span class="st">"FE"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>fit_re <span class="ot">&lt;-</span> <span class="fu">rma</span>(yi, vi, <span class="at">data =</span> es, <span class="at">method =</span> <span class="st">"DL"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(<span class="st">"log OR, fixed effect"</span>, <span class="st">"SE, fixed effect"</span>, <span class="st">"log OR, random effects"</span>, <span class="st">"SE, random effects"</span>, <span class="st">"$</span><span class="sc">\\</span><span class="st">tau^2$"</span>, <span class="st">"$I^2$ (%)"</span>),</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(lor_fe, se_fe, lor_re, se_re, tau2, <span class="dv">100</span> <span class="sc">*</span> I2),</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(<span class="fu">coef</span>(fit_fe), fit_fe<span class="sc">$</span>se, <span class="fu">coef</span>(fit_re), fit_re<span class="sc">$</span>se, fit_re<span class="sc">$</span>tau2, fit_re<span class="sc">$</span>I2)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">4</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Quantity"</span>, <span class="st">"From scratch"</span>, <span class="st">"metafor"</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: right;">From scratch</th>
<th style="text-align: right;">metafor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">log OR, fixed effect</td>
<td style="text-align: right;">0.6500</td>
<td style="text-align: right;">0.6500</td>
</tr>
<tr class="even">
<td style="text-align: left;">SE, fixed effect</td>
<td style="text-align: right;">0.1200</td>
<td style="text-align: right;">0.1200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log OR, random effects</td>
<td style="text-align: right;">0.7682</td>
<td style="text-align: right;">0.7682</td>
</tr>
<tr class="even">
<td style="text-align: left;">SE, random effects</td>
<td style="text-align: right;">0.1996</td>
<td style="text-align: right;">0.1996</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\tau^2\)</span></td>
<td style="text-align: right;">0.1131</td>
<td style="text-align: right;">0.1131</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(I^2\)</span> (%)</td>
<td style="text-align: right;">58.8789</td>
<td style="text-align: right;">58.8789</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The forest plot shows each trial with its 95% CI, the random-effects pooled estimate as a diamond, and the prediction interval as the dotted line through it:</p>
<div class="cell">
<details class="code-fold">
<summary>View the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">forest</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    fit_re,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">slab =</span> trials<span class="sc">$</span>study,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">atransf =</span> exp,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">at =</span> <span class="fu">log</span>(<span class="fu">c</span>(<span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">8</span>)),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">addpred =</span> <span class="cn">TRUE</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">header =</span> <span class="fu">c</span>(<span class="st">"Study"</span>, <span class="st">"OR [95% CI]"</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="12_Pairwise_Meta_Analysis_files/figure-html/forest-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="bayesian-random-effects-in-stan" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="bayesian-random-effects-in-stan"><span class="header-section-number">4.3</span> Bayesian Random Effects in Stan</h3>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Stan model: pairwise_re.stan
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output cell-output-stdout">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode stan code-with-copy"><code class="sourceCode stan"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">data</span> {</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">int</span>&lt;<span class="kw">lower</span>=<span class="dv">1</span>&gt; S;                        <span class="co">// number of studies</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">array</span>[S] <span class="dt">int</span>&lt;<span class="kw">lower</span>=<span class="dv">0</span>&gt; n_A;             <span class="co">// patients on A</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">array</span>[S] <span class="dt">int</span>&lt;<span class="kw">lower</span>=<span class="dv">0</span>&gt; r_A;             <span class="co">// responders on A</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">array</span>[S] <span class="dt">int</span>&lt;<span class="kw">lower</span>=<span class="dv">0</span>&gt; n_B;             <span class="co">// patients on B</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">array</span>[S] <span class="dt">int</span>&lt;<span class="kw">lower</span>=<span class="dv">0</span>&gt; r_B;             <span class="co">// responders on B</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="kw">parameters</span> {</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="dt">vector</span>[S] mu;                          <span class="co">// baseline log odds on A, one per study</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="dt">real</span> d;                                <span class="co">// pooled log OR, B vs A</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="dt">real</span>&lt;<span class="kw">lower</span>=<span class="dv">0</span>&gt; tau;                     <span class="co">// between-study SD of the log OR</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  <span class="dt">vector</span>[S] z;                           <span class="co">// standardised study-level deviations</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="kw">transformed parameters</span> {</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  <span class="dt">vector</span>[S] delta = d + tau * z;         <span class="co">// study-specific log OR (non-centred)</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="kw">model</span> {</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>  mu ~ normal(<span class="dv">0</span>, <span class="dv">10</span>);</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  d ~ normal(<span class="dv">0</span>, <span class="dv">10</span>);</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>  tau ~ normal(<span class="dv">0</span>, <span class="dv">1</span>);                    <span class="co">// half-normal, since tau &gt;= 0</span></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>  z ~ std_normal();</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>  r_A ~ binomial_logit(n_A, mu);</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>  r_B ~ binomial_logit(n_B, mu + delta);</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a><span class="kw">generated quantities</span> {</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>  <span class="dt">real</span> OR = exp(d);                      <span class="co">// pooled OR</span></span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>  <span class="dt">real</span> OR_new = exp(normal_rng(d, tau)); <span class="co">// OR in a new study setting</span></span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</div>
<p>Three choices in the model are worth stating:</p>
<ul>
<li><strong>Priors</strong>: <span class="math inline">\(N(0, 10^2)\)</span> for the baselines <span class="math inline">\(\mu_i\)</span> and the pooled log OR <span class="math inline">\(d\)</span>, which is vague on the log-odds scale; half-Normal<span class="math inline">\((0, 1)\)</span> for <span class="math inline">\(\tau\)</span>, which keeps implausibly large heterogeneity unlikely without ruling it out. NICE DSU TSD 2 uses wider conventions, <span class="math inline">\(N(0, 100^2)\)</span> for <span class="math inline">\(\mu_i\)</span> and <span class="math inline">\(d\)</span> and <span class="math inline">\(\sigma \sim \text{Uniform}(0, 2)\)</span> for the between-trial standard deviation; the tighter priors here are chosen to sample stably with only five trials, and a submission would report a sensitivity analysis over both.</li>
<li><strong>Non-centred parameterisation</strong>: <span class="math inline">\(\delta_i = d + \tau z_i\)</span> with <span class="math inline">\(z_i \sim N(0, 1)\)</span>. It describes the same model as <span class="math inline">\(\delta_i \sim N(d, \tau^2)\)</span>, but samples far more reliably when <span class="math inline">\(\tau\)</span> is poorly identified, as it is with five trials.</li>
<li><strong>Prediction</strong>: <code>OR_new</code> draws a log OR for a new study from <span class="math inline">\(N(d, \tau^2)\)</span> at every iteration, giving the Bayesian counterpart of the prediction interval.</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>View the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstan)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>stan_data <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">S =</span> <span class="fu">nrow</span>(trials),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_A =</span> trials<span class="sc">$</span>n_A, <span class="at">r_A =</span> trials<span class="sc">$</span>r_A,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_B =</span> trials<span class="sc">$</span>n_B, <span class="at">r_B =</span> trials<span class="sc">$</span>r_B</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>fit_bayes <span class="ot">&lt;-</span> <span class="fu">stan</span>(</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">file =</span> <span class="st">"pairwise_re.stan"</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> stan_data,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">chains =</span> <span class="dv">4</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">iter =</span> <span class="dv">4000</span>,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">warmup =</span> <span class="dv">2000</span>,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">seed =</span> <span class="dv">42</span>,</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">control =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.99</span>),</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">refresh =</span> <span class="dv">0</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>bayes_sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit_bayes, <span class="at">pars =</span> <span class="fu">c</span>(<span class="st">"d"</span>, <span class="st">"OR"</span>, <span class="st">"tau"</span>, <span class="st">"OR_new"</span>))<span class="sc">$</span>summary</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>    bayes_sum[, <span class="fu">c</span>(<span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"2.5%"</span>, <span class="st">"50%"</span>, <span class="st">"97.5%"</span>, <span class="st">"n_eff"</span>, <span class="st">"Rhat"</span>)],</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">0</span>, <span class="dv">3</span>),</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Mean"</span>, <span class="st">"SD"</span>, <span class="st">"2.5%"</span>, <span class="st">"Median"</span>, <span class="st">"97.5%"</span>, <span class="st">"ESS"</span>, <span class="st">"R-hat"</span>)</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">2.5%</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">97.5%</th>
<th style="text-align: right;">ESS</th>
<th style="text-align: right;">R-hat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">d</td>
<td style="text-align: right;">0.778</td>
<td style="text-align: right;">0.263</td>
<td style="text-align: right;">0.288</td>
<td style="text-align: right;">0.766</td>
<td style="text-align: right;">1.334</td>
<td style="text-align: right;">3229</td>
<td style="text-align: right;">1.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">OR</td>
<td style="text-align: right;">2.256</td>
<td style="text-align: right;">0.647</td>
<td style="text-align: right;">1.334</td>
<td style="text-align: right;">2.151</td>
<td style="text-align: right;">3.796</td>
<td style="text-align: right;">3175</td>
<td style="text-align: right;">1.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">tau</td>
<td style="text-align: right;">0.433</td>
<td style="text-align: right;">0.263</td>
<td style="text-align: right;">0.057</td>
<td style="text-align: right;">0.383</td>
<td style="text-align: right;">1.117</td>
<td style="text-align: right;">2758</td>
<td style="text-align: right;">1.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">OR_new</td>
<td style="text-align: right;">2.762</td>
<td style="text-align: right;">7.868</td>
<td style="text-align: right;">0.719</td>
<td style="text-align: right;">2.137</td>
<td style="text-align: right;">7.462</td>
<td style="text-align: right;">7858</td>
<td style="text-align: right;">1.000</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>View the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>n_div <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">sapply</span>(<span class="fu">get_sampler_params</span>(fit_bayes, <span class="at">inc_warmup =</span> <span class="cn">FALSE</span>), <span class="cf">function</span>(x) <span class="fu">sum</span>(x[, <span class="st">"divergent__"</span>])))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>All R-hat values are at or below 1.001, the smallest ESS is 2758, and the sampler reported 0 divergent transitions.</p>
</section>
</section>
<section id="results" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="results"><span class="header-section-number">5</span> Results &amp; Interpretation</h2>
<div class="cell">
<details class="code-fold">
<summary>View the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> rstan<span class="sc">::</span><span class="fu">extract</span>(fit_bayes, <span class="at">pars =</span> <span class="fu">c</span>(<span class="st">"OR"</span>, <span class="st">"OR_new"</span>, <span class="st">"tau"</span>))</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>b_or <span class="ot">&lt;-</span> <span class="fu">quantile</span>(post<span class="sc">$</span>OR, <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.025</span>, <span class="fl">0.975</span>))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>b_new <span class="ot">&lt;-</span> <span class="fu">quantile</span>(post<span class="sc">$</span>OR_new, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>b_tau <span class="ot">&lt;-</span> <span class="fu">quantile</span>(post<span class="sc">$</span>tau, <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.025</span>, <span class="fl">0.975</span>))</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(<span class="st">"Fixed effect"</span>, <span class="st">"Random effects (DerSimonian-Laird)"</span>, <span class="st">"Random effects (Bayesian)"</span>),</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(<span class="fu">ci_text</span>(lor_fe, se_fe), <span class="fu">ci_text</span>(lor_re, se_re), <span class="fu">sprintf</span>(<span class="st">"%.2f (%.2f, %.2f)"</span>, b_or[<span class="dv">1</span>], b_or[<span class="dv">2</span>], b_or[<span class="dv">3</span>])),</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(<span class="st">"&amp;ndash;"</span>, <span class="fu">sprintf</span>(<span class="st">"%.2f to %.2f"</span>, pi_lo, pi_hi), <span class="fu">sprintf</span>(<span class="st">"%.2f to %.2f"</span>, b_new[<span class="dv">1</span>], b_new[<span class="dv">2</span>])),</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(<span class="st">"0 (assumed)"</span>, <span class="fu">sprintf</span>(<span class="st">"%.2f"</span>, <span class="fu">sqrt</span>(tau2)), <span class="fu">sprintf</span>(<span class="st">"%.2f (%.2f, %.2f)"</span>, b_tau[<span class="dv">1</span>], b_tau[<span class="dv">2</span>], b_tau[<span class="dv">3</span>]))</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Model"</span>, <span class="st">"Pooled OR (95% interval)"</span>, <span class="st">"95% prediction interval"</span>, <span class="st">"$</span><span class="sc">\\</span><span class="st">tau$ (between-study SD)"</span>)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 31%">
<col style="width: 22%">
<col style="width: 21%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: left;">Pooled OR (95% interval)</th>
<th style="text-align: left;">95% prediction interval</th>
<th style="text-align: left;"><span class="math inline">\(\tau\)</span> (between-study SD)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Fixed effect</td>
<td style="text-align: left;">1.92 (1.51, 2.42)</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">0 (assumed)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Random effects (DerSimonian-Laird)</td>
<td style="text-align: left;">2.16 (1.46, 3.19)</td>
<td style="text-align: left;">1.00 to 4.64</td>
<td style="text-align: left;">0.34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Random effects (Bayesian)</td>
<td style="text-align: left;">2.15 (1.33, 3.80)</td>
<td style="text-align: left;">0.72 to 7.46</td>
<td style="text-align: left;">0.38 (0.06, 1.12)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Three readings of this table matter for an HTA submission.</p>
<p><strong>Fixed vs random effects.</strong> The fixed-effect OR (1.92) sits closer to Study 3 than the random-effects OR (2.16), because the fixed-effect model gives the largest, least favourable trial 42% of the weight. Which is right is not a statistical question alone: if the trials plausibly differ in population or setting, the fixed-effect assumption of one common effect is hard to defend, and its narrower interval is not a real gain in precision.</p>
<p><strong>Confidence vs prediction interval.</strong> The random-effects 95% CI (1.46 to 3.19) describes the average effect across settings like these trials. The prediction interval (1.00 to 4.64) describes the effect to expect in one new setting, and its lower end sits at 1.00. B helps on average; whether it helps in a particular new population is far less certain. A cost-effectiveness model that uses only the pooled estimate carries the first statement, not the second.</p>
<p><strong>Frequentist vs Bayesian random effects.</strong> The Bayesian 95% interval for the pooled OR (1.33 to 3.80) is wider than the DerSimonian–Laird CI. The two are not different models: as <a href="#sec-bayes" class="quarto-xref">Section&nbsp;2.6</a> shows, holding <span class="math inline">\(\tau\)</span> fixed and using a flat prior reproduces the DerSimonian–Laird estimate and interval exactly. The difference is that DerSimonian–Laird plugs in one value of <span class="math inline">\(\tau\)</span> (0.34) as if it were known, while the Bayesian model carries the uncertainty about <span class="math inline">\(\tau\)</span> itself, whose 95% interval runs from 0.06 to 1.12. With five trials, that uncertainty is large, and ignoring it overstates precision.</p>
</section>
<section id="audit" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="audit"><span class="header-section-number">6</span> HTA Audit Points &amp; Interview Q&amp;A</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Should I choose fixed or random effects based on I²?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>No.&nbsp;I² is a supporting signal, not a switch, and a low I² with few trials is weak evidence of homogeneity, because <span class="math inline">\(Q\)</span> has little power to detect heterogeneity when <span class="math inline">\(k\)</span> is small. The judgement starts from whether the trials plausibly estimate one common effect; see <a href="#nte-choose" class="quarto-xref">Note&nbsp;1</a> for the full order.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>What does an I² of around 60% actually tell you?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>That around 60% of the scatter between trials is real rather than chance, not how far apart the true effects are: that depends on trial size as well, and <span class="math inline">\(\tau\)</span> or the prediction interval is the measure to use. See <a href="#sec-i2" class="quarto-xref">Section&nbsp;2.4.3</a>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Why is DerSimonian–Laird criticised when there are few trials?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It estimates <span class="math inline">\(\tau^2\)</span> from one moment equation and then treats the estimate as fixed, so the confidence interval ignores the uncertainty in <span class="math inline">\(\tau^2\)</span>. With few trials that uncertainty is large, and the interval is too narrow. Common remedies are the Hartung–Knapp–Sidik–Jonkman adjustment, which rescales the variance and uses a <span class="math inline">\(t\)</span> distribution, usually widening the interval, restricted maximum likelihood for <span class="math inline">\(\tau^2\)</span>, or a Bayesian model that carries the uncertainty in <span class="math inline">\(\tau\)</span> through, as above.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>When is a pairwise meta-analysis enough, and when do you need an NMA?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A pairwise meta-analysis is enough when the decision problem is one comparison and there are head-to-head trials of it. Once the decision involves several treatments, or the comparator of interest has never been tested directly against the new treatment, the evidence has to be connected through common comparators, which is what an <a href="../../04_NMA/05_NMA_Technical_Prep/01_Standard_Bayesian_NMA_Guide.html">NMA</a> does.</p>
</div>
</div>
</div>
</section>
<section id="conclusion" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">7</span> Conclusion</h2>
<p>Pairwise meta-analysis comes down to a weighted average with two decisions attached: how to weight the trials, and whether they share one effect. The fixed-effect model weights by precision alone; the random-effects model adds between-study variance, which evens out the weights, widens the interval and makes the prediction interval available. The Bayesian version works from the counts and carries the uncertainty in <span class="math inline">\(\tau\)</span>, and it is the same model that a <a href="../../04_NMA/05_NMA_Technical_Prep/01_Standard_Bayesian_NMA_Guide.html">Standard Bayesian NMA</a> extends to a network of comparisons.</p>
<p><strong>Methodological References</strong>: NICE DSU TSD 2 (Dias et al., 2011, updated 2016); <em>Cochrane Handbook for Systematic Reviews of Interventions</em>, Chapter 10; DerSimonian &amp; Laird (1986); Higgins, Thompson &amp; Spiegelhalter (2009) on prediction intervals.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>