{
  "hash": "47ade7cc7de9a75f68d48019e9153974",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Survival Analysis & Immortal Time Bias in Real-World Evidence\"\nsubtitle: \"Target Trial Emulation, Landmark Analysis, and Time-Varying Cox Regression\"\nauthor: \"Xiaoge Zhang, PhD\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    code-summary: \"R Code\"\n    number-sections: true\n    reference-location: margin\n---\n\n*Methodological guidelines and implementation templates for survival analysis, delayed treatment initiation, and target trial emulation in health technology assessment.*\n\n## Introduction: Causal Inference in Time-to-Event Data\n\nIn health technology assessment (HTA), clinical endpoints are frequently **time-to-event outcomes**. While aggregate summaries like Overall Survival (OS) or Progression-Free Survival (PFS) are represented as curves showing the *proportion* or *probability* of surviving patients at specific points in time, the underlying outcome measured at the patient level is the actual **duration of time** (e.g., months or days) elapsed from a defined baseline (such as diagnosis or treatment initiation) until the clinical event of interest (e.g., death, relapse) occurs.\n\nUnlike binary outcomes where logistic regression or propensity score matching are applied statically, survival data introduces a critical dimension: **Time**. \n\nIf time-to-event analysis is not bounded by strict causal constraints, observational analyses can yield severe selection biases. A primary methodological challenge in retrospective registries is **Immortal Time Bias (ITB)**. \n\n### The Coffee & Heart Disease Paradox: Temporal Ordering and Selection Bias\n\nTo understand why a strict time-to-event framework is necessary, consider the \"Coffee & Heart Disease Paradox\":\n\n- **The Paradox**: Observational studies often show that coffee drinkers have lower rates of heart disease than non-coffee drinkers (Hazard Ratio < 1.0).\n- **The Reverse Causality**: In reality, patients who develop heart symptoms or are diagnosed with high risk are advised by doctors to quit coffee.\n- **The Methodological Connection**: If we classify exposure statically based on whether a patient drinks coffee during follow-up, we violate the **chronological ordering** of causal inference. A patient who develops heart disease on **Day 50** and **subsequently** quits coffee will be misclassified as a \"non-coffee drinker\" at the **end of the study**. This attributes their heart event (which occurred **before** quitting) to the non-exposure group, violating the non-anticipatory constraint of time-to-event outcomes. \n\nTo resolve this paradox, we must align the study baseline ($T_0$), measure confounders (like baseline heart risk) strictly *before* exposure initiation, and model exposure dynamically over time. This is exactly what Target Trial Emulation and Time-Varying survival models achieve.\n\n## The Target Trial Emulation (TTE) Framework\n\nTarget Trial Emulation is a structured design framework developed by Miguel Hernán and colleagues to **guide the design** and analysis of observational studies. The core principle is that we should design our observational study **to mimic a hypothetical randomized trial as closely as possible.**\n\n### The 7 Dimensions of the Target Trial Approach\n\nAccording to the official NICE RWE Framework (Section 5.2)[^1], a target trial must be defined across 7 core dimensions to prevent bias and ensure transparency:\n\n[^1]: **Official Source:** NICE Real-World Evidence Framework (2022), Section 5.2 (\"The target trial approach\"). **Methodological Reference:** Hernán MA, Robins JM (2016). *Using Big Data to Emulate a Target Trial When a Randomized Trial Is Not Available*. Am J Epidemiol.\n\n| Dimension | NICE RWE Framework Requirement | Application to Survival Cohorts |\n| :--- | :--- | :--- |\n| **1. Eligibility criteria** | Define clear inclusion/exclusion criteria at baseline. | Patients must meet all criteria at Time Zero ($T_0$), ensuring no baseline selection bias. |\n| **2. Treatment strategies** | Specify the interventions being compared. | **Arm A:** Initiate active treatment within a defined window. **Arm B:** Initiate Standard of Care (SOC) / no treatment. |\n| **3. Assignment procedure** | Define how treatment groups are formed. | Emulate randomization at $T_0$ using Propensity Scores (IPTW or matching) based on baseline covariates. |\n| **4. Follow-up period** | Align follow-up start exactly with $T_0$. | Clock starts ticking for all patients at $T_0$. Ends at the event, death, censoring, or study end. |\n| **5. Outcomes** | Define a standardized clinical endpoint. | First occurrence of the event (e.g., death, progression) during the follow-up period. |\n| **6. Causal effect of interest** | Specify the causal contrast of interest. | **Intention-to-Treat (ITT):** Effect of treatment assignment at $T_0$, regardless of later compliance. |\n| **7. Analysis plan** | Specify the statistical estimator. | Cox Proportional Hazards model or parametric survival models, adjusted for baseline confounding. |\n\n### Deep Dive: The New User Design\n\nA fundamental rule of TTE is the **New User Design**[^2]. In observational studies, researchers often mistakenly compare \"prevalent users\" (patients already on the drug for some time) with \"never users.\" This introduces three major issues:\n\n[^2]: **Defining a \"New User\":** A patient is classified as a \"new user\" only if they initiate the drug of interest for the first time at $T_0$. This requires establishing a **washout period** (e.g., 180 or 365 days prior to $T_0$) during which they have no records of the drug in the database, ensuring they are not \"prevalent users.\"\n\n- **Survivor Bias**: Prevalent users are, by definition, \"survivors\" who have tolerated the drug and survived long enough to be observed in the database. Patients who died or discontinued the drug early due to adverse events are systematically excluded from the treated group, creating a false survival advantage.\n- **Baseline Contamination**: To adjust for confounding, we must measure covariates **before** treatment starts. For prevalent users, their baseline measurements (e.g., blood pressure, lab values) are already affected by the treatment, making it impossible to measure their true pre-treatment state.\n- **$T_0$ Synchronization**: We cannot align the start of follow-up with the start of treatment if treatment began years before the observation period.\n\nA New User Design enforces that patients are only entered into the cohort at the exact moment they **initiate** the treatment of interest.\n\n### Deep Dive: Intention-to-Treat (ITT) in RWD (Cloning & Censoring)\n\nIn randomized trials, the ITT principle analyzes patients in the group they were randomized to, regardless of whether they complied. In retrospective RWD, we often face a \"grace period\"—a window of time (e.g., 30 or 60 days) after diagnosis during which patients are allowed to initiate treatment.\n\nIf we assign patients to the \"treated\" group because they initiated treatment on day 30, we violate the ITT principle by using \"future knowledge\" at $T_0$. To solve this, TTE uses **Cloning**:\n\n1. **Cloning at $T_0$**: At the moment of eligibility ($T_0$), we create two identical copies of each patient. One copy is assigned to Arm A (Initiate Treatment), and one copy is assigned to Arm B (Standard of Care).\n2. **Follow-up**: Both clones begin follow-up at $T_0$.\n3. **Censoring**: If a patient assigned to Arm B initiates treatment on day 30, their Arm B clone is **censored** at day 30 (because they violated the \"no treatment\" protocol). The Arm A clone continues to be followed.\n4. **IPCW Adjustment**: To correct for selection bias introduced by this artificial censoring, we apply **Inverse Probability of Censoring Weights (IPCW)**, which upweights the remaining uncensored clones who share similar baseline characteristics.\n\n### Causal Transparency: Why TTE Aligns with the DataSAT Tool\n\nNICE prefers TTE because it enforces **Transparency**. \n\nIn a simple Cox regression, you often see:\n$$\\text{Surv}(\\text{time}, \\text{event}) \\sim \\text{Treatment} + \\text{Confounders}$$\n\nAn auditor cannot see:\n\n- When was the treatment started?\n- Were the confounders measured *before* or *after* the drug was given?\n- Is there a \"Healthy User Bias\"?\n\nBy using the **DataSAT** tool (Data Suitability Assessment Tool), NICE auditors look for **Provenance**—the clear lineage of how a patient moved from a raw database record to a study row. TTE forces the researcher to write a \"Trial Protocol\" *before* touching the data, making it obvious where $T_0$ is. If an auditor sees that you measured covariates after the drug was given and used them as baseline, the TTE framework will flag this as a \"Post-baseline Bias\" immediately.\n\n## Applied Scenario: Zero-Time Alignment in an Oncology External Control Arm\n\nTo see how these principles apply in an HTA-facing RWE setting, consider **Drug X**, a precision oncology therapy for METex14-mutated non-small cell lung cancer (NSCLC).\n\n::: {.callout-note collapse=\"true\"}\n### Declaration: Simulated Proof-of-Methodology Scenario\nThis METex14 scenario is a **self-generated proof-of-methodology example**, not a real NICE submission, manufacturer dossier, or clinical claim about an identifiable medicine. Drug X, the sample sizes, data source details, and audit responses are simplified or fictionalized to demonstrate how target trial emulation, immortal time bias correction, and DataSAT-style reasoning can be documented in an HTA-facing RWE workflow.\n:::\n\n### Scenario Overview: The Drug X Challenge\n\n- **The Innovation**: Due to the rarity of the METex14 mutation and ethical constraints, only a **Single-arm Trial (N=40)** was conducted for Drug X.\n- **The Challenge**: A single-arm submission faces a high risk of rejection due to the lack of a randomized head-to-head comparison. Given the aggressive natural history of METex14 NSCLC, simple unadjusted benchmarking is insufficient for demonstrating comparative effectiveness.\n- **The Strategy**: We leverage the UK **Hospital Episode Statistics (HES)** database to construct an External Control Arm (ECA) of 200 patients, using the Target Trial Emulation (TTE) framework to satisfy NICE's demand for rigorous causal inference.\n\n### Data Suitability Considerations (DataSAT)\n\nAccording to Sections 3.1–3.3 of the NICE RWE Framework, we must prove the data is fit for purpose across three core dimensions:\n\n| Dimension | HTA Audit Response (HES Database) | NICE Framework Requirement |\n| :--- | :--- | :--- |\n| **Provenance** | Data sourced from NHS Digital with a clear audit trail from ICD-10 coding to the final analytical dataset. | Evaluate the **origin and trustworthiness** of data sources, methods of collection, and governance. (Section 3.1) |\n| **Quality** | METex14 status confirmed via secondary linkage to SACT and genomic records; completeness checked for key covariates. | Assess the **completeness and accuracy** of eligibility criteria, exposures, and outcomes. (Section 3.2) |\n| **Relevance** | HES covers 99% of NHS hospital activity, matching the SOC pathways in the UK. | Ensure findings **generalise to the target population** and clinical care pathways in the NHS. (Section 3.3) |\n\n### Defining $T_0$ (Zero-time Alignment)\n\nTo avoid Immortal Time Bias, we align $T_0$ as the moment a patient meets all eligibility criteria **AND** is assigned to treatment, following the target trial approach described in **Section 5.2 of the NICE RWE Framework**. Basically, the index date and treatment strategy assignment must be defined **without using future information**. Treatment status observed after $T_0$ cannot be used retrospectively to create baseline groups unless it is handled through a pre-specified grace-period strategy, such as cloning and censoring.\n\n#### Why Immortal Time Bias is a \"Statistical Killer\" {.unnumbered}\n\n1. **Logic Paradox**: In RWD studies, patients from diagnosis to actual treatment initiation (Drug X) face delays (e.g., 1 month). If follow-up begins at diagnosis, but grouping is based on whether they ever received treatment, the period before receiving the drug is **immortal**—if the patient **died on Day 15**, they would **never** have lived long enough to receive the drug, and would automatically be classified into the control group (since they are not \"treated\").\n2. **Case Simulation**:\n\n   - **Patient A**: Diagnosed Jan 1, scheduled for Drug X, dies Jan 15 (unexposed). Classified as Control.\n   - **Patient B**: Diagnosed Jan 1, initiates Drug X Feb 1, survives until June.\n   - **Result**: The Drug X group artificially filters out those who die before treatment initiation, inflating the active group's survival.\n3. **TTE Correction**: The survival follow-up clock must be aligned to a clearly defined index date that is comparable across arms. If the estimand starts at diagnosis but treatment can begin during a grace period, the waiting time must not be retrospectively credited to the treated group; it should be handled using cloning-and-censoring, a time-varying exposure model, or a pre-specified landmark strategy.\n\n#### The Control Arm $T_0$ {.unnumbered}\n\nWhere does the control arm's $T_0$ start if they never receive the active treatment?\n\n- **Synchronicity Principle**: $T_0$ is the moment the patient meets all clinical eligibility criteria (e.g., METex14 diagnosis + ECOG status).\n- **Timeline Alignment**:\n  - *Incorrect*: Treated group starts at the \"first recorded treatment start date\", while controls start at \"diagnosis\". This gives the treated group an implicit survival benefit.\n  - *Correct TTE Approach*: Both groups start follow-up at the exact date they meet all eligibility criteria (the clinical decision point, or clinical equipoise). \n\n#### Handling the Grace Period {.unnumbered}\n\nIn RWD, a patient has a \"window\" of time (grace period) to initiate treatment (e.g., 30 days after diagnosis). \n\n- If a patient initiates treatment on Day 20, they contribute 20 days of \"unexposed\" person-time to the control group.\n- Using cloning, we create two clones at diagnosis. The \"Control Clone\" is followed until Day 20, where it is censored because the patient initiated treatment. The \"Treated Clone\" starts contributing treated time from Day 20 onwards.\n\n### Implication for Cloning & Censoring\n\nTo maintain ITT principles:\n\n- **Anti-Future-Knowledge**: We cannot look ahead to see what the patient did. We clone them at $T_0$ into both paths.\n- **Artificial Censoring**: If the patient's actual path deviates from a clone's assigned arm, that clone is censored.\n- **IPCW Weighting**: Because censoring might be non-random, we estimate the probability of being censored at time $t$ based on baseline covariates and apply Inverse Probability of Censoring Weights to the remaining patients, dynamically restoring the balance.\n\n## Immortal Time Bias (ITB): Theory & Landmark Analysis\n\n### The Meditation & Longevity Paradox\n\nConsider a study evaluating whether a 12-week intensive meditation course increases overall survival (OS):\n\n- **Cohort**: 1,000 participants followed for 5 years.\n- **Exposure Group ($Z=1$)**: Completed the full 12-week program.\n- **Control Group ($Z=0$)**: Did not complete the program (includes those who died or dropped out before week 12).\n- **The Result**: Participants who completed the course show a Hazard Ratio ($HR$) of 0.30 (70% risk reduction).[^meditation-completion]\n- **The Error**: Since a patient had to survive 12 weeks to complete the program, the meditation group is guaranteed 0% mortality during the first 12 weeks. Sicker patients who died in weeks 1–11 were automatically allocated to the control group.\n\n[^meditation-completion]: Completion status at Week 12 is post-baseline information. It **cannot** be used retrospectively to define the baseline exposure group; otherwise, the first 12 weeks of survival are incorrectly credited to the intervention.\n\n### Landmark Analysis\n\nLandmark Analysis is a classical approach to resolve this:\n\n1. **Select Landmark Time ($T_L$)**: E.g., Week 12.\n2. **Exclude Early Events**: Exclude all patients who died or were censored before $T_L$.\n3. **Re-classify**: Classify survivors at $T_L$ based on their exposure status at $T_L$.\n4. **Follow-up**: Set $T_L$ as the new baseline ($T_{start} = T_L$) and follow patients from that point.\n\n#### HTA Audit of Landmark Analysis {.unnumbered}\n\n- **Pros**: Simple, highly intuitive, and removes the immortal period.\n- **Cons**: \n  - **Information Loss**: Discards all events and person-time before $T_L$. If the drug **has high early toxicity**, this signal is completely lost.\n  - **Selection Bias**: The populations at $T_L$ may no longer be balanced, as sicker patients in the control group may have died, while sicker patients in the treated group were protected by the \"immortal\" definition.\n\nTherefore, landmark analysis is usually better positioned as an intuitive diagnostic or sensitivity analysis, rather than the preferred primary analysis for HTA submissions. It is most defensible when the clinical question is explicitly conditional on surviving and remaining eligible until the landmark time; otherwise, time-varying exposure models or cloning-censoring-IPCW are generally more aligned with the original target trial estimand.\n\n## Time-Dependent Cox Model & HTA Practice\n\nThe time-dependent Cox model is an extension of the standard Cox proportional hazards model that allows a patient's exposure status to **change during follow-up**. This makes it useful for auditing and correcting immortal time bias when treatment initiation is delayed.\n\n### What the Model Does\n\nIn a standard Cox model, treatment is usually treated as fixed at baseline:\n\n$$\nh_i(t) = h_0(t)\\exp(\\beta Z_i + \\gamma L_i)\n$$\n\nwhere $Z_i$ is a single treatment indicator for patient $i$, and $L_i$ represents baseline covariates such as age or ECOG status.\n\nThe problem is that delayed treatment is not fixed at baseline. A patient may be untreated from Day 0 to Day 60, then treated from Day 60 onward. A time-dependent Cox model replaces the fixed treatment indicator $Z_i$ with a time-updated treatment indicator $Z_i(t)$:\n\n$$\nh_i(t) = h_0(t)\\exp(\\beta Z_i(t) + \\gamma L_i)\n$$\n\nHere, $Z_i(t)=0$ before treatment starts and $Z_i(t)=1$ after treatment starts. At each event time, the Cox model compares patients according to their treatment status **at that moment**, not according to information observed later in follow-up.\n\nThis is the key correction for immortal time bias: the waiting period before treatment is counted as untreated person-time, rather than being retrospectively assigned to the treated group.\n\n### Counting Process Data Structure\n\nTo estimate this model, the data usually need to be written in counting process format. Rather than one row per patient, the dataset is split into multiple intervals `(tstart, tstop]` where treatment status remains constant.\n\n#### Start-Stop Data Format Example (Patient #101) {.unnumbered}\nPatient #101 has a treatment initiation lag of 60 days and dies on Day 500. We split this patient's record into two lines:\n\n| Patient ID | Start (Day) | Stop (Day) | Status (Event) | Treatment ($Z$) |\n| :--- | :--- | :--- | :--- | :--- |\n| #101 | 0 | 60 | 0 (Alive) | 0 (Unexposed) |\n| #101 | 60 | 500 | 1 (Death) | 1 (Exposed) |\n\nAt Day 60, the patient's treatment status switches from unexposed to exposed. The patient is not removed from follow-up; instead, their contribution to the risk set is updated from untreated person-time to treated person-time.\n\n### Landmark vs. Time-Dependent Cox\n\n| Dimension | Time-dependent Cox | Landmark Analysis |\n| :--- | :--- | :--- |\n| **Data Retention** | Retains all patients and events from Day 0. | Discards patients/events prior to Landmark $T_L$. |\n| **Causal Question** | Causal effect starting from Day 0. | Conditional effect given survival to $T_L$. |\n| **Early Toxicity** | Captures early adverse event signals. | Masked if events occur before $T_L$. |\n| **HTA Audit Preference** | Preferred for primary analysis. | Used primarily as a sensitivity analysis. |\n\n## Cloning, Censoring, and IPCW in Target Trial Emulation\n\nTime-dependent Cox models are useful for auditing whether delayed treatment initiation has created immortal time bias. However, when the target trial estimand is defined as a comparison of **treatment strategies**—for example, \"initiate Drug X within 90 days of diagnosis\" versus \"do not initiate Drug X within 90 days\"—a trial-emulation analysis often requires **cloning, artificial censoring, and inverse probability of censoring weighting (IPCW)**.\n\n### Why Artificial Censoring Creates Bias\n\nIn a cloned analysis, each patient is copied into every treatment strategy at $T_0$:\n\n- One clone is assigned to the \"initiate within grace period\" strategy.\n- One clone is assigned to the \"do not initiate within grace period\" strategy.\n\nEach clone is followed from the same $T_0$. If the patient's observed behavior becomes incompatible with a clone's assigned strategy, that clone is artificially censored. For example, if the \"no treatment\" clone initiates Drug X on Day 20, that clone is censored on Day 20.\n\nThis artificial censoring is not necessarily random. Patients who start treatment early may differ systematically from patients who do not start treatment, and patients who remain compatible with a strategy may no longer represent the original target population. IPCW is used to reduce this selection bias.\n\n### IPCW Intuition\n\nThe \"C\" in IPCW stands for **censoring**. The core idea is to weight each remaining uncensored clone by the inverse of its probability of remaining uncensored:\n\n$$\nw_i(t) = \\frac{1}{P(C_i(t)=0 \\mid L_i)}\n$$\n\nwhere $C_i(t)=0$ means clone $i$ remains uncensored at time $t$, and $L_i$ represents baseline or time-updated covariate history.\n\nThe intuition is simple: if a type of patient is highly likely to be censored, but one such patient remains uncensored, that patient receives more weight because they represent similar patients who were censored.\n\n### Stabilized Weights\n\nIn practice, stabilized weights are often preferred because they reduce variance:\n\n$$\nSW_i(t) =\n\\frac{P(C_i(t)=0 \\mid A_i)}\n{P(C_i(t)=0 \\mid A_i, L_i)}\n$$\n\nThe denominator models censoring using strategy assignment and prognostic covariates. The numerator uses a simpler model, often including strategy assignment only. Extreme weights should be inspected and, if necessary, truncated using a pre-specified rule.\n\n### HTA Audit Checks\n\nFor an HTA-facing analysis, IPCW should not be presented as a black box. The submission should document:\n\n- the protocol rule that triggers artificial censoring;\n- the censoring model covariates and timing;\n- the distribution of stabilized weights;\n- any truncation threshold and its sensitivity analysis;\n- whether positivity is plausible across clinically relevant subgroups.\n\n## R Simulation: Validation of Estimators\n\nWe simulate a cohort of 500 patients where treatment initiation is delayed due to an administrative \"Approval Lag.\"\n\n### Simulating the Cohort and Biased Analysis\n\nWe simulate a true treatment Hazard Ratio of **0.70** (30% risk reduction). Age and ECOG status act as baseline confounders.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(survival)\nlibrary(EValue)\nset.seed(42)\nn <- 500\n\n# Helper function to render Cox model summaries as kable tables\nshow_cox <- function(fit, caption) {\n  sum_fit <- summary(fit)\n  coefs <- sum_fit$coefficients\n  cis <- sum_fit$conf.int\n  se_col <- if (\"robust se\" %in% colnames(coefs)) \"robust se\" else \"se(coef)\"\n  z_col <- if (\"z\" %in% colnames(coefs)) \"z\" else colnames(coefs)[4]\n  tbl <- data.frame(\n    Covariate = rownames(coefs),\n    `Hazard Ratio` = round(coefs[, \"exp(coef)\"], 4),\n    `Log HR (coef)` = round(coefs[, \"coef\"], 4),\n    `Std Error` = round(coefs[, se_col], 4),\n    `z-value` = round(coefs[, z_col], 3),\n    `p-value` = format.pval(coefs[, \"Pr(>|z|)\"], digits = 4),\n    `95% LCL` = round(cis[, 3], 4),\n    `95% UCL` = round(cis[, 4], 4),\n    check.names = FALSE\n  )\n  knitr::kable(tbl, caption = caption, align = \"lrrrrrrr\")\n}\n\n# 1. Simulate Baseline Confounders\nage <- rnorm(n, mean = 60, sd = 10)\necog <- rbinom(n, 1, 0.4)\n\n# 2. Simulate Treatment Selection (Confounding by Indication)\n# Sicker (ECOG=1) and older patients are more likely to receive treatment\nps_prob <- plogis(-1.5 + 0.02 * age + 0.5 * ecog)\nz_treatment <- rbinom(n, 1, ps_prob)\n\n# For those treated, add a random initiation delay between 30 and 120 days\nt_init <- ifelse(z_treatment == 1, runif(n, 30, 120), Inf)\n\n# 3. Simulate Survival Times (True treatment HR = 0.70)\ntrue_hr <- 0.70\nlambda_base <- 0.001 * exp(0.02 * age + 0.5 * ecog)\n\nu <- runif(n)\nlog_u <- -log(u)\n\nt_event <- numeric(n)\nfor(i in 1:n) {\n  l0 <- lambda_base[i]\n  l1 <- l0 * true_hr\n  t_tr <- t_init[i]\n  \n  if (log_u[i] <= l0 * t_tr) {\n    t_event[i] <- log_u[i] / l0\n  } else {\n    t_event[i] <- t_tr + (log_u[i] - l0 * t_tr) / l1\n  }\n}\n\n# Censoring between 150 and 730 days\nt_censor <- runif(n, 150, 730)\ntime <- pmin(t_event, t_censor)\nevent <- as.integer(t_event <= t_censor)\n\ndf <- data.frame(id = 1:n, age, ecog, z_treatment, t_init, time, event)\n\n# Determine treatment status based on actual follow-up (Biased approach)\ndf$ever_treated <- ifelse(df$t_init < df$time, 1, 0)\n\n# --- Biased Analysis: Static Cox Model ---\nfit_biased <- coxph(Surv(time, event) ~ ever_treated + age + ecog, data = df)\nshow_cox(fit_biased, \"Biased Static Cox Proportional Hazards Model Results (Immortal Time Unadjusted)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Biased Static Cox Proportional Hazards Model Results (Immortal Time Unadjusted)\n\n|             |Covariate    | Hazard Ratio| Log HR (coef)| Std Error| z-value|   p-value| 95% LCL| 95% UCL|\n|:------------|:------------|------------:|-------------:|---------:|-------:|---------:|-------:|-------:|\n|ever_treated |ever_treated |       0.4062|       -0.9008|    0.1138|  -7.915| 2.468e-15|  0.3250|  0.5077|\n|age          |age          |       1.0219|        0.0216|    0.0056|   3.853| 0.0001168|  1.0107|  1.0332|\n|ecog         |ecog         |       1.9562|        0.6710|    0.1071|   6.264| 3.757e-10|  1.5857|  2.4132|\n\n\n:::\n:::\n\n\nThe biased static Cox model overestimates drug efficacy due to the unadjusted immortal time.\n\n### Method 1: Landmark Analysis (Day 90)\n\nWe apply Landmark Analysis at Day 90:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_landmark <- 90\n\n# Exclude patients who died or were censored before Day 90\ndf_landmark <- df[df$time > t_landmark, ]\n\n# Classify status at Landmark\ndf_landmark$treated_at_landmark <- ifelse(df_landmark$t_init <= t_landmark, 1, 0)\n\n# Shift time\ndf_landmark$time_shifted <- df_landmark$time - t_landmark\n\nfit_landmark <- coxph(Surv(time_shifted, event) ~ treated_at_landmark + age + ecog, data = df_landmark)\nshow_cox(fit_landmark, \"Landmark Analysis (Day 90) Cox Proportional Hazards Model Results\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Landmark Analysis (Day 90) Cox Proportional Hazards Model Results\n\n|                    |Covariate           | Hazard Ratio| Log HR (coef)| Std Error| z-value|  p-value| 95% LCL| 95% UCL|\n|:-------------------|:-------------------|------------:|-------------:|---------:|-------:|--------:|-------:|-------:|\n|treated_at_landmark |treated_at_landmark |       0.7879|       -0.2384|    0.1482|  -1.608| 0.107855|  0.5893|  1.0536|\n|age                 |age                 |       1.0212|        0.0210|    0.0074|   2.840| 0.004517|  1.0065|  1.0361|\n|ecog                |ecog                |       2.1712|        0.7753|    0.1415|   5.477| 4.32e-08|  1.6452|  2.8653|\n\n\n:::\n:::\n\n\n### Method 2: Time-Varying Cox Model\n\nWe restructure the dataset into a counting process format using `tmerge()` and fit the time-varying Cox model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Initialize dataset with the primary event time\ndf_tv <- tmerge(df, df, id = id, event = event(time, event))\n\n# 2. Merge the time-dependent treatment initiation event\ndf_tv <- tmerge(df_tv, df, id = id, treatment_status = tdc(t_init))\n\n# Display the split intervals for Patient ID 1 to 3 in table format\nknitr::kable(\n  head(df_tv[df_tv$id %in% 1:3, c(\"id\", \"tstart\", \"tstop\", \"event\", \"treatment_status\")]),\n  caption = \"Restructured Counting Process Intervals (Patient ID 1-3)\",\n  align = \"c\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Restructured Counting Process Intervals (Patient ID 1-3)\n\n| id |  tstart   |   tstop   | event | treatment_status |\n|:--:|:---------:|:---------:|:-----:|:----------------:|\n| 1  |  0.00000  | 119.09690 |   0   |        0         |\n| 1  | 119.09690 | 308.79962 |   0   |        1         |\n| 2  |  0.00000  | 23.38370  |   1   |        0         |\n| 3  |  0.00000  | 92.99129  |   0   |        0         |\n| 3  | 92.99129  | 215.66793 |   1   |        1         |\n\n\n:::\n:::\n\n\nAs shown, if a patient receives treatment at a delayed time, their follow-up is split:\n\n- **Interval 1 `[0, t_init]`**: `treatment_status = 0` (contributes person-time to the control risk set).\n- **Interval 2 `[t_init, time]`**: `treatment_status = 1` (contributes person-time to the treated risk set after the first infusion).\n\nWe fit the Cox model on the split intervals:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the time-varying Cox model\nfit_tv <- coxph(Surv(tstart, tstop, event) ~ treatment_status + age + ecog, data = df_tv)\nshow_cox(fit_tv, \"Time-Varying Cox Proportional Hazards Model Results (Immortal Time Corrected)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Time-Varying Cox Proportional Hazards Model Results (Immortal Time Corrected)\n\n|                 |Covariate        | Hazard Ratio| Log HR (coef)| Std Error| z-value|   p-value| 95% LCL| 95% UCL|\n|:----------------|:----------------|------------:|-------------:|---------:|-------:|---------:|-------:|-------:|\n|treatment_status |treatment_status |       0.6930|       -0.3668|    0.1257|  -2.918| 0.0035197|  0.5417|  0.8865|\n|age              |age              |       1.0188|        0.0187|    0.0056|   3.350| 0.0008068|  1.0078|  1.0300|\n|ecog             |ecog             |       1.8597|        0.6204|    0.1070|   5.799| 6.658e-09|  1.5079|  2.2935|\n\n\n:::\n:::\n\n\nThe time-varying Cox model successfully recovers the true treatment effect ($HR = 0.70$) without discarding data.\n\n### Method 3: Cloning-Censoring-IPCW Analysis\n\nWe now emulate a strategy-level target trial with a 90-day grace period:\n\n- **Strategy 1**: initiate Drug X within 90 days of diagnosis.\n- **Strategy 0**: do not initiate Drug X within 90 days of diagnosis.\n\nEach patient is cloned into both strategies. A clone is artificially censored when the observed treatment path becomes incompatible with its assigned strategy.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrace_period <- 90\n\n# 1. Clone each patient into both treatment strategies\ndf_clone <- rbind(\n  transform(df, strategy = 1, strategy_label = \"Initiate within 90 days\"),\n  transform(df, strategy = 0, strategy_label = \"No initiation within 90 days\")\n)\n\n# 2. Define artificial censoring rules\ndf_clone$artificial_censor_time <- Inf\n\n# Strategy 1 violation: no treatment initiation by the end of the grace period\ndf_clone$artificial_censor_time[\n  df_clone$strategy == 1 &\n    df_clone$t_init > grace_period &\n    df_clone$time > grace_period\n] <- grace_period\n\n# Strategy 0 violation: treatment initiation during the grace period\ndf_clone$artificial_censor_time[\n  df_clone$strategy == 0 &\n    df_clone$t_init <= grace_period &\n    df_clone$t_init < df_clone$time\n] <- df_clone$t_init[\n  df_clone$strategy == 0 &\n    df_clone$t_init <= grace_period &\n    df_clone$t_init < df_clone$time\n]\n\n# 3. Observed follow-up under each assigned strategy\ndf_clone$obs_time <- pmin(df_clone$time, df_clone$artificial_censor_time)\ndf_clone$outcome_event <- as.integer(df_clone$event == 1 & df_clone$time <= df_clone$artificial_censor_time)\ndf_clone$artificial_censored <- as.integer(df_clone$artificial_censor_time < df_clone$time)\ndf_clone$uncensored <- 1 - df_clone$artificial_censored\n\nknitr::kable(\n  head(df_clone[, c(\"id\", \"strategy_label\", \"time\", \"event\", \"t_init\", \"obs_time\", \"outcome_event\", \"artificial_censored\")], 8),\n  caption = \"Cloned Target Trial Dataset with Artificial Censoring Rules\",\n  align = \"c\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Cloned Target Trial Dataset with Artificial Censoring Rules\n\n| id |     strategy_label      |   time    | event |  t_init   | obs_time | outcome_event | artificial_censored |\n|:--:|:-----------------------:|:---------:|:-----:|:---------:|:--------:|:-------------:|:-------------------:|\n| 1  | Initiate within 90 days | 308.79962 |   0   | 119.09690 | 90.00000 |       0       |          1          |\n| 2  | Initiate within 90 days | 23.38370  |   1   | 69.46443  | 23.38370 |       1       |          0          |\n| 3  | Initiate within 90 days | 215.66793 |   1   | 92.99129  | 90.00000 |       0       |          1          |\n| 4  | Initiate within 90 days | 289.21538 |   1   | 110.01693 | 90.00000 |       0       |          1          |\n| 5  | Initiate within 90 days | 11.00879  |   1   |    Inf    | 11.00879 |       1       |          0          |\n| 6  | Initiate within 90 days | 236.96021 |   1   | 96.09793  | 90.00000 |       0       |          1          |\n| 7  | Initiate within 90 days | 241.13736 |   1   |    Inf    | 90.00000 |       0       |          1          |\n| 8  | Initiate within 90 days | 85.79655  |   1   | 105.85904 | 85.79655 |       1       |          0          |\n\n\n:::\n:::\n\n\nNext, we estimate stabilized IPCW. This is a simplified subject-level implementation for demonstration; production analyses commonly estimate censoring probabilities over time using discrete-time pooled logistic models or start-stop data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 4. Estimate stabilized inverse probability of censoring weights\ncensor_den <- glm(uncensored ~ strategy + age + ecog, family = binomial(), data = df_clone)\ncensor_num <- glm(uncensored ~ strategy, family = binomial(), data = df_clone)\n\ndf_clone$p_uncens_den <- predict(censor_den, type = \"response\")\ndf_clone$p_uncens_num <- predict(censor_num, type = \"response\")\ndf_clone$ipcw <- df_clone$p_uncens_num / df_clone$p_uncens_den\n\nweight_summary <- data.frame(\n  Metric = c(\"Minimum\", \"1st Quartile\", \"Median\", \"Mean\", \"3rd Quartile\", \"Maximum\"),\n  Stabilized_IPCW = as.numeric(summary(df_clone$ipcw))\n)\n\nknitr::kable(\n  weight_summary,\n  caption = \"Stabilized IPCW Distribution\",\n  digits = 3,\n  align = \"lr\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Stabilized IPCW Distribution\n\n|Metric       | Stabilized_IPCW|\n|:------------|---------------:|\n|Minimum      |           0.865|\n|1st Quartile |           0.964|\n|Median       |           1.011|\n|Mean         |           1.003|\n|3rd Quartile |           1.038|\n|Maximum      |           1.160|\n\n\n:::\n:::\n\n\nFinally, we fit a weighted Cox model comparing the two grace-period strategies. The `cluster(id)` term accounts for the fact that each original patient contributes two cloned records.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_ipcw <- coxph(\n  Surv(obs_time, outcome_event) ~ strategy + age + ecog + cluster(id),\n  data = df_clone,\n  weights = ipcw\n)\n\nshow_cox(fit_ipcw, \"Cloning-Censoring-IPCW Cox Model Results\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Cloning-Censoring-IPCW Cox Model Results\n\n|         |Covariate | Hazard Ratio| Log HR (coef)| Std Error| z-value|   p-value| 95% LCL| 95% UCL|\n|:--------|:---------|------------:|-------------:|---------:|-------:|---------:|-------:|-------:|\n|strategy |strategy  |       0.9042|       -0.1007|    0.0584|  -1.724|  0.084746|  0.8064|  1.0139|\n|age      |age       |       1.0169|        0.0168|    0.0058|   2.893|  0.003818|  1.0054|  1.0285|\n|ecog     |ecog      |       1.7407|        0.5543|    0.1118|   4.959| 7.071e-07|  1.3983|  2.1670|\n\n\n:::\n:::\n\n\n## Causal Evidence Reconciliation\n\nThe table below summarizes the estimates across all four models compared to the true parameter.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract statistics\nhr_biased  <- exp(coef(fit_biased)[\"ever_treated\"])\nse_biased  <- summary(fit_biased)$coefficients[\"ever_treated\", \"se(coef)\"]\n\nhr_land    <- exp(coef(fit_landmark)[\"treated_at_landmark\"])\nse_land    <- summary(fit_landmark)$coefficients[\"treated_at_landmark\", \"se(coef)\"]\n\nhr_tv      <- exp(coef(fit_tv)[\"treatment_status\"])\nse_tv      <- summary(fit_tv)$coefficients[\"treatment_status\", \"se(coef)\"]\n\nhr_ipcw    <- exp(coef(fit_ipcw)[\"strategy\"])\nse_ipcw    <- summary(fit_ipcw)$coefficients[\"strategy\", \"robust se\"]\n\n# Combine into reconciliation matrix\nreconciliation_tbl <- data.frame(\n  Estimator = c(\"Ground Truth (True Parameter)\", \"Biased Model (Static Baseline)\", \"Landmark Analysis (Day 90)\", \"Time-Varying Cox Model\", \"Cloning-Censoring-IPCW\"),\n  \"Hazard Ratio (HR)\" = c(true_hr, hr_biased, hr_land, hr_tv, hr_ipcw),\n  \"Standard Error\" = c(NA, se_biased, se_land, se_tv, se_ipcw),\n  \"95% LCL\" = c(NA, exp(confint(fit_biased)[\"ever_treated\", 1]), exp(confint(fit_landmark)[\"treated_at_landmark\", 1]), exp(confint(fit_tv)[\"treatment_status\", 1]), exp(confint(fit_ipcw)[\"strategy\", 1])),\n  \"95% UCL\" = c(NA, exp(confint(fit_biased)[\"ever_treated\", 2]), exp(confint(fit_landmark)[\"treated_at_landmark\", 2]), exp(confint(fit_tv)[\"treatment_status\", 2]), exp(confint(fit_ipcw)[\"strategy\", 2])),\n  \"Bias vs. Truth (Log HR)\" = c(0.0000, coef(fit_biased)[\"ever_treated\"] - log(true_hr), coef(fit_landmark)[\"treated_at_landmark\"] - log(true_hr), coef(fit_tv)[\"treatment_status\"] - log(true_hr), coef(fit_ipcw)[\"strategy\"] - log(true_hr)),\n  check.names = FALSE\n)\n\n# Format values for display\nreconciliation_tbl[, 2:6] <- round(reconciliation_tbl[, 2:6], 4)\nreconciliation_tbl[is.na(reconciliation_tbl)] <- \"N/A\"\n\nknitr::kable(reconciliation_tbl, caption = \"Survival Parameter Reconciliation Across Estimators\", align = \"lrrrrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Survival Parameter Reconciliation Across Estimators\n\n|                    |Estimator                      | Hazard Ratio (HR)| Standard Error| 95% LCL| 95% UCL| Bias vs. Truth (Log HR)|\n|:-------------------|:------------------------------|-----------------:|--------------:|-------:|-------:|-----------------------:|\n|                    |Ground Truth (True Parameter)  |            0.7000|            N/A|     N/A|     N/A|                  0.0000|\n|ever_treated        |Biased Model (Static Baseline) |            0.4062|         0.1138|   0.325|  0.5077|                 -0.5442|\n|treated_at_landmark |Landmark Analysis (Day 90)     |            0.7879|         0.1482|  0.5893|  1.0536|                  0.1183|\n|treatment_status    |Time-Varying Cox Model         |            0.6930|         0.1257|  0.5417|  0.8865|                 -0.0101|\n|strategy            |Cloning-Censoring-IPCW         |            0.9042|         0.0584|  0.8064|  1.0139|                  0.2560|\n\n\n:::\n:::\n\n\n## Quantitative Bias Analysis: E-Value Sensitivity Analysis\n\nWhen submitting RWE to HTA bodies, we must audit the robustness of our findings against unmeasured confounding. We compute the E-value for the time-varying Hazard Ratio ($HR = 0.693$).\n\n### E-Value Math & Formula Setup\n\nThe E-value is defined as the minimum strength of association on the risk ratio scale that an unmeasured confounder ($U$) must have with both:\n1. The treatment assignment ($Z$)\n2. The clinical outcome ($Y$)\n\nto fully explain away the observed treatment-outcome association.\n\nThe formula depends on the cumulative incidence of the outcome:\n\n1. **Rare Outcome Assumption** (cumulative incidence < 15%):\n\n   The Hazard Ratio approximates the Relative Risk ($RR \\approx HR$). For protective effects ($HR < 1.0$), we first invert the HR ($HR^* = 1 / HR$) to get a value $> 1.0$:\n   $$\\text{E-value} = HR^* + \\sqrt{HR^* \\cdot (HR^* - 1)}$$\n\n2. **Common Outcome Correction** (cumulative incidence > 15%):\n\n   The rare outcome assumption is violated, and we must apply the square root approximation:\n   $$RR \\approx \\sqrt{HR}$$\n   The corresponding E-value is calculated as:\n   $$\\text{E-value} = \\sqrt{HR^*} + \\sqrt{\\sqrt{HR^*} \\cdot (\\sqrt{HR^*} - 1)}$$\n\nIn our cohort, $379$ out of $500$ patients ($75.8\\%$) experienced the event, meaning the outcome is common. We must apply the common outcome correction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Extract HR and confidence limits from the time-varying Cox model\nhr_est_val <- exp(coef(fit_tv)[\"treatment_status\"])\nhr_lcl_val <- exp(confint(fit_tv)[\"treatment_status\", 1])\nhr_ucl_val <- exp(confint(fit_tv)[\"treatment_status\", 2])\n\n# 2. Compute E-value (common outcome correction: rare = FALSE)\nev_survival <- evalues.HR(est = hr_est_val, lo = hr_lcl_val, hi = hr_ucl_val, rare = FALSE)\nev_survival_df <- as.data.frame(ev_survival)\n\n# 3. Format E-value table\nev_survival_tbl <- data.frame(\n  \"Metric / Parameter\" = c(\"Hazard Ratio (HR)\", \"E-value (Treatment Effect Bound)\"),\n  \"Point Estimate\" = c(sprintf(\"%.3f\", ev_survival_df[\"HR\", \"point\"]), sprintf(\"%.3f\", ev_survival_df[\"E-values\", \"point\"])),\n  \"95% CI Lower Bound\" = c(sprintf(\"%.3f\", ev_survival_df[\"HR\", \"lower\"]), sprintf(\"%.3f\", ev_survival_df[\"E-values\", \"lower\"])),\n  \"95% CI Upper Bound\" = c(sprintf(\"%.3f\", ev_survival_df[\"HR\", \"upper\"]), \"N/A\"),\n  check.names = FALSE\n)\n\nknitr::kable(ev_survival_tbl, caption = \"E-Value Analysis for Survival Sensitivity to Unmeasured Confounding\", align = \"lrrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: E-Value Analysis for Survival Sensitivity to Unmeasured Confounding\n\n|Metric / Parameter               | Point Estimate| 95% CI Lower Bound| 95% CI Upper Bound|\n|:--------------------------------|--------------:|------------------:|------------------:|\n|Hazard Ratio (HR)                |             NA|                 NA|                 NA|\n|E-value (Treatment Effect Bound) |          1.899|                 NA|                N/A|\n\n\n:::\n:::\n\n\nThe point estimate E-value of **1.899** means that an unmeasured confounder would need to increase the probability of treatment assignment by **1.899-fold** and increase the hazard of death by **1.899-fold** to fully explain away the observed survival benefit.\n\n### Algebraic Derivation of the E-Value (VanderWeele & Ding 2016)\n\nTo understand the mathematical strength of the E-value, we trace its algebraic derivation from the **Bias Factor** model.\n\nLet $U$ be a binary unmeasured confounder. The observed relative risk $RR_{obs}$ is related to the true relative risk $RR_{true}$ by:\n$$RR_{obs} = RR_{true} \\times \\text{Bias}$$\n\nwhere the Bias Factor is defined as:\n$$\\text{Bias} = \\frac{RR_{ZU} \\times RR_{UY}}{RR_{ZU} + RR_{UY} - 1}$$\n\nHere:\n\n- $RR_{ZU}$ is the risk ratio associating the treatment $Z$ with the unmeasured confounder $U$.\n- $RR_{UY}$ is the risk ratio associating the unmeasured confounder $U$ with the outcome $Y$.\n\nTo explain away an observed effect (i.e., to show that the true effect is null, $RR_{true} = 1.0$), the Bias Factor must equal or exceed the observed relative risk:\n$$\\text{Bias} \\ge RR_{obs}$$\n\nTo find the minimum strength of association required for both relationships, we define a single threshold $E = RR_{ZU} = RR_{UY}$. Substituting $E$ into the Bias formula:\n$$\\frac{E^2}{2E - 1} \\ge RR_{obs}$$\n\nThis can be rearranged into a quadratic inequality:\n$$E^2 - 2RR_{obs} \\cdot E + RR_{obs} \\ge 0$$\n\nSolving the quadratic equation $E^2 - 2RR_{obs} \\cdot E + RR_{obs} = 0$ using the quadratic formula:\n$$E = \\frac{2RR_{obs} \\pm \\sqrt{4RR_{obs}^2 - 4RR_{obs}}}{2} = RR_{obs} + \\sqrt{RR_{obs}(RR_{obs} - 1)}$$\n\nThis is the exact mathematical derivation of the E-value formula. It represents the absolute minimum joint relationship required for an unmeasured confounder to explain away the observed treatment effect.\n\n## HTA Audit & Interview Guide\n\n### Interview Audit Checklist\n\nWhen auditing a manufacturer's RWE survival submission (or preparing for an HTA interview), follow these three key checks:\n\n1. **Zero-time Alignment Check**:\n\n   - *Question*: Identify the exact calendar date of $T_0$ for both cohorts. Is $T_0$ defined by the clinical event (diagnosis) or the administrative event (first prescription)?\n   - *Audit Rule*: Follow-up must start for both cohorts when they meet the eligibility criteria. If the treated group follow-up starts at drug initiation and controls start at diagnosis, the analysis is invalid.\n\n2. **Immortal Time Bias Screen**:\n\n   - *Question*: Check the initial segment of the Kaplan-Meier curve. Does the treated arm show a \"zero-risk\" flat line at the start of follow-up?\n   - *Audit Rule*: A flat line on the treatment curve indicates that patients who died early were excluded from the treated group, indicating Immortal Time Bias.\n\n3. **Statistical Correction Audit**:\n\n   - *Question*: If a treatment initiation lag exists, was it addressed using a time-varying covariate or a Landmark approach?\n   - *Audit Rule*: Standard Cox models using a static baseline treatment indicator are statistically invalid in the presence of treatment initiation delays.\n\n### Expert HTA Articulation\n\nUse the following professional statements to articulate survival analysis defense strategies during HTA reviews or interviews:\n\n- **Justifying Time-Varying Cox Models Over Static Models**:\n  > \"To prevent the introduction of lead-time and immortal time biases, we did not define treatment statically at baseline based on retrospective treatment status. Instead, we modeled treatment as a time-varying exposure using a counting process framework with start-stop intervals via the `tmerge` protocol. This ensures that the risk sets are updated dynamically at each event time, preventing the misattribution of waiting-period survival to the active drug's efficacy.\"\n\n- **Defending the Conditional Exchangeability Assumption**:\n  > \"Second, to maintain conditional exchangeability over time despite treatment delays, we utilized a cloning-and-censoring approach with IPCW, ensuring the counterfactual baseline characteristics remained balanced as the retrospective follow-up progressed.\"\n\n- **Empirically Validating the Positivity Assumption**:\n  > \"Finally, we empirically validated the positivity assumption by confirming that patients across all covariate strata in our HES data had a non-zero probability of receiving standard of care, preventing structurally empty cells in our propensity score distributions.\"\n\n- **Defending against Unmeasured Confounding via E-Values**:\n  > \"Although our real-world registry lacks smoking history, our E-value of 1.70 demonstrates that to nullify the observed survival benefit, an unmeasured confounder would need to increase both the likelihood of treatment and the hazard of death by at least 1.70-fold. This is larger than the hazard associated with major clinical indicators like age in our adjusted models, making it highly implausible that a missing confounder of this magnitude exists that is completely independent of the clinical variables adjusted for in our primary analysis.\"\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}