{
  "hash": "60eaeb3888a5a299d1e4cd043ca85a85",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multilevel Network Meta-Regression (ML-NMR)\"\ndescription: \"Resolving Ecological Bias in Population-Adjusted Indirect Comparisons\"\nauthor: \"Xiaoge Zhang\"\ndate: \"today\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    number-sections: true\n    embed-resources: true\n---\n\n## Executive Summary\n\nAs demonstrated in Chapter 07, **Simulated Treatment Comparison (STC)** suffers from a mathematical fatal flaw when dealing with non-linear clinical endpoints (such as survival or binary outcomes): **Ecological Bias**. Because $f(E[X]) \\neq E[f(X)]$ for a non-linear link function $f$, plugging aggregate means into a regression model will inevitably yield biased population-level predictions.\n\n**Multilevel Network Meta-Regression (ML-NMR)** was specifically invented to solve this exact problem. It represents the state-of-the-art methodology for Population-Adjusted Indirect Comparisons (PAIC) in Health Technology Assessment (HTA).\n\nInstead of plugging in aggregate means, ML-NMR performs **numerical integration** over the target population's covariate distribution (e.g., integrating over the age distribution). By projecting the individual-level non-linear relationship (from IPD) across the macro-level probability density function (PDF) of the AgD trial, ML-NMR successfully calculates $E[f(X)]$ without ecological bias.\n\nIn this chapter, we will:\n\n1.  Simulate a realistic scenario with IPD and AgD (assuming the binary outcome $y$ is **Complete Remission (CR)**).\n2.  Formulate the **Joint Likelihood** function.\n3.  Use numerical integration (Sobol sequences) to solve the ecological bias.\n4.  Run an ML-NMR using the industry-standard `multinma` package.\n\n------------------------------------------------------------------------\n\n## The Mock Scenario: Anchored PAIC\n\nImagine a connected network with three treatments:\n\n- **Treatment A (Quizartinib)**: We own the Individual Patient Data (IPD) from Trial 1 (A vs. Placebo).\n- **Treatment B (Midostaurin)**: We only have published Aggregate Data (AgD) from Trial 2 (B vs. Placebo).\n- **Endpoint**: Binary response $y_i$ (Responded = 1, Failed = 0). Modeled via Logistic Regression.\n- **Effect Modifier**: `age`. The treatment effect diminishes as patients get older.\n\nLet's generate the mock datasets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(multinma)\nlibrary(ggplot2)\nset.seed(2026)\n# ---------------------------------------------------------\n# 1. Generate IPD for Trial 1 (Our Trial: Quizartinib vs Placebo)\n# Outcome y represents Complete Remission (CR)\n# ---------------------------------------------------------\nn_ipd <- 600\nage_ipd <- rnorm(n_ipd, mean = 45, sd = 10) # Younger population\ntrt_ipd <- sample(c(\"Placebo\", \"Quizartinib\"), n_ipd, replace = TRUE)\n\n# Simulate logit probabilities:\nlogit_p_ipd <- -1.0 + # <1>\n    ifelse(trt_ipd == \"Quizartinib\", 2.5, 0) + # <2>\n    (-0.05 * (age_ipd - 45)) +\n    ifelse(trt_ipd == \"Quizartinib\", -0.04 * (age_ipd - 45), 0) # <3>\n\nprob_ipd <- 1 / (1 + exp(-logit_p_ipd))\ny_ipd <- rbinom(n_ipd, 1, prob_ipd)\n\nipd_data <- data.frame(\n    study = \"Trial 1\",\n    patient_id = 1:n_ipd,\n    trt = trt_ipd,\n    age = age_ipd,\n    y = y_ipd\n)\n\n# ---------------------------------------------------------\n# 2. Generate AgD for Trial 2 (Competitor: Midostaurin vs Placebo)\n# ---------------------------------------------------------\nn_agd_pbo <- 300\nn_agd_mido <- 300\nage_agd_pbo <- rnorm(n_agd_pbo, mean = 65, sd = 8) # <4>\nage_agd_mido <- rnorm(n_agd_mido, mean = 65, sd = 8)\n\n\nlogit_p_agd_pbo <- -1.5 + (-0.05 * (age_agd_pbo - 45)) # <5>\nprob_agd_pbo <- 1 / (1 + exp(-logit_p_agd_pbo))\nr_pbo <- sum(rbinom(n_agd_pbo, 1, prob_agd_pbo))\n\nlogit_p_agd_mido <- -1.5 + 2.2 + (-0.05 * (age_agd_mido - 45)) + (-0.04 * (age_agd_mido - 45)) # <6>\nprob_agd_mido <- 1 / (1 + exp(-logit_p_agd_mido))\nr_mido <- sum(rbinom(n_agd_mido, 1, prob_agd_mido))\n\nagd_data <- data.frame(\n    study = \"Trial 2\",\n    trt = c(\"Placebo\", \"Midostaurin\"),\n    r = c(r_pbo, r_mido),\n    n = c(n_agd_pbo, n_agd_mido),\n    age_mean = 65,\n    age_sd = 8\n)\n```\n:::\n\n\n1.  Base risk (Placebo) = -1.0\n2.  Effect of Quizartinib = +2.5\n3.  Age penalty = -0.05 per year above 45; Age\\*Quizartinib interaction (effect decay) = -0.04 per year above 45\n4.  Trial 2 is older (Mean Age = 65, SD = 8); We simulate the true underlying AgD data to get the counts, but we will ONLY use the counts.\n5.  Trial 2 Base risk (Placebo) might be different, let's say -1.5 (Study-specific intercept).\n6.  Midostaurin effect = +2.2; Same age penalties apply.\n\n## The Core Philosophy: Joint Likelihood ($L_{Joint}$)\n\nML-NMR works by constructing a **Joint Likelihood** that glues IPD and AgD together using shared parameters.\n\n### The Logistic Regression Equation\n\nFor any patient $i$ in study $k$: $$ \\text{logit}(P_{ik}) = \\ln (\\dfrac{P_{ik}}{1-P_{ik}}) = \\mu_k + \\beta_{age}\\text{Age}_i + \\beta_{trt_k}\\text{Trt}_i + \\beta_{age:trt}(\\text{Age}_i \\times \\text{Trt}_i) $$\n\n- $P_{ik}$ (Patient Probability): Can be explicitly derived by applying the inverse-logit transformation to the right-hand side. This value acts as the direct mathematical input for the IPD likelihood ($L_{IPD}$) below.\n- $\\mu_k$ (Study-Specific Intercepts): Accommodates unmeasured background risk differences between Trial 1 and Trial 2. It is the independent \"baseline floor\" for each trial.\n- $\\beta$ (Shared Parameters): The treatment effects ($\\beta_{trt}$) and the covariate modifiers ($\\beta_{age}, \\beta_{age:trt}$) are shared across the entire network. These act as the mathematical \"bridges\" that allow information to flow from the IPD trial to the AgD trial.\n\n### IPD Likelihood ($L_{IPD}$)\n\nFor the 300 patients in Trial 1, the likelihood is straightforward Bernoulli: $$ L_{IPD} = \\prod_i P_{i}^{y_i} (1 - P_{i})^{1 - y_i} $$ Because we have exact ages $x_i$, $P_i$ can be expressed exactly. Because we also have the binary response $y_i$, $L_{IPD}$ can be expressed exactly.\n\n### AgD Likelihood ($L_{AgD}$) & Numerical Integration\n\nFor Trial 2, we only have the total responders $R$ out of $N$. The expected probability for the group is $\\bar{P}_{AgD}$.\n\n**This is where STC failed.** STC assumed $\\bar{P}_{AgD} = \\text{inv\\_logit}(\\mu_2 + \\beta_{age}\\bar{X}_{age} + \\dots)$, which is WRONG, Ecological Fallacy.\n\n**ML-NMR** correctly defines it as an integral over the population's age distribution's density function $p(x)$: $$ \\bar{P}_{AgD} = \\int \\text{inv\\_logit}(\\mu_2 + \\beta_{age}x + \\dots) \\cdot p(x) \\, dx $$\n\nTo solve this analytically impossible integral, ML-NMR uses **Sobol sequences** to generate a set of representative \"virtual avatars\" (integration points) that match the mean and SD of the AgD trial. The integral is approximated by averaging the probabilities of these avatars: $$ \\bar{P}_{AgD} \\approx \\frac{1}{J} \\sum_{j=1}^{J} \\text{inv\\_logit}(\\mu_2 + \\beta_{age}x_j + \\dots) $$\n\n```{=html}\n<!-- Audit Point: Riemann vs. Monte Carlo Integration\nWhy did the probability density function p(x) disappear in the discrete summation?\nAn intuitive approach (Riemann Integration) would suggest laying out a fixed, evenly spaced grid of ages and multiplying each calculated probability by its corresponding PDF weight p(x_j). However, ML-NMR employs Quasi-Monte Carlo integration via Sobol sequences. \nBecause the J \"virtual avatars\" (the x_j points) are *sampled directly from* the underlying probability distribution p(x), the density weight is physically represented by the clustering of the avatars. For example, more avatars will naturally be generated around the mean age of 65 than at age 20. \nBy the Law of Large Numbers, the integral simplifies: \\int f(x) p(x) dx \\approx \\frac{1}{J} \\sum f(x_j) as long as x_j ~ p(x). Multiplying by p(x_j) again in the summation would incorrectly double-count the density weights.\n-->\n```\n\nThe final AgD likelihood is Binomial, anchoring the model to the published macro-data: $$ L_{AgD} = \\binom{N}{R} [\\bar{P}_{AgD}]^R [1 - \\bar{P}_{AgD}]^{N-R} $$\n\n```{=html}\n<!-- Audit Point: The \"Iron Tongs\" of the Binomial Likelihood\nWhy does ML-NMR require the raw counts (R, N) instead of just the percentage rate?\nBecause N determines the \"weight\" or statistical gravity of the evidence. A 40% survival rate derived from N=10 has massive variance, allowing the MCMC chain to wander. A 40% survival rate derived from N=1000 acts like iron tongs, forcing the macro average of the Sobol avatars (\\bar{P}_{AgD}) to strictly align with the real-world observation. This forces the underlying shared \\beta parameters into the correct alignment.\n-->\n```\n\n### The Total Audit Balance (Joint Likelihood)\n\n$$L_{Joint}(\\beta, \\mu) = L_{IPD}(\\mu_1, \\beta) \\times L_{AgD}(\\mu_2, \\beta)$$\n\nBecause $L_{IPD}$ and $L_{AgD}$ share the exact same treatment effect $\\beta$, the model is forced during optimization to find the mathematical equilibrium that best explains both the micro-level individual logic (IPD) and the macro-level summary bill (AgD).\n\n## R Implementation with `multinma`\n\nLet's build the ML-NMR model using the `multinma` package.\n\n### Network Construction and Integration Points\n\nFirst, we tell the model who the baseline comparator is, and we generate the Sobol integration points for the AgD trial.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add treatment classes to share interaction effects\nipd_data$class <- ifelse(ipd_data$trt == \"Placebo\", \"Placebo\", \"Active\")\nagd_data$class <- ifelse(agd_data$trt == \"Placebo\", \"Placebo\", \"Active\")\n\n# 1. Combine Network with classes\nnet <- combine_network(\n    set_ipd(ipd_data, study = study, trt = trt, r = y, trt_class = class),\n    set_agd_arm(agd_data, study = study, trt = trt, r = r, n = n, trt_class = class),\n    trt_ref = \"Placebo\"\n)\n\n# 2. Add Numerical Integration Points (Sobol Sequences)\nnet <- add_integration(net,\n    age = distr(qnorm, mean = age_mean, sd = age_sd),\n    n_int = 64\n) # 64 Sobol points\n```\n:::\n\n\n### Fitting the ML-NMR Model\n\nWe instruct Stan to fit a regression model including the interaction between treatment and age (`~ age * .trt`). We will use Fixed Effects (FE) for this sparse network.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 3. Fit ML-NMR (using a short chain for demonstration)\nfit_mlnmr <- nma(net,\n    trt_effects = \"fixed\",\n    regression = ~ age * .trt,\n    class_interactions = \"common\",\n    prior_intercept = normal(scale = 10),\n    prior_trt = normal(scale = 10),\n    prior_reg = normal(scale = 10),\n    iter = 2000,\n    warmup = 1000,\n    chains = 2,\n    refresh = 0\n)\n# Extract summary matrix from the underlying Stan fit for clean formatting\nfit_summary <- as.data.frame(rstan::summary(fit_mlnmr$stanfit)$summary)\n# Filter rows for key parameters and select desired columns\nrows_to_keep <- grep(\"^(d\\\\[|beta|mu\\\\[)\", rownames(fit_summary))\nclean_summary <- fit_summary[rows_to_keep, c(\"mean\", \"sd\", \"2.5%\", \"50%\", \"97.5%\", \"n_eff\", \"Rhat\")]\nprint(round(clean_summary, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                           mean   sd  2.5%   50% 97.5%   n_eff Rhat\nmu[Trial 1]               -1.46 0.21 -1.89 -1.45 -1.07  884.66    1\nmu[Trial 2]               -2.85 0.31 -3.46 -2.83 -2.27 1086.65    1\nbeta[age]                 -0.04 0.01 -0.07 -0.04 -0.02  925.10    1\nbeta[age:.trtclassActive] -0.05 0.02 -0.10 -0.05 -0.01  791.64    1\nd[Midostaurin]             2.66 0.37  1.95  2.66  3.40 1008.97    1\nd[Quizartinib]             1.99 0.28  1.46  1.99  2.54  855.93    1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n### Counterfactual Prediction (The Infilling Logic)\n\n### How the Adjustment from 55.08 to 45 Works\n\nSince `multinma` automatically centers the covariate (Age) at the overall network mean ($c \\approx 55.08$), the estimated intercepts ($\\mu$) and main treatment effects ($d$) are specific to a 55.08-year-old patient. To compare them with our true simulation values (which were defined at Age 45), we must algebraically shift them back.\n\nThe specific formulas are derived from the linear predictor equation: $$\\text{logit}(p) = \\mu + \\beta_{age} \\cdot (\\text{Age} - c) + d_{trt} \\cdot \\text{trt} + \\beta_{age:trt} \\cdot (\\text{Age} - c) \\cdot \\text{trt}$$\n\nTo find the parameters at $\\text{Age} = 45$:\n\n1.  **Adjusted Intercept (**$\\mu'$): $$\\mu'_{k} = \\mu_k + \\beta_{age} \\cdot (45 - c)$$ *The intercept shifts by the age effect over the distance of \\~10.08 years.*\n\n2.  **Adjusted Treatment Effect (**$d'_{trt}$): $$d'_{trt} = d_{trt} + \\beta_{age:trt} \\cdot (45 - c)$$ *The main treatment effect shifts by the interaction effect over the same distance.*\n\n3.  **Slopes (**$\\beta_{age}, \\beta_{age:trt}$): These are rates of change per year and are invariant to the centering point. Therefore, no adjustment is needed.\n\nHere is the comparison table (dynamically extracted from the model):\n\n| Parameter | Estimated Value (at 55.08) | Adjusted Value (at 45) | True Value (at 45) |\n|------------------|------------------|------------------|------------------|\n| $\\mu_1$ (Trial 1 Baseline) | -1.46 | -1.02 | -1.0 |\n| $\\mu_2$ (Trial 2 Baseline) | -2.85 | -2.42 | -1.5 |\n| $\\beta_{age}$ (Age Effect) | -0.04 | -0.04 | -0.05 |\n| $\\beta_{Quiz}$ (Quizartinib Effect) | 1.99 | 2.56 | 2.5 |\n| $\\beta_{Mido}$ (Midostaurin Effect) | 2.66 | 3.22 | 2.2 |\n| $\\beta_{age:trt}$ (Shared Interaction) | -0.05 | -0.05 | -0.04 |\n\n::: callout-warning\n### Methodological Insight: Ecological Fallacy & Collinearity in AgD\n\nEven after doubling the sample size, the model failed to accurately recover the true values of $\\mu_2$ (-1.5) and $\\beta_{Mido}$ (2.2). Instead, it estimated $\\mu_2 \\approx -2.42$ and $\\beta_{Mido} \\approx 3.22$.\n\nNotice that their sum is almost perfect ($-2.42 + 3.22 = 0.8$ vs. the true $-1.5 + 2.2 = 0.7$), but the individual decomposition is incorrect. This is because Trial 2 only has Aggregate Data (AgD). No matter how much we increase the sample size (from 300 to 3000 or more), the model only ever sees two macro metrics in Trial 2: the overall event rate for Placebo and the overall event rate for Midostaurin.\n\nTrying to disentangle \"baseline risk\" from \"treatment effect\" using only two data points naturally introduces severe **Collinearity**. This is the famous **Ecological Fallacy**: inferring individual-level effects from group-level data, where parameters cannot be fully decoupled without individual-level variance.\n:::\n\n**The ultimate goal of PAIC is to answer:** *What would the competitor's drug (Midostaurin) have achieved if it were given to a specific patient in our Trial 1?*\n\nLet's perform the **Counterfactual Projection** for a hypothetical 35-year-old patient from Trial 1 receiving Midostaurin. We will use the **Adjusted Parameters (at Age 45)** for a more intuitive calculation:\n\n1.  **Select the Arena (Baseline)**: We project onto Trial 1's adjusted baseline at age 45, so $\\mu'_1 = -1.02$.\n2.  **Calculate the Linear Predictor (**$\\eta$): $$\\begin{aligned}\\eta_{35, Mido} &= \\mu'_1 + (\\beta_{age} \\times (35 - 45)) + d'_{Mido} + (\\beta_{age:trt} \\times (35 - 45)) \\\\ &= -1.02 + (-0.04 \\times -10) + 3.22 + (-0.05 \\times -10) \\\\ &= -1.02 + 0.42 + 3.22 + 0.55 \\\\ &= 3.17\\end{aligned}$$\n3.  **Convert to Probability (Inverse Logit)**: $$P = \\frac{1}{1 + e^{-3.17}} \\approx \\mathbf{96\\%}$$\n\nContrast this with a 70-year-old patient from Trial 2 (where the original Midostaurin data came from), also using adjusted parameters at age 45:\n\n$$\\begin{aligned}\\eta_{70, Mido} &= \\mu'_2 + (\\beta_{age} \\times (70 - 45)) + d'_{Mido} + (\\beta_{age:trt} \\times (70 - 45)) \\\\ &= -2.42 + (-0.04 \\times 25) + 3.22 + (-0.05 \\times 25) \\\\ &= -2.42 + -1.05 + 3.22 + -1.37 \\\\ &= -1.61\\end{aligned}$$\n\n$$P = \\frac{1}{1 + e^{-(-1.61)}} \\approx \\mathbf{16.6\\%}$$\n\n**This is the true power of ML-NMR:** By decomposing the effects, ML-NMR mathematically \"transplants\" Midostaurin into a younger body (35 years old), revealing a potential **96%** Complete Remission (CR) rate. We then compare this against Quizartinib's performance *in the exact same patient profile*. This guarantees a rigorous, apples-to-apples comparison.\n\nTo calculate this in `multinma`, the `relative_effects` function performs this exact integration over the target age distribution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 4. Extract Relative Effects specifically for the Trial 1 population\nreleff_trial1 <- relative_effects(fit_mlnmr,\n    newdata = data.frame(age = 45),\n    all_contrasts = TRUE\n)\n\n# Convert to data frame and select key columns including diagnostics\nreleff_df <- as.data.frame(releff_trial1)\n# Combine Treatment B and Treatment A into one column\nreleff_df$Comparison <- paste(releff_df$.trtb, \"vs\", releff_df$.trta)\n# Abbreviate names to prevent line wrapping\nreleff_df$Comparison <- gsub(\"Quizartinib\", \"Quiz\", releff_df$Comparison)\nreleff_df$Comparison <- gsub(\"Midostaurin\", \"Mido\", releff_df$Comparison)\nreleff_df$Comparison <- gsub(\"Placebo\", \"Pbo\", releff_df$Comparison)\n# Select key columns including diagnostics\nreleff_df <- releff_df[, c(\"Comparison\", \"mean\", \"sd\", \"2.5%\", \"97.5%\", \"Rhat\", \"Bulk_ESS\")]\n# Rename columns to be concise and fit on one line\nnames(releff_df) <- c(\"Comparison\", \"Mean\", \"SD\", \"2.5%\", \"97.5%\", \"Rhat\", \"ESS\")\nprint(releff_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Comparison      Mean        SD      2.5%     97.5%     Rhat       ESS\n1  Mido vs Pbo  3.215970 0.5176390  2.230412 4.2290039 1.005827  862.4296\n2  Quiz vs Pbo  2.551674 0.2133233  2.124642 2.9585115 1.002519 1732.1302\n3 Quiz vs Mido -0.664296 0.5243988 -1.683855 0.3569393 1.006067  828.1780\n```\n\n\n:::\n:::\n\n\n### Interpreting the Results (The 3rd Row)\n\nIn the 3rd row of the table above (**`Quiz vs Mido`**), we are answering the counterfactual question: *What if the patients in our Trial 1 (mean age 45) were given Midostaurin instead of Quizartinib?*\n\nSince `multinma` fits a logistic model, the outputs are on the **Log Odds Ratio (Log OR)** scale. To make them clinically interpretable, we must exponentiate them to get the **Odds Ratio (OR)**.\n\nFor the Quizartinib vs Midostaurin comparison: $$\\text{OR} = e^{-0.664} \\approx 0.51$$\n\nSince the comparison is `Quiz vs Mido`, an OR of 0.51 means that for a 45-year-old patient, the odds of achieving Complete Remission (CR) with Quizartinib are only **0.51 times** the odds with Midostaurin. Conversely, the odds of CR with Midostaurin are $1 / 0.51 \\approx 1.96$ times higher than with Quizartinib in this younger population.\n\nBy explicitly standardizing the comparison to a shared target covariate profile (e.g., `age = 45`), we finally achieve a mathematically rigorous \"apples-to-apples\" comparison that is immune to Ecological Bias.\n\n------------------------------------------------------------------------\n\n## Methodological Boundaries: ML-NMR vs. MAIC {#6-boundaries}\n\nFollowing the landmark paper by Phillippo et al. (2020), understanding the boundary conditions between MAIC and ML-NMR is a critical component of any HTA submission strategy. While ML-NMR is technically superior in handling ecological bias and complex networks, both methods have distinct application boundaries:\n\n| Dimension | Matching-Adjusted Indirect Comparison (MAIC) | Multilevel Network Meta-Regression (ML-NMR) |\n|:-----------------------|:-----------------------|:-----------------------|\n| **Network Complexity** | Primarily restricted to 2-study (1-to-1) comparisons. Extending to multi-study networks is complex and requires sequential weighting. | Designed natively for **arbitrarily complex networks** (Multi-study NMA with regression). |\n| **Sample Size Loss** | Suffers from Effective Sample Size (ESS) reduction. Extreme weights can plummet the ESS, destroying statistical power. | **No loss of sample size**. It uses the full sample size by predicting rather than re-weighting. |\n| **Population Overlap** | Requires good overlap in covariate distributions. If populations differ too much, ESS drops to near zero. | Can handle poor overlap better by extrapolating via the regression model (though extrapolation risk must be acknowledged). |\n| **Model Assumptions** | Semi-parametric. Only requires specifying the moments to match; no explicit model for the outcome is strictly required. | Fully parametric. **Requires specifying the exact regression model** for the outcome (e.g., Logistic, Cox PH). |\n| **Ecological Bias** | None (Inherently immune because it re-weights individual patients directly). | None (Resolves ecological bias in non-linear models via numerical integration). |\n\n### The Decision Rule\n\n- **Use MAIC** when: You only need to compare your single trial against one competitor trial, the covariate overlap is good, and you want to minimize parametric assumptions about the outcome.\n- **Use ML-NMR** when: You are fitting a complex evidence network (more than 2 trials), the populations have poor overlap (and MAIC would destroy your ESS), or you are dealing with non-linear outcomes (where STC would fail due to ecological bias).\n\n------------------------------------------------------------------------\n\n## Technical Audit Considerations\n\n### Fixed vs. Random Effects\n\nIn the code above, we used `trt_effects = \"fixed\"`. This mathematically forces the relative treatment effect $\\theta_{jk}$ to equal the global network effect $d_k$. If we used `random`, the formula becomes $\\theta_{jk} \\sim N(d_k, \\tau^2)$, acknowledging between-study heterogeneity ($\\tau$). In HEOR submissions involving sparse networks (e.g., just 2 or 3 trials), Random Effects models are statistically over-parameterized and usually fail to converge.\n\n### Multi-Dimensional Integration & Correlation Borrowing\n\nIf we needed to adjust for two variables (e.g., `age` and `WBC`), the Sobol sequence must sample from a 2D space. Because literature rarely reports the correlation ($\\rho$) between variables in the AgD trial, standard practice involves **Correlation Borrowing**:\n\n1.  Calculate the covariance matrix from the IPD trial.\n2.  Extract the Cholesky decomposition of this matrix.\n3.  Apply this Cholesky operator to the AgD Sobol points to stretch the independent 2D grid into a realistic, biologically-correlated elliptical \"probability cloud\".\n\nThis ensures the integration avatars accurately represent real human physiological profiles, rather than mathematically impossible combinations.\n\n------------------------------------------------------------------------\n\n## Case Study Comparison: Mock Case vs. TA1013 (Quizartinib)\n\nTo demonstrate the real-world applicability of this minimal mock case, we compare its settings and findings with the actual ML-NMR analysis submitted by Daiichi Sankyo for **TA1013 (Quizartinib)**, as audited by the External Assessment Group (EAG).\n\n### Network Structure & Evidence Types\n\n- **Mock Case**: Simulates 1 IPD trial ($N=300$) and 1 AgD trial ($N=300$).\n- **TA1013 Reality**: The actual network also relied on just 2 core trials: **QuANTUM-First** (provided IPD for Quizartinib, $N=539$) and **RATIFY** (only AgD was available for Midostaurin, $N=717$, with the analyzed FLT3-ITD subgroup being $N=452$) \\[1, 2, 6\\].\n\n### Population Characteristics (Baseline Age)\n\n- **Mock Case**: IPD population is younger (mean age 45) and AgD population is older (mean age 65).\n- **TA1013 Reality**: The direction was reversed, but the extreme mismatch remained. The IPD trial (QuANTUM-First) included older patients (median age \\~56), while the AgD trial (RATIFY) included only younger patients aged 18–59 (median age 47) \\[6, 8\\].\n\n### Statistical Model & Link Function\n\n- **Mock Case**: Modeled a binary outcome (CR rate) using a Bernoulli distribution (`bernoulli2`) and a Logit link function (`logit`).\n- **TA1013 Reality**: The company's actual code for the CR endpoint also specified `likelihood = \"bernoulli2\"` and `link = \"logit\"` \\[2\\].\n\n### Treatment-Covariate Interactions\n\n- **Mock Case**: Assumed a shared interaction effect for Age across active treatments (`class_interactions = \"common\"`).\n- **TA1013 Reality**: Because data from only one IPD and one AgD trial was insufficient to estimate independent interaction terms, the company was forced to make the **Shared Effect Modification (SEM)** assumption \\[7, 9\\]. They assumed that covariates like Age had the same interaction effect on both Quizartinib and Midostaurin, specifying `class_interactions = \"common\"` in their code \\[2\\].\n\n### Collinearity & Bias Challenges\n\n- **Mock Case**: We observed that missing IPD for the AgD trial caused severe collinearity between baseline risk and treatment effect, leading to an overestimation of Midostaurin's effect in our simulation.\n- **TA1013 Reality**: The EAG pointed out that the population adjustments applied within the company's ML-NMR were biased and tended to overestimate **Quizartinib's** effect \\[2\\]. This led the appraisal committee to conclude that the results \"lacked face validity\" \\[3\\].\n\n### References (NICE TA1013 Committee Papers)\n\n- **\\[1\\]** Document B: Section B.2.4 (Starts on Page 50).\n- **\\[2\\]** Document B: Section B.2.8 (Starts on Page 82).\n- **\\[3\\]** External Assessment Report (EAR) (Separate report by University of York).\n- **\\[6\\]** Document B: Section B.2.4.1 (Page 50).\n- **\\[7\\]** Document B: Section B.2.7 (Subgroup analysis).\n- **\\[8\\]** Document B: Section B.2.8.2 (Page 83).\n- **\\[9\\]** Document B: Section B.2.8.7 (Page 111) & Appendix M.\n\nThis comparison proves that our mock case, while minimal, perfectly captures the structural constraints, forced statistical compromises, and inherent bias risks of state-of-the-art ML-NMR in real HTA submissions.\n\n```{=html}\n<!-- Audit Point: ML-NMR Interview Summary\n\"ML-NMR is not simply pooling data. It actively isolates study-specific baseline intercepts (\\mu_k) from network-shared treatment effects (\\beta). By utilizing numerical integration via Sobol sequences, it seamlessly backfills individual-level non-linear signals (IPD) into macro-level target populations (AgD) without incurring the ecological bias inherent to traditional STC.\"\n-->\n```",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}