{
  "hash": "a4cfaa11ed49fe3d0706daf29b6200d2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Pairwise Meta-Analysis: The Foundation of NMA\"\nauthor: \"Xiaoge Zhang, PhD\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    code-summary: \"View the code\"\n    number-sections: true\n---\n\n*Pooling direct evidence for one comparison, from the likelihood up*\n\n## Executive Summary: One Comparison, Many Trials\n\nA pairwise meta-analysis pools the results of several trials that all compare the **same two treatments**, say a new drug B against standard of care A. Each trial on its own is a noisy estimate of the treatment effect; pooled, they give one estimate with a narrower interval.\n\nIt is also the building block of every method in this library. A [Standard Bayesian NMA](01_Standard_Bayesian_NMA_Guide.qmd) is several pairwise meta-analyses estimated together, tied by the consistency assumption so that evidence on A vs B and A vs C also informs B vs C. Everything an NMA adds sits on top of the two questions answered here:\n\n1.  How should trials of different sizes be **weighted**?\n2.  What if the trials do not all estimate the **same** effect?\n\n## Theoretical Framework: From a 2×2 Table to a Pooled Estimate\n\n### The Effect Size in a Single Trial\n\nFor a binary outcome such as response, each trial reduces to a 2×2 table:\n\n|             | Responders | Non-responders |\n|:------------|:----------:|:--------------:|\n| Treatment B |    $a$     |      $b$       |\n| Treatment A |    $c$     |      $d$       |\n\nThe odds ratio and its logarithm are\n\n$$OR_i = \\frac{a / b}{c / d} = \\frac{ad}{bc}, \\qquad y_i = \\ln OR_i$$\n\nMeta-analysis works on the log scale because the OR is bounded below by 0 and asymmetric around 1, whereas $\\ln OR$ is symmetric around 0 and close to Normal in reasonably sized trials.\n\nThe variance of $y_i$ is\n\n$$v_i = \\frac{1}{a} + \\frac{1}{b} + \\frac{1}{c} + \\frac{1}{d}$$\n\nIt comes from the two arms separately. In one arm with $n$ patients and response rate $p$, the log odds $\\ln(a/b)$ has approximate variance $\\frac{1}{np(1-p)}$, which equals $\\frac{1}{a} + \\frac{1}{b}$ because $a = np$ and $b = n(1-p)$. The two arms are independent, so their variances add. Larger trials have larger counts, hence smaller $v_i$.\n\n### Fixed Effect: Inverse-Variance Weighting\n\nThe **fixed-effect** model assumes every trial estimates one common effect $\\theta$, and differs from it only through sampling error:\n\n$$y_i \\sim N(\\theta, v_i), \\qquad i = 1, \\dots, k$$\n\ntreating each $v_i$ as known. The log-likelihood is\n\n$$\\ell(\\theta) = -\\frac{1}{2} \\sum_{i=1}^{k} \\frac{(y_i - \\theta)^2}{v_i} + \\text{const}$$\n\nSetting its derivative to zero gives the maximum likelihood estimate:\n\n$$\\sum_{i=1}^{k} \\frac{y_i - \\theta}{v_i} = 0 \\quad \\Rightarrow \\quad \\hat\\theta_{FE} = \\frac{\\sum w_i y_i}{\\sum w_i}, \\qquad w_i = \\frac{1}{v_i}$$\n\nSo the pooled estimate is a weighted average, and each trial's weight is the inverse of its variance: precise trials count for more. The second derivative of $\\ell(\\theta)$ is $-\\sum w_i$, which gives\n\n$$\\text{Var}(\\hat\\theta_{FE}) = \\frac{1}{\\sum w_i}$$\n\nThis is the same curvature argument as in [The Core of Bayesian Estimation](10_Bayesian_Estimation.qmd): every trial adds its weight to the curvature of the log-likelihood, so the interval narrows as trials accumulate.\n\n### Random Effects: When Trials Estimate Different Effects\n\nTrials differ in populations, doses and settings, so the true effect may differ between them. The **random-effects** model lets each trial have its own true effect $\\theta_i$, drawn from a common distribution:\n\n$$y_i \\sim N(\\theta_i, v_i), \\qquad \\theta_i \\sim N(\\mu, \\tau^2)$$\n\nHere $\\mu$ is the average effect across settings and $\\tau^2$ the between-study variance. Integrating out $\\theta_i$ gives\n\n$$y_i \\sim N(\\mu, \\; v_i + \\tau^2)$$\n\nwhich is the fixed-effect model with every variance increased by $\\tau^2$. The same algebra therefore applies, with weights $w_i^* = 1 / (v_i + \\tau^2)$:\n\n$$\\hat\\mu_{RE} = \\frac{\\sum w_i^* y_i}{\\sum w_i^*}, \\qquad \\text{Var}(\\hat\\mu_{RE}) = \\frac{1}{\\sum w_i^*}$$\n\nAdding the same $\\tau^2$ to every trial matters most for the trials whose own $v_i$ is small. Large trials lose weight, small trials gain it, and the weights become more equal.\n\n### Measuring Heterogeneity: Q, τ² and I²\n\n**Cochran's Q** measures how far the trials scatter around the fixed-effect estimate, in units of their own precision:\n\n$$Q = \\sum_{i=1}^{k} w_i (y_i - \\hat\\theta_{FE})^2$$\n\nIf all trials share one effect, $Q$ follows a $\\chi^2_{k-1}$ distribution with expected value $k - 1$. Scatter beyond that is attributed to heterogeneity. The **DerSimonian–Laird** estimator turns the excess into an estimate of $\\tau^2$:\n\n$$\\hat\\tau^2_{DL} = \\max\\left(0, \\; \\frac{Q - (k - 1)}{\\sum w_i - \\sum w_i^2 / \\sum w_i}\\right)$$\n\nand **I²** expresses the excess as a share of $Q$:\n\n$$I^2 = \\max\\left(0, \\; \\frac{Q - (k - 1)}{Q}\\right)$$\n\nI² is the proportion of the observed variability that reflects real differences between trials rather than chance. It is a proportion, not a size: it says nothing directly about how far apart the true effects are. That is what $\\tau$ measures.\n\n### The Prediction Interval\n\nThe confidence interval for $\\mu$ describes uncertainty about the **average** effect. A decision about a new population needs the range of effects to expect in **one new setting**, which also includes the spread $\\tau^2$:\n\n$$\\hat\\mu_{RE} \\pm 1.96 \\sqrt{\\hat\\tau^2 + \\text{Var}(\\hat\\mu_{RE})}$$\n\nWith substantial heterogeneity, the prediction interval can include no effect even when the confidence interval does not.\n\n### The Bayesian Version: An NMA With One Comparison\n\nThe models above take each $y_i$ and $v_i$ as given, which relies on a Normal approximation. The Bayesian model used for NMA goes back to the counts, with a Binomial likelihood for each arm:\n\n$$r_{iA} \\sim \\text{Binomial}(n_{iA}, p_{iA}), \\qquad r_{iB} \\sim \\text{Binomial}(n_{iB}, p_{iB})$$\n\n$$\\text{logit}(p_{iA}) = \\mu_i, \\qquad \\text{logit}(p_{iB}) = \\mu_i + \\delta_i, \\qquad \\delta_i \\sim N(d, \\tau^2)$$\n\nThis is the model of the [Standard Bayesian NMA](01_Standard_Bayesian_NMA_Guide.qmd) guide with a single comparison: $\\mu_i$ is the study's baseline log odds, $\\delta_i$ its log OR and $d$ the pooled log OR. Two differences from the DerSimonian–Laird approach matter in practice: no Normal approximation is needed for each trial, and $\\tau$ is estimated with its own uncertainty instead of being plugged in as a single number.\n\n## The Minimal Mock Case: Five Trials of B vs A\n\n- **Treatment A**: Standard of Care\n- **Treatment B**: New Drug\n- **Outcome**: response (higher is better), so an OR above 1 favours B\n\nFive trials of different sizes compared B with A:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(knitr)\n\ntrials <- data.frame(\n    study = paste(\"Study\", 1:5),\n    n_A = c(120, 60, 300, 80, 150),\n    r_A = c(24, 15, 75, 16, 30),\n    n_B = c(120, 60, 300, 80, 150),\n    r_B = c(45, 28, 88, 34, 60)\n)\n\nkable(trials, col.names = c(\"Study\", \"Patients (A)\", \"Responders (A)\", \"Patients (B)\", \"Responders (B)\"))\n```\n\n::: {.cell-output-display}\n\n\n|Study   | Patients (A)| Responders (A)| Patients (B)| Responders (B)|\n|:-------|------------:|--------------:|------------:|--------------:|\n|Study 1 |          120|             24|          120|             45|\n|Study 2 |           60|             15|           60|             28|\n|Study 3 |          300|             75|          300|             88|\n|Study 4 |           80|             16|           80|             34|\n|Study 5 |          150|             30|          150|             60|\n\n\n:::\n:::\n\n\nStudy 3 is by far the largest trial, and, as the next section shows, the one closest to no effect. That combination is what makes the choice between fixed and random effects visible.\n\n## Implementation: From Scratch, `metafor` and Stan\n\n### From Scratch in Base R\n\nEvery quantity from the theoretical framework, computed directly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfmt <- function(x) sprintf(\"%.2f\", x)\nci_text <- function(est, se) sprintf(\"%.2f (%.2f, %.2f)\", exp(est), exp(est - 1.96 * se), exp(est + 1.96 * se))\n\n# Cells of each 2x2 table\nresp_B <- trials$r_B\nnon_B <- trials$n_B - trials$r_B\nresp_A <- trials$r_A\nnon_A <- trials$n_A - trials$r_A\n\n# Effect size and variance per trial\ny <- log((resp_B / non_B) / (resp_A / non_A)) # log OR\nv <- 1 / resp_B + 1 / non_B + 1 / resp_A + 1 / non_A\nk <- length(y)\n\n# Fixed effect\nw <- 1 / v\nlor_fe <- sum(w * y) / sum(w)\nse_fe <- sqrt(1 / sum(w))\n\n# Heterogeneity\nQ <- sum(w * (y - lor_fe)^2)\nQ_p <- pchisq(Q, df = k - 1, lower.tail = FALSE)\ntau2 <- max(0, (Q - (k - 1)) / (sum(w) - sum(w^2) / sum(w))) # DerSimonian-Laird\nI2 <- max(0, (Q - (k - 1)) / Q)\n\n# Random effects\nw_re <- 1 / (v + tau2)\nlor_re <- sum(w_re * y) / sum(w_re)\nse_re <- sqrt(1 / sum(w_re))\n\n# 95% prediction interval, on the OR scale\npi_half <- 1.96 * sqrt(tau2 + se_re^2)\npi_lo <- exp(lor_re - pi_half)\npi_hi <- exp(lor_re + pi_half)\n\nw_fe_pct <- 100 * w / sum(w)\nw_re_pct <- 100 * w_re / sum(w_re)\n\nkable(\n    data.frame(trials$study, exp(y), y, v, w_fe_pct, w_re_pct),\n    digits = c(0, 2, 3, 3, 1, 1),\n    col.names = c(\"Study\", \"OR\", \"log OR\", \"Variance\", \"Weight, FE (%)\", \"Weight, RE (%)\")\n)\n```\n\n::: {.cell-output-display}\n\n\n|Study   |   OR| log OR| Variance| Weight, FE (%)| Weight, RE (%)|\n|:-------|----:|------:|--------:|--------------:|--------------:|\n|Study 1 | 2.40|  0.875|    0.088|           16.4|           19.8|\n|Study 2 | 2.62|  0.965|    0.156|            9.2|           14.8|\n|Study 3 | 1.25|  0.219|    0.034|           42.5|           27.1|\n|Study 4 | 2.96|  1.084|    0.129|           11.1|           16.4|\n|Study 5 | 2.67|  0.981|    0.069|           20.7|           21.8|\n\n\n:::\n\n```{.r .cell-code}\nkable(\n    data.frame(Q, k - 1, Q_p, tau2, 100 * I2),\n    digits = c(2, 0, 3, 3, 1),\n    col.names = c(\"Cochran's Q\", \"df\", \"p-value\", \"$\\\\tau^2$\", \"$I^2$ (%)\")\n)\n```\n\n::: {.cell-output-display}\n\n\n| Cochran's Q| df| p-value| $\\tau^2$| $I^2$ (%)|\n|-----------:|--:|-------:|--------:|---------:|\n|        9.73|  4|   0.045|    0.113|      58.9|\n\n\n:::\n\n```{.r .cell-code}\nkable(\n    data.frame(\n        c(\"Fixed effect\", \"Random effects (DerSimonian-Laird)\"),\n        c(ci_text(lor_fe, se_fe), ci_text(lor_re, se_re)),\n        c(\"&ndash;\", sprintf(\"%.2f to %.2f\", pi_lo, pi_hi))\n    ),\n    col.names = c(\"Model\", \"Pooled OR (95% CI)\", \"95% prediction interval\")\n)\n```\n\n::: {.cell-output-display}\n\n\n|Model                              |Pooled OR (95% CI) |95% prediction interval |\n|:----------------------------------|:------------------|:-----------------------|\n|Fixed effect                       |1.92 (1.51, 2.42)  |&ndash;                 |\n|Random effects (DerSimonian-Laird) |2.16 (1.46, 3.19)  |1.00 to 4.64            |\n\n\n:::\n:::\n\n\nStudy 3 has the smallest variance, so under the fixed-effect model it carries 42% of the weight. With $\\hat\\tau^2 =$ 0.113 added to every variance, its share falls to 27%, while the smallest trial, Study 2, rises from 9% to 15%.\n\n### Cross-Check With `metafor`\n\nThe standard R package gives the same numbers:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(metafor)\n\nes <- escalc(measure = \"OR\", ai = r_B, n1i = n_B, ci = r_A, n2i = n_A, data = trials)\nfit_fe <- rma(yi, vi, data = es, method = \"FE\")\nfit_re <- rma(yi, vi, data = es, method = \"DL\")\n\nkable(\n    data.frame(\n        c(\"log OR, fixed effect\", \"SE, fixed effect\", \"log OR, random effects\", \"SE, random effects\", \"$\\\\tau^2$\", \"$I^2$ (%)\"),\n        c(lor_fe, se_fe, lor_re, se_re, tau2, 100 * I2),\n        c(coef(fit_fe), fit_fe$se, coef(fit_re), fit_re$se, fit_re$tau2, fit_re$I2)\n    ),\n    digits = 4,\n    col.names = c(\"Quantity\", \"From scratch\", \"metafor\")\n)\n```\n\n::: {.cell-output-display}\n\n\n|Quantity               | From scratch| metafor|\n|:----------------------|------------:|-------:|\n|log OR, fixed effect   |       0.6500|  0.6500|\n|SE, fixed effect       |       0.1200|  0.1200|\n|log OR, random effects |       0.7682|  0.7682|\n|SE, random effects     |       0.1996|  0.1996|\n|$\\tau^2$               |       0.1131|  0.1131|\n|$I^2$ (%)              |      58.8789| 58.8789|\n\n\n:::\n:::\n\n\nThe forest plot shows each trial with its 95% CI, the random-effects pooled estimate as a diamond, and the prediction interval as the dotted line through it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforest(\n    fit_re,\n    slab = trials$study,\n    atransf = exp,\n    at = log(c(0.5, 1, 2, 4, 8)),\n    addpred = TRUE,\n    header = c(\"Study\", \"OR [95% CI]\")\n)\n```\n\n::: {.cell-output-display}\n![](12_Pairwise_Meta_Analysis_files/figure-html/forest-1.png){width=672}\n:::\n:::\n\n\n### Bayesian Random Effects in Stan\n\n::: {.callout-note collapse=\"true\" appearance=\"minimal\"}\n# Stan model: pairwise_re.stan\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n``` stan\ndata {\n  int<lower=1> S;                        // number of studies\n  array[S] int<lower=0> n_A;             // patients on A\n  array[S] int<lower=0> r_A;             // responders on A\n  array[S] int<lower=0> n_B;             // patients on B\n  array[S] int<lower=0> r_B;             // responders on B\n}\n\nparameters {\n  vector[S] mu;                          // baseline log odds on A, one per study\n  real d;                                // pooled log OR, B vs A\n  real<lower=0> tau;                     // between-study SD of the log OR\n  vector[S] z;                           // standardised study-level deviations\n}\n\ntransformed parameters {\n  vector[S] delta = d + tau * z;         // study-specific log OR (non-centred)\n}\n\nmodel {\n  mu ~ normal(0, 10);\n  d ~ normal(0, 10);\n  tau ~ normal(0, 1);                    // half-normal, since tau >= 0\n  z ~ std_normal();\n\n  r_A ~ binomial_logit(n_A, mu);\n  r_B ~ binomial_logit(n_B, mu + delta);\n}\n\ngenerated quantities {\n  real OR = exp(d);                      // pooled OR\n  real OR_new = exp(normal_rng(d, tau)); // OR in a new study setting\n}\n```\n\n\n:::\n:::\n\n:::\n\nThree choices in the model are worth stating:\n\n- **Priors**: $N(0, 10^2)$ for the baselines $\\mu_i$ and the pooled log OR $d$, which is vague on the log-odds scale; half-Normal$(0, 1)$ for $\\tau$, which keeps implausibly large heterogeneity unlikely without ruling it out.\n- **Non-centred parameterisation**: $\\delta_i = d + \\tau z_i$ with $z_i \\sim N(0, 1)$. It describes the same model as $\\delta_i \\sim N(d, \\tau^2)$, but samples far more reliably when $\\tau$ is poorly identified, as it is with five trials.\n- **Prediction**: `OR_new` draws a log OR for a new study from $N(d, \\tau^2)$ at every iteration, giving the Bayesian counterpart of the prediction interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rstan)\n\nstan_data <- list(\n    S = nrow(trials),\n    n_A = trials$n_A, r_A = trials$r_A,\n    n_B = trials$n_B, r_B = trials$r_B\n)\n\nfit_bayes <- stan(\n    file = \"pairwise_re.stan\",\n    data = stan_data,\n    chains = 4,\n    iter = 4000,\n    warmup = 2000,\n    seed = 42,\n    control = list(adapt_delta = 0.99),\n    refresh = 0\n)\n\nbayes_sum <- summary(fit_bayes, pars = c(\"d\", \"OR\", \"tau\", \"OR_new\"))$summary\nkable(\n    bayes_sum[, c(\"mean\", \"sd\", \"2.5%\", \"50%\", \"97.5%\", \"n_eff\", \"Rhat\")],\n    digits = c(3, 3, 3, 3, 3, 0, 3),\n    col.names = c(\"Mean\", \"SD\", \"2.5%\", \"Median\", \"97.5%\", \"ESS\", \"R-hat\")\n)\n```\n\n::: {.cell-output-display}\n\n\n|       |  Mean|    SD|  2.5%| Median| 97.5%|  ESS| R-hat|\n|:------|-----:|-----:|-----:|------:|-----:|----:|-----:|\n|d      | 0.778| 0.263| 0.288|  0.766| 1.334| 3229| 1.001|\n|OR     | 2.256| 0.647| 1.334|  2.151| 3.796| 3175| 1.001|\n|tau    | 0.433| 0.263| 0.057|  0.383| 1.117| 2758| 1.000|\n|OR_new | 2.762| 7.868| 0.719|  2.137| 7.462| 7858| 1.000|\n\n\n:::\n\n```{.r .cell-code}\nn_div <- sum(sapply(get_sampler_params(fit_bayes, inc_warmup = FALSE), function(x) sum(x[, \"divergent__\"])))\n```\n:::\n\n\nAll R-hat values are at or below 1.001, the smallest ESS is 2758, and the sampler reported 0 divergent transitions.\n\n## Results & Interpretation {#results}\n\n\n::: {.cell}\n\n```{.r .cell-code}\npost <- rstan::extract(fit_bayes, pars = c(\"OR\", \"OR_new\", \"tau\"))\nb_or <- quantile(post$OR, c(0.5, 0.025, 0.975))\nb_new <- quantile(post$OR_new, c(0.025, 0.975))\nb_tau <- quantile(post$tau, c(0.5, 0.025, 0.975))\n\nkable(\n    data.frame(\n        c(\"Fixed effect\", \"Random effects (DerSimonian-Laird)\", \"Random effects (Bayesian)\"),\n        c(ci_text(lor_fe, se_fe), ci_text(lor_re, se_re), sprintf(\"%.2f (%.2f, %.2f)\", b_or[1], b_or[2], b_or[3])),\n        c(\"&ndash;\", sprintf(\"%.2f to %.2f\", pi_lo, pi_hi), sprintf(\"%.2f to %.2f\", b_new[1], b_new[2])),\n        c(\"0 (assumed)\", sprintf(\"%.2f\", sqrt(tau2)), sprintf(\"%.2f (%.2f, %.2f)\", b_tau[1], b_tau[2], b_tau[3]))\n    ),\n    col.names = c(\"Model\", \"Pooled OR (95% interval)\", \"95% prediction interval\", \"$\\\\tau$ (between-study SD)\")\n)\n```\n\n::: {.cell-output-display}\n\n\n|Model                              |Pooled OR (95% interval) |95% prediction interval |$\\tau$ (between-study SD) |\n|:----------------------------------|:------------------------|:-----------------------|:-------------------------|\n|Fixed effect                       |1.92 (1.51, 2.42)        |&ndash;                 |0 (assumed)               |\n|Random effects (DerSimonian-Laird) |2.16 (1.46, 3.19)        |1.00 to 4.64            |0.34                      |\n|Random effects (Bayesian)          |2.15 (1.33, 3.80)        |0.72 to 7.46            |0.38 (0.06, 1.12)         |\n\n\n:::\n:::\n\n\nThree readings of this table matter for an HTA submission.\n\n**Fixed vs random effects.** The fixed-effect OR (1.92) sits closer to Study 3 than the random-effects OR (2.16), because the fixed-effect model gives the largest, least favourable trial 42% of the weight. Which is right is not a statistical question alone: if the trials plausibly differ in population or setting, the fixed-effect assumption of one common effect is hard to defend, and its narrower interval is not a real gain in precision.\n\n**Confidence vs prediction interval.** The random-effects 95% CI (1.46 to 3.19) describes the average effect across settings like these trials. The prediction interval (1.00 to 4.64) describes the effect to expect in one new setting, and its lower end sits at 1.00. B helps on average; whether it helps in a particular new population is far less certain. A cost-effectiveness model that uses only the pooled estimate carries the first statement, not the second.\n\n**Frequentist vs Bayesian random effects.** The Bayesian 95% interval for the pooled OR (1.33 to 3.80) is wider than the DerSimonian–Laird CI. DerSimonian–Laird plugs in one value of $\\tau$ (0.34) as if it were known; the Bayesian model carries the uncertainty about $\\tau$ itself, whose 95% interval runs from 0.06 to 1.12. With five trials, that uncertainty is large, and ignoring it overstates precision.\n\n## HTA Audit Points & Interview Q&A {#audit}\n\n::: {.callout-important collapse=\"true\"}\n# Should I choose fixed or random effects based on I²?\n\nNo. The choice should rest first on whether the trials plausibly estimate one common effect: similar populations, doses, comparators and outcome definitions. I² is a supporting signal, not a switch. A low I² with few trials is weak evidence of homogeneity, because Q has little power to detect heterogeneity when $k$ is small. NICE DSU TSD 2 compares fixed- and random-effects models on fit (residual deviance and DIC) alongside this clinical reasoning.\n:::\n\n::: {.callout-important collapse=\"true\"}\n# What does an I² of around 60% actually tell you?\n\nThat around 60% of the scatter between trial results reflects real differences rather than chance. It does not say whether those differences are clinically large; $\\tau$ on the log OR scale, or the prediction interval, answers that. I² also depends on trial size: the same true spread gives a higher I² when the trials are large and precise, because less of the scatter can be put down to chance.\n:::\n\n::: {.callout-important collapse=\"true\"}\n# Why is DerSimonian–Laird criticised when there are few trials?\n\nIt estimates $\\tau^2$ from one moment equation and then treats the estimate as fixed, so the confidence interval ignores the uncertainty in $\\tau^2$. With few trials that uncertainty is large, and the interval is too narrow. Common remedies are the Hartung–Knapp–Sidik–Jonkman adjustment, which rescales the variance and uses a $t$ distribution, usually widening the interval, restricted maximum likelihood for $\\tau^2$, or a Bayesian model that carries the uncertainty in $\\tau$ through, as above.\n:::\n\n::: {.callout-important collapse=\"true\"}\n# When is a pairwise meta-analysis enough, and when do you need an NMA?\n\nA pairwise meta-analysis is enough when the decision problem is one comparison and there are head-to-head trials of it. Once the decision involves several treatments, or the comparator of interest has never been tested directly against the new treatment, the evidence has to be connected through common comparators, which is what an [NMA](01_Standard_Bayesian_NMA_Guide.qmd) does.\n:::\n\n## Conclusion {#conclusion}\n\nPairwise meta-analysis comes down to a weighted average with two decisions attached: how to weight the trials, and whether they share one effect. The fixed-effect model weights by precision alone; the random-effects model adds between-study variance, which evens out the weights, widens the interval and makes the prediction interval available. The Bayesian version works from the counts and carries the uncertainty in $\\tau$, and it is the same model that a [Standard Bayesian NMA](01_Standard_Bayesian_NMA_Guide.qmd) extends to a network of comparisons.\n\n**Methodological References**: NICE DSU TSD 2 (Dias et al., 2011, updated 2016); *Cochrane Handbook for Systematic Reviews of Interventions*, Chapter 10; DerSimonian & Laird (1986); Higgins, Thompson & Spiegelhalter (2009) on prediction intervals.\n",
    "supporting": [
      "12_Pairwise_Meta_Analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}