{
  "hash": "384f0f17ef1f00d21938af483864d15b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Standard Bayesian Network Meta-Analysis (NMA)\"\nauthor: \"Xiaoge Zhang\"\ndate: 06/05/2026\nformat: \n  html:\n    theme: cosmo          # 使用现代、干净的主题（可选 flatly, lumen 等）\n    toc: true             # 自动生成右侧目录（Table of Contents）\n    toc-depth: 3          # 目录层级深度\n    code-fold: true       # 默认折叠代码块，读者点击可以展开（非常适合作品集）\n    code-summary: \"View the code\" # 折叠代码块的提示文字\n    number-sections: true # 自动为标题编号\n---\n\n*Mastering Evidence Synthesis through a Minimal Mock Case*\n\n```{=html}\n<!--\n## 📑 Table of Contents\n\n1.  [**Executive Summary: The Anatomy of a Network**](#1-executive-summary-the-anatomy-of-a-network)\n2.  [**Theoretical Framework: The Calculus of Consistency**](#2-theoretical-framework-the-calculus-of-consistency)\n3.  [**The Minimal Mock Case: A vs B vs C**](#3-the-minimal-mock-case-a-vs-b-vs-c)\n4.  [**MCMC Forensic Audit: Implementation & Convergence**](#4-mcmc-forensic-audit-implementation--convergence)\n5.  [**Results & Interpretation: The League Table**](#5-results--interpretation-the-league-table)\n6.  [**Strategic Q&A: Interview Prep**](#6-strategic-qa-interview-prep)\n7.  [**Strategic Conclusion**](#7-strategic-conclusion)\n-->\n```\n\n## Executive Summary: The Anatomy of a Network {#1-executive-summary-the-anatomy-of-a-network}\n\nNetwork Meta-Analysis (NMA) is the gold standard for evidence synthesis in Health Technology Assessment (HTA). It extends traditional pair-wise meta-analysis by allowing the simultaneous comparison of multiple treatments, even those that have never been compared head-to-head in a clinical trial.\n\n```{=html}\n<!--\n【基础概念】traditional pair-wise meta-analysis（传统两两 Meta 分析）\n指仅在两个特定治疗（如 A vs B）之间进行直接比较的 Meta 分析。它只能整合那些做了相同头对头（head-to-head）试验的数据，通过合并多个试验的效应量来提高统计效能。它的局限是无法连接没有直接临床试验的药物。\n-->\n```\n\nThis guide is designed to take you from a conceptual understanding to a mastery of **Standard Bayesian NMA**. We use a **Minimal Mock Case** involving three treatments (A, B, and C) forming a closed loop. This structure allows us to explore the critical concepts of **Direct Evidence**, **Indirect Evidence**, and **Network Consistency**.\n\n```{=html}\n<!--\n【审计备忘/面试要点】为什么在 HTA 中偏爱“贝叶斯” NMA 而非频率学派？\n1. 贝叶斯不是回归方法，而是一种统计学范式。回归只是我们在该框架下使用的具体模型。\n2. 频率学派（Frequentist）NMA 存在（如 R 包 netmeta），但贝叶斯学派具有以下压倒性优势：\n   - 天然输出“排名概率”（Rankogram/SUCRA），直接回答“哪个药最好”的 HTA 核心问题。\n   - 全量不确定性传播（Full Uncertainty Propagation）：通过 MCMC 采样，将异质性参数（tau^2）的不确定性自动带入最终效应量的可信区间，结果更诚实。\n   - 处理稀疏网络能力强：通过弱信息先验（Weakly Informative Priors）稳定模型，避免频率学派在稀疏数据时矩阵无法求逆的不收敛问题。\n-->\n```\n\n::: {.callout-tip collapse=\"true\"}\n# Learning Strategy\n\nFocus on the transition from the data likelihood to the network constraints. Understanding how indirect paths are calculated is the key to answering advanced interview questions.\n:::\n\n## Theoretical Framework: The Calculus of Consistency {#2-theoretical-framework-the-calculus-of-consistency}\n\nIn a Bayesian NMA, we model the data at the study level and connect the treatment effects through a common reference treatment.\n\n### The Likelihood (Binomial-Logit Model)\n\nFor a binary outcome (e.g., responders $r_{jk}$ out of $n_{jk}$ patients in study $j$ for treatment $k$): <!-- 一个 study 就是指某一种特定的药物 vs 自己的对照组比较的实验 -->\n\nFor example, we can have: $$r_{1,base/control} \\sim \\text{Binomial}(p_{1b}, n_{1b})$$ $$r_{1,trt} \\sim \\text{Binomial}(p_{1,trt}, n_{1,trt})$$\n\nWe use the logit link function to map probabilities to the real line:\n\n$$\\text{logit}(p_{1b}) = \\ln\\left(\\frac{p_{1b}}{1-p_{1b}}\\right) = \\mu_1 + \\delta_{1b} = \\mu_1$$ $$\\text{logit}(p_{1,trt}) = \\ln\\left(\\frac{p_{1,trt}}{1-p_{1,trt}}\\right) = \\mu_1 + \\delta_{1,trt}$$\n\nobviously,\n\n$$\\text{logit}(p_{1,trt}) - \\text{logit}(p_{1b}) = \\ln\\left( \\frac{\\frac{p_{1,trt}}{1-p_{1,trt}}}{\\frac{p_{1b}}{1-p_{1b}}} \\right) = \\delta_{1,trt}$$ Where:\n\n- $\\mu_1$: The baseline log-odds of response in study $j$ (for the control treatment in that study).\n- $\\delta_{1,trt}$: The log-odds ratio of treatment $k$ compared to the study's control treatment. Note that $\\delta_{1,b} = 0$.\n\n### The Consistency Assumption (The Core Constraint)\n\nThe defining feature of NMA is the assumption of consistency. We assume that the relative effect of B vs C can be derived from the relative effects of A vs B and A vs C:\n\n$$d_{BC} = d_{AC} - d_{AB}$$\n\nWhere $d_{xy}$ is the pooled relative effect (log-odds ratio) of treatment $y$ vs treatment $x$.\n\n```{=html}\n<!--\n【参数解析】关于公式中的 d 变量\n1. 对应关系：这里的 d 对应 2.3 节中的 d_bk（网络池化/合成效应量）。\n2. 符号说明：字母 b 代表 Baseline（基线/对照），在 NMA 中指代**该具体试验的对照药**。因为不同试验的对照药可能不同（不一定是安慰剂），所以 b 会随试验而变。\n3. 与 delta_jk 的区别：\n   - delta_jk 是具体试验 j 中药物 k 相比对照组 b 的效应量。\n   - d 是整个网络跨所有试验池化后的真实效应量。\n   - 在固定效应模型下 delta_jk = d_bk；在随机效应模型下 delta_jk 围绕 d_bk 呈正态分布。\n4. 计算方式：模型通常直接估算与网络基准药物（如 A）相比的基础参数（如 d_AB, d_AC），而间接效应 d_BC 是通过减法派生出来的：d_BC = d_AC - d_AB。\n-->\n```\n\n```{=html}\n<!--\n【核心假设剖析】一致性假设（Consistency Assumption）成立与不成立的场景\n1. 成立的场景（大概率）：\n   - 临床同质性高：各试验的人群基线特征（如年龄、疾病严重程度）、伴随治疗、终点定义高度相似。\n   - 共同对照药（A）具有可比性：在 A vs B 和 A vs C 的试验中，A 的给药方案和患者群体没有实质差异。\n\n【直观直觉：平行宇宙视角】\n假设存在平行宇宙，一号宇宙中这群人使用 A vs 安慰剂，二号宇宙中完全相同的一群人在完全相同的条件下使用 B vs 安慰剂。此时用 (B vs 安慰剂) - (A vs 安慰剂) 得到的间接效应完美成立。现实中 NMA 的所有数学修正（如倾向性评分、Meta回归、ML-NMR 的积分），本质上都是在试图把不同试验的人群，拉回到这个“完全相同”的平行宇宙状态。\n\n1. 不成立的场景（大概率）：\n   - 存在效应修饰变量（Effect Modifier）分布不均：例如，B 药在老年人中效果更好，而 A vs B 试验招募的全是年轻人，A vs C 试验全是老年人。此时通过 A 间接推算 B vs C 就会失真（Transitivity 违背）。\n   - 试验设计/方法论差异大：例如一个是开放标签（Open-label）试验，另一个是双盲（Double-blind）试验，主观终点可能受到偏倚影响导致不一致。\n-->\n```\n\n### Fixed Effects (FE) vs. Random Effects (RE)\n\n- **Fixed Effects Model**: Assumes that the true relative effect of treatment $k$ vs $b$ is constant across all studies: $\\delta_{jk} = d_{bk}$.\n- **Random Effects Model**: Assumes that the true relative effects vary across studies following a normal distribution: $\\delta_{jk} \\sim \\text{Normal}(d_{bk}, \\tau^2)$, where $\\tau^2$ is the between-study heterogeneity variance.\n\n::: callout-important\n### Judgment Logic for FE vs. RE (HTA Audit Focus)\n\nDeciding between a Fixed Effects and a Random Effects model is a critical decision in NMA. Here is the standard judgment logic: \n\n1. **Clinical Plausibility**: Are the trials sufficiently similar in terms of patient populations (e.g., age, baseline severity), treatment protocols, and outcome definitions? If there are obvious differences, an RE model is clinically more plausible. \n2. **Statistical Heterogeneity**: - Check the estimated between-study standard deviation ($\\tau$). Is it large relative to the treatment effects? - Look at the $I^2$ statistic from pairwise meta-analyses. \n3. **Model Fit (DIC)**: Compare the Deviance Information Criterion (DIC) between FE and RE models. A smaller DIC indicates a better fit. A difference of 3-5 points is usually considered meaningful. If DIC is similar, the simpler FE model is often preferred (principle of parsimony). \n4. **Network Sparsity**: If the network is sparse (very few studies per comparison), the RE model may struggle to estimate $\\tau$ accurately, leading to wide credible intervals. In such cases, an FE model or an RE model with an informative prior for $\\tau$ may be necessary.\n:::\n\n## The Minimal Mock Case: A vs B vs C {#3-the-minimal-mock-case-a-vs-b-vs-c}\n\n- **Treatment A**: Standard of Care (SoC) - Reference\n- **Treatment B**: New Drug 1\n- **Treatment C**: New Drug 2\n\nTo make this concrete, let's construct a minimal network with 3 treatments and 3 studies forming a complete loop.\n\n### The Mock Data\n\n| Study       | Arm 1 (Control) | Arm 2 (Active) | $n_1$ | $r_1$ | $n_2$ | $r_2$ | Observed OR |\n|:--------|:--------|:--------|:--------|:--------|:--------|:--------|:--------|\n| **Study 1** | A               | B              | 100   | 20    | 100   | 40    | 2.67        |\n| **Study 2** | A               | C              | 100   | 20    | 100   | 50    | 4.00        |\n| **Study 3** | B               | C              | 100   | 30    | 100   | 40    | 1.55        |\n\n*Where:*\n\n- $n_1, n_2$: Total number of patients (sample size) in Arm 1 and Arm 2 respectively.\n- $r_1, r_2$: Number of responders (events) in Arm 1 and Arm 2 respectively.\n- **Observed OR** (Odds Ratio) is calculated as: $OR = \\frac{r_2 / (n_2 - r_2)}{r_1 / (n_1 - r_1)}$.\n  - For example, in Study 1: $OR = \\frac{40 / (100 - 40)}{20 / (100 - 20)} \\approx 2.67$.\n\n```{=html}\n<!--\n【逻辑思辨】如果现实中已经有了 Study 3（B vs C 的直接头对头试验），还需要做 NMA 吗？\n1. 没有 Study 3 时：这是 NMA 的经典场景（雪中送炭），必须通过共同对照药 A 进行间接比较。\n2. 有 Study 3 时：依然需要做 NMA，并纳入 Study 1 和 2（锦上添花），原因如下：\n   - 提高精度：结合直接证据与间接证据，变相扩大样本量，使效应量的置信/可信区间更窄。\n   - 一致性检验：只有形成闭环，才能检验直接证据与间接证据是否一致，这是评估证据链可靠性的核心。\n   - 全网排名：HTA 机构（如 NICE）需要对网络中所有药物进行优劣排名，而不仅仅是 B 和 C。\n-->\n```\n\n### The Calculus of the Loop\n\nLet's calculate the log-odds ratios (LOR) for each study:\n\n1.  **Study 1 (A vs B)**: $\\ln(OR_{AB}) = \\ln(2.67) \\approx 0.982$\n2.  **Study 2 (A vs C)**: $\\ln(OR_{AC}) = \\ln(4.00) \\approx 1.386$\n3.  **Study 3 (B vs C)**: $\\ln(OR_{BC}) = \\ln(1.55) \\approx 0.438$\n\n**The Indirect Check:** According to the consistency assumption, the indirect estimate of B vs C should be: $$\\ln(OR_{BC, \\text{ind}}) = \\ln(OR_{AC}) - \\ln(OR_{AB}) = 1.386 - 0.982 = 0.404$$\n\n**The Consistency Gap:**\n\n- Direct $\\ln(OR_{BC}) = 0.438$\n- Indirect $\\ln(OR_{BC}) = 0.404$\n- Difference (Inconsistency) = $0.438 - 0.404 = 0.034$\n\nThis difference is very small, indicating a consistent network.\n\n## MCMC Forensic Audit: How Bayes Actually Solves the Network {#4-mcmc-forensic-audit-implementation--convergence}\n\nIn this section, we move away from simple arithmetic and look at how the Bayesian MCMC engine actually processes our mock data to find the global solution.\n\n### Step 1: Setting up the Likelihood and Parameters\n\nFor our 3 studies, the model views the data as follows. Let $r_{jk}$ be the number of events in study $j$, arm $k$, and $n_{jk}$ be the total patients.\n\nThe formal mathematical likelihood $L$ for the entire network is the product of the probability mass functions (PMF) of the independent Binomial distributions for all studies and arms:\n\n$$L(\\mu, d | r, n) = \\prod_{j=1}^{3} \\prod_{k=1}^{2} \\binom{n_{jk}}{r_{jk}} p_{jk}^{r_{jk}} (1 - p_{jk})^{n_{jk} - r_{jk}}$$\n\n```{=html}\n<!--\n【学派思辨】频率派与贝叶斯派处理似然函数的不同哲学\n1. 频率学派：目标是寻找“最值点”。通过解析求导或数值优化算法，寻找使似然函数 L 达到最大值的唯一参数组合。这本质上是一个求解最值（极大似然估计，MLE）的确定性问题。\n2. 贝叶斯学派：目标是寻找“概率分布”。它不追求单一的最值点，而是通过 MCMC 采样在参数空间中不断游走（即“波动”）。在似然值更高的参数区域，采样点会被更密集地记录；在似然值低的区域，采样点则较稀疏。\n最终，这些海量的采样点在参数空间中形成了一个密度的分布，其直观形态就像一片“概率云”（即后验分布），从而诚实地反映了参数的不确定性。\n--> \n```\n\nWhere the probabilities $p_{jk}$ are derived from the model: $\\text{logit}(p_{jk}) = \\mu_j + \\delta_{jk}$.\n\nSolving for $p_{jk}$ (the inverse-logit or logistic function):\n\n$$p_{jk} = \\frac{1}{1 + \\exp(-(\\mu_j + \\delta_{jk}))}$$\n\nNow let's look at the specific setup for our 3 studies:\n\n| Study | Arm | Treatment | Distribution | Linear Predictor ($\\text{logit}(p)$) |\n|:--------------|:--------------|:--------------|:--------------|:--------------|\n| **Study 1** | 1 | A (SoC) | $r_{11} \\sim \\text{Binomial}(p_{11}, 100)$ | $\\mu_1$ |\n|  | 2 | B | $r_{12} \\sim \\text{Binomial}(p_{12}, 100)$ | $\\mu_1 + d_{AB}$ |\n| **Study 2** | 1 | A (SoC) | $r_{21} \\sim \\text{Binomial}(p_{21}, 100)$ | $\\mu_2$ |\n|  | 2 | C | $r_{22} \\sim \\text{Binomial}(p_{22}, 100)$ | $\\mu_2 + d_{AC}$ |\n| **Study 3** | 1 | B | $r_{31} \\sim \\text{Binomial}(p_{31}, 100)$ | $\\mu_3$ |\n|  | 2 | C | $r_{32} \\sim \\text{Binomial}(p_{32}, 100)$ | $\\mu_3 + d_{BC}$ |\n\n**The Consistency Constraint (The Golden Rule):** At all times, the model enforces: $d_{BC} = d_{AC} - d_{AB}$. This means we only have 5 independent parameters to estimate: $\\mu_1, \\mu_2, \\mu_3, d_{AB}, d_{AC}$. All study data are pooled simultaneously to find the best values for these 5 parameters.\n\n### Step 2: Assigning Priors (The Bayesian Part)\n\nSince we have no prior knowledge in this mock case, we use vague (non-informative) priors:\n\n- Study baselines: $\\mu_1, \\mu_2, \\mu_3 \\sim \\text{Normal}(0, 1000)$\n- Treatment effects: $d_{AB}, d_{AC} \\sim \\text{Normal}(0, 1000)$\n\n::: callout-tip\n### Prior Choice in Real-World NMA\n\nIn real HTA submissions, prior choice is heavily scrutinized: \n\n1. **Priors for Treatment Effects (**$d$): Typically use weakly informative priors like $N(0, 100^2)$ rather than extremely flat priors like $N(0, 1000^2)$, to prevent the sampler from exploring unrealistically large effect sizes while still letting the data dominate. \n2. **Priors for Heterogeneity (**$\\tau$) (in RE models): This is the most sensitive choice! \n   - **Uniform Prior**: e.g., $\\tau \\sim \\text{Uniform}(0, 2)$ or $\\text{Uniform}(0, 5)$. Easy to implement but can place too much weight on large values if data is sparse. \n   - **Half-Normal Prior**: e.g., $\\tau \\sim \\text{Half-Normal}(0, 1)$. Pulls $\\tau$ towards zero, acting as a shrinkage prior. \n   - **Informative Priors**: When the network is sparse, it is best practice to use empirical informative priors based on historical meta-analyses (e.g., Turner et al., 2012 for binary outcomes). This provides a realistic estimate of $\\tau$ even when the current data has little information about it.\n:::\n\n**How Priors and Likelihood Connect in MCMC:**\n\nAccording to Bayes' Theorem, the **Posterior** (the target distribution MCMC tries to map) is proportional to the **Likelihood** multiplied by the **Prior**: $$\\text{Posterior} \\propto \\text{Likelihood} \\times \\text{Prior}$$\n\n::: {.callout-note collapse=\"true\"}\n# In our minimal mock case\n\n1.  **Flat Priors**: Because we use a huge variance (1000), the prior distribution is extremely flat. The prior probability of guessing $d_{AB} = 0.982$ is almost identical to guessing $d_{AB} = 10.0$.\n2.  **Likelihood Dominance**: Therefore, when the MCMC engine calculates the score of a guess, the Prior part contributes almost nothing. The score is dominated by the **Likelihood** (how well the parameters fit the 100-patient data in the table).\n3.  **Guiding the Walk**: When MCMC decides whether to move to a new guess, it compares the ratio of the scores. Since the priors are flat, the decision is almost entirely based on whether the new guess makes the observed data *more likely* than the old guess.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## What exactly are we multiplying in a single MCMC step?\n\n- It is **NOT** a distribution.\n- It is **NOT** a random draw from $\\text{Normal}(0, 1000)$.\n- It is a **specific number** (probability density). In each MCMC step, the engine has a *specific guess* for the parameters (e.g., $d_{AB} = 0.982$). The \"Prior\" in the formula is the **function value of the probability density function (PDF)** of $\\text{Normal}(0, 1000)$ at the point $0.982$. Similarly, the \"Likelihood\" is the probability of seeing the data given this guess (a single number). MCMC multiplies these two numbers to score the current guess.\n:::\n\n```{=html}\n<!-- \n 【学派思辨】似然与先验相乘的实际物理意义\n本质上，这是两个概率密度（Density）在相乘，决定了 MCMC 采样的“方向”和“驻留时间”：\n\n1. 似然（Likelihood）：\n   反映“数据”的话语权。即在当前参数取值下，生成我们观察到的这组真实数据的概率。\n2. 先验（Prior）：\n   反映“背景知识”的话语权。即在未看数据前，我们根据经验或常识认为该参数取值的概率。\n\n两者相乘的博弈逻辑：\n- 似然低 x 先验高：背景知识认为很可能，但无法解释现实数据。这取决于两者的“拉扯”力道：如果先验只是微弱偏好，采样会变稀疏；但若先验极强，它甚至能压过低似然，在该区域强行拉�<!--\n\n【逻辑思辨】Stan 能完全替代 BUGS/JAGS 吗？\n不能简单地认为 Stan 可以完全替代 BUGS/JAGS。Stan 虽强，但有一个致命弱点：无法直接处理“离散未知参数”（Discrete Parameters）。\n\n举两个具体的 HEOR/临床场景：\n\n1. 分类缺失数据（Categorical Missing Data）：\n- 场景：在 NMA 中，需要调整一个二分类协变量（如患者是否吸烟，1=是，0=否）。但部分患者数据缺失。\n- 离散变量：在 BUGS/JAGS 中，可以直接把缺失的“吸烟状态”设为未知的离散参数（0 或 1），模型在游走时会顺便为这些患者“猜”出他们到底是 0 还是 1。\n- Stan 的困难：因为 0 或 1 离散变量不连续、无法求导，所以 Stan 无法直接对离散参数进行采样。程序员必须在数学上把“吸烟”和“不吸烟”的两种可能性用概率加权求和，把离散变量从似然函数中消去（边缘化，Marginalize）。\n\n2. 潜在亚组分类（Latent Subgroup Classification）：\n- 场景：假设某药物对一部分患者极有效，对另一部分完全无效。你怀疑人群存在两个“潜在亚组”，但临床上无法直接区分他们。\n- 离散变量：我们可以为每个患者引入一个隐藏变量（0 代表隐性无效组，1 代表隐性有效组）。这个 0 或 1 就是离散参数。\n- Stan 的困难：Stan 无法直接为每个患者采样他是属于 0 还是 1。\n\n这个变量是我们最终要估计的参数吗？\n- 在数学定义上是。在贝叶斯框架下，任何未知量（包括缺失值、隐藏状态）都是参数。\n- 但在业务目标上通常不是，它们是“隐变量”或“干扰参数”。我们真正关心的依然是“药物的真实疗效”（连续参数）。但为了准确估计疗效，模型必须处理掉这些离散的 0 或 1。\n\n总结：\n1. BUGS/JAGS：基于 Gibbs 采样，可以轻松处理离散变量。\n2. Stan：基于梯度的 HMC 算法，无法直接采样离散变量，必须进行复杂的数学“边缘化”处理。\n因此，对于绝大多数 HEOR 连续参数模型，Stan 完胜；但对于包含复杂离散隐变量的模型，BUGS/JAGS 仍有优势。\n-->\n```\n\n### The Iterative Algorithm and Posterier.\n\n1.  **Proposal**: The engine guesses values for the parameters.\n    - Suppose it guesses: $\\mu_1=-1.386, \\mu_2=-1.386, \\mu_3=-0.847, d_{AB}=0.982, d_{AC}=1.386$.\n2.  **Derivation**: It calculates $d_{BC} = 1.386 - 0.982 = 0.404$ (forced by consistency).\n3.  **Likelihood Calculation**: It calculates the probability of seeing our mock data given these guesses:\n    - For Study 1: $p_{11} = \\text{logit}^{-1}(-1.386) = 0.20$. $r_{11}=20$ fits perfectly!\n    - For Study 3: $p_{31} = \\text{logit}^{-1}(-0.847) = 0.30$. $r_{31}=30$ fits perfectly!\n4.  **Acceptance**: If the guessed values make the data highly probable, the engine accepts them and records them. If not, it might reject them.\n5.  The engine repeats this **thousands of times** (e.g., 50,000 iterations).\n6.  After 50,000 steps, we don't get single numbers. We get thousands of recorded values for $d_{AB}, d_{AC}$, and the derived $d_{BC}$. This is the simulated Posterier distribution.\n    - The **median** of the recorded values for $d_{AB}$ becomes our pooled estimate.\n    - The 2.5th and 97.5th percentiles become our **95% Credible Interval (CrI)**.\n\n### Model Implementation: BUGS/JAGS & Stan\n\nHere we present the implementation of our Fixed Effects NMA model in both the traditional BUGS/JAGS language and the modern Stan language, along with the R code to call them.\n\n#### BUGS/JAGS Implementation\n\nHere is the actual code used to run this simulation in JAGS:\n\n::: {.callout-note collapse=\"true\" appearance=\"minimal\"}\n# JAGS nma_model.txt\n\n``` {.R .bugs}\nmodel {\n  \n  for (j in 1:3) { # <1> \n    for (k in 1:2) { # <2> \n      r[j,k] ~ dbin(p[j,k], n[j,k])\n      logit(p[j,k]) <- mu[j] + delta[j,k] # <3>\n    }\n    \n    delta[j,1] <- 0 # <4>\n  }  \n  # Consistency Equations (Fixed Effects)\n  delta[1,2] <- d_AB\n  delta[2,2] <- d_AC\n  delta[3,2] <- d_AC - d_AB # <5>\n  # Priors\n  for (j in 1:3) {\n    mu[j] ~ dnorm(0, 0.0001) # <6>\n  }\n  d_AB ~ dnorm(0, 0.0001)\n  d_AC ~ dnorm(0, 0.0001)\n  \n  OR_AB <- exp(d_AB) # <7>\n  OR_AC <- exp(d_AC)\n  OR_BC <- exp(d_AC - d_AB)\n}\n```\n\n1.  3 studies\n2.  2 arms per study\n3.  Likelihood\n4.  Define delta relative to arm 1\n5.  This is d_BC\n6.  The second parameter is Precision (1/Variance). So this is a no information prior.\n7.  Derived parameters for output\n:::\n\n```{=html}\n<!--\n【操作指南】如何在 R 中运行上述 BUGS 代码？\n很多初学者会误以为可以直接在 R 脚本中运行 BUGS 代码。实际上，R 无法直接解析 BUGS 语言。\n正确的工作流是：\n1. 头部加载：在 R 脚本开头写 `library(rjags)`。\n2. 保存代码：将上述 `model { ... }` 块的代码复制并保存为一个独立的纯文本文件（如 `nma_model.txt`）。\n3. 传参调用：在 R 中使用 `jags.model(file = \"nma_model.txt\", ...)` 读取该文件。\n\n这样，R 只是作为一个“搬运工”和“控制器”，把数据和模型文件发给后台的 JAGS 引擎去计算。\n-->\n```\n\nTo run this model in R, you would use the `rjags` package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rjags)\n\n# Prepare the data\ndata_list <- list(\n    r = matrix(c(20, 40, 10, 30, 15, 20), nrow = 3, byrow = TRUE),\n    n = matrix(c(100, 100, 100, 100, 100, 100), nrow = 3, byrow = TRUE)\n)\n\n# Initialize the model\njags_model <- jags.model(\n    file = \"/Users/xiaogezhang/AntigravityLocal/CareerShowcaseGithub/HEOR-Technical-Portfolio/scratch/CareerTransferZXG/08_Practice_Drafts/05_NMA_Technical_Prep/nma_model.txt\",\n    data = data_list,\n    n.chains = 3,\n    n.adapt = 1000,\n    quiet = TRUE\n)\n\n# Sample from the posterior\nsamples <- coda.samples(\n    model = jags_model,\n    variable.names = c(\"d_AB\", \"d_AC\", \"OR_AB\", \"OR_AC\", \"OR_BC\"),\n    n.iter = 10000\n)\n\nsummary(samples)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nIterations = 1001:11000\nThinning interval = 1 \nNumber of chains = 3 \nSample size per chain = 10000 \n\n1. Empirical mean and standard deviation for each variable,\n   plus standard error of the mean:\n\n       Mean     SD Naive SE Time-series SE\nOR_AB 2.829 0.8028 0.004635       0.013432\nOR_AC 4.122 1.3435 0.007757       0.024485\nOR_BC 1.510 0.4724 0.002727       0.006338\nd_AB  1.001 0.2771 0.001600       0.004612\nd_AC  1.367 0.3118 0.001800       0.005662\n\n2. Quantiles for each variable:\n\n        2.5%    25%   50%   75% 97.5%\nOR_AB 1.5907 2.2541 2.719 3.286 4.713\nOR_AC 2.1750 3.1735 3.908 4.807 7.395\nOR_BC 0.7973 1.1737 1.438 1.764 2.641\nd_AB  0.4642 0.8128 1.000 1.190 1.550\nd_AC  0.7770 1.1548 1.363 1.570 2.001\n```\n\n\n:::\n:::\n\n\n#### Stan Implementation\n\nThe exact same functionality can be implemented in Stan. Notice that Stan uses standard deviation instead of precision in its normal distribution, and uses vectorized operations.\n\n::: {.callout-note collapse=\"true\" appearance=\"minimal\"}\n# STAN nma_model.stan\n\n``` stan\ndata {\n  int<lower=1> J; // Number of studies\n  int r[J, 2];    // Events\n  int n[J, 2];    // Total patients\n}\n\nparameters {\n  real mu[J];     // Study baselines\n  real d_AB;      // Effect of B vs A\n  real d_AC;      // Effect of C vs A\n}\n\ntransformed parameters {\n  real delta[J, 2];\n  // Study 1: A vs B\n  delta[1, 1] = 0;\n  delta[1, 2] = d_AB;\n  // Study 2: A vs C\n  delta[2, 1] = 0;\n  delta[2, 2] = d_AC;\n  // Study 3: B vs C\n  delta[3, 1] = 0;\n  delta[3, 2] = d_AC - d_AB; // Consistency constraint\n}\n\nmodel {\n  mu ~ normal(0, 100); # <1>\n  d_AB ~ normal(0, 100);\n  d_AC ~ normal(0, 100);\n  for (j in 1:J) {\n    for (k in 1:2) {\n      r[j, k] ~ binomial_logit(n[j, k], mu[j] + delta[j, k]); # <2>\n    }\n  }\n}\n\ngenerated quantities {\n  real OR_AB = exp(d_AB);\n  real OR_AC = exp(d_AC);\n  real OR_BC = exp(d_AC - d_AB);\n}\n```\n\n1.  Priors (Stan uses standard deviation, so 100 means variance 10000)\n2.  Likelihood\n:::\n\nTo run this model in R, you would use the `rstan` package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rstan)\n\n# Prepare data\nstan_data <- list(\n    J = 3,\n    r = matrix(c(20, 40, 10, 30, 15, 20), nrow = 3, byrow = TRUE),\n    n = matrix(c(100, 100, 100, 100, 100, 100), nrow = 3, byrow = TRUE)\n)\n\n# Run the model\nfit <- stan(\n    file = \"/Users/xiaogezhang/AntigravityLocal/CareerShowcaseGithub/HEOR-Technical-Portfolio/scratch/CareerTransferZXG/08_Practice_Drafts/05_NMA_Technical_Prep/nma_model.stan\",\n    data = stan_data,\n    chains = 3,\n    iter = 2000,\n    warmup = 1000,\n    refresh = 0\n)\n\n# Extract results\nprint(fit, pars = c(\"d_AB\", \"d_AC\", \"OR_AB\", \"OR_AC\", \"OR_BC\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInference for Stan model: anon_model.\n3 chains, each with iter=2000; warmup=1000; thin=1; \npost-warmup draws per chain=1000, total post-warmup draws=3000.\n\n      mean se_mean   sd 2.5%  25%  50%  75% 97.5% n_eff Rhat\nd_AB  1.00    0.01 0.28 0.45 0.82 1.00 1.19  1.55  1359    1\nd_AC  1.36    0.01 0.30 0.78 1.16 1.36 1.57  1.97  1433    1\nOR_AB 2.83    0.02 0.80 1.56 2.26 2.72 3.28  4.70  1331    1\nOR_AC 4.10    0.03 1.28 2.17 3.19 3.90 4.82  7.14  1475    1\nOR_BC 1.50    0.01 0.47 0.80 1.17 1.44 1.76  2.61  1863    1\n\nSamples were drawn using NUTS(diag_e) at Sat May  9 22:48:47 2026.\nFor each parameter, n_eff is a crude measure of effective sample size,\nand Rhat is the potential scale reduction factor on split chains (at \nconvergence, Rhat=1).\n```\n\n\n:::\n:::\n\n\n```{=html}\n<!--\n【审计要点】注意 BUGS 代码中的精度（Precision）\n在 BUGS/JAGS 中，`dnorm(mean, precision)` 里的第二个参数是**精度**（方差的倒数），而不是标准差或方差。所以 `0.0001` 代表方差是 `10000`，这是一个非常宽的无信息先验。\n-->\n```\n\n::: {.callout-note collapse=\"true\"}\n# Comparison: BUGS vs JAGS vs Stan\n\nWhile the code above is written in the BUGS/JAGS language, it is helpful to understand the differences between the three major MCMC engines used in HEOR:\n\n- **BUGS (WinBUGS / OpenBUGS)**: The pioneer. It uses **Gibbs sampling**. It is the oldest and can be slow or unstable for complex models.\n- **JAGS (Just Another Gibbs Sampler)**: A C++ reimplementation of BUGS. It uses the same language syntax but is cross-platform and more stable. It is currently the most widely used engine for traditional NMA (e.g., in NICE DSU technical support documents).\n- **Stan**: The modern standard. It uses **Hamiltonian Monte Carlo (HMC)** and the **No-U-Turn Sampler (NUTS)**. Instead of random walking, it uses the gradient of the log-posterior to \"glide\" efficiently through the parameter space. It is much faster and more reliable for complex, high-dimensional models (like ML-NMR), though it requires compiling the model to C++ first.\n:::\n\n::: {.callout-note collapse=\"true\"}\n# BUGS/JAGS: Software or Language?\n\nBUGS and JAGS are both **standalone software (computational engines)** and **modeling languages**. - **BUGS** (WinBUGS/OpenBUGS) has its own language syntax and originally had a GUI. - **JAGS** is a command-line program with no GUI. In modern HEOR practice, they are almost always used as \"plugins\" called from R (via packages like `rjags` or `R2jags`), rather than run standalone.\n:::\n\n```{=html}\n<!--\n【逻辑思辨】Stan 能完全替代 BUGS/JAGS 吗？\n不能简单地认为 Stan 可以完全替代 BUGS/JAGS。Stan 虽强，但有一个致命弱点：无法直接处理“离散未知参数”（Discrete Parameters）。\n\n举个具体的 HEOR 场景（分类缺失数据）：\n- 场景：在 NMA 中，需要调整一个二分类协变量（如患者是否吸烟，1=是，0=否）。但部分患者数据缺失。\n- 离散变量：在 BUGS/JAGS 中，可以直接把缺失的“吸烟状态”设为未知的离散参数（0 或 1），模型在游走时会顺便为这些患者“猜”出他们到底是 0 还是 1。\n- Stan 的困难：因为 0 或 1 离散变量不连续、无法求导，所以 Stan 无法直接对离散参数进行采样。程序员必须在数学上把“吸烟”和“不吸烟”的两种可能性用概率加权求和，把离散变量从似然函数中消去（边缘化，Marginalize）。\n\n这个变量是我们最终要估计的参数吗？\n- 在数学定义上是。在贝叶斯框架下，任何未知量（包括缺失值、隐藏状态）都是参数。\n- 但在业务目标上通常不是，它们是“隐变量”或“干扰参数”。我们真正关心的依然是“药物的真实疗效”（连续参数）。但为了准确估计疗效，模型必须处理掉这些离散的 0 或 1。\n\n总结与跑车比喻：\n1. BUGS/JAGS：基于 Gibbs 采样，可以轻松处理离散变量。就像一辆老款吉普车，虽然慢，但能开过乱石泥泞路段（离散变量）。\n2. Stan：基于梯度的 HMC 算法，无法直接采样离散变量，必须进行复杂的数学“边缘化”处理。就像一辆性能极强的现代跑车，在 95% 的绝大多数公路（连续参数模型）上降维打击吉普车，但在泥泞路段会趴窝。\n\n因此，在业务层面上，Stan 几乎完全涵盖并超越了 BUGS/JAGS 的功能，正在成为新的行业标准；但在底层技术特性上，对于包含复杂离散隐变量的模型，BUGS/JAGS 仍有其不可替代的优势。\n-->\n```\n\n### Convergence Diagnostics\n\nWhen auditing an NMA, always verify the following MCMC diagnostics to ensure the posterior simulation has converged:\n\n- **R-hat (Gelman-Rubin Diagnostic)**: Must be $< 1.05$ (or strictly $< 1.01$) for all parameters. It compares between-chain and within-chain variance. Values close to 1 indicate convergence.\n- **Trace Plots**: Chains should look like \"fat hairy caterpillars,\" showing good mixing and no trends.\n- **Auto-correlation**: Should drop to zero quickly as the lag increases. High autocorrelation means the sampler is moving slowly and requires more iterations or thinning.\n- **Effective Sample Size (ESS)**: Should be sufficiently large (typically $> 400$, ideally $> 1000$). For calculating tail probabilities (like ranking probabilities or SUCRA), a larger ESS is required to ensure stability.\n\nIf the model does not converge, potential solutions include: \n\n- Increasing the number of burn-in and iteration steps. \n- Checking for data entry errors or extremely sparse data (zero cells). \n- Using more informative priors to stabilize the model. \n- Reparameterizing the model (e.g., non-centered parameterization in Stan).\n\n## Results & Interpretation: The League Table {#5-results--interpretation-the-league-table}\n\nAfter running the MCMC, we combine the direct and indirect evidence to get the final pooled estimates.\n\n### The League Table (Median OR and 95% CrI)\n\n| Treatment A         | 2.67 (1.5, 4.8)     | 4.00 (2.2, 7.3) |\n|:--------------------|:--------------------|:----------------|\n| **0.37 (0.2, 0.7)** | Treatment B         | 1.50 (0.8, 2.7) |\n| **0.25 (0.1, 0.5)** | **0.67 (0.4, 1.2)** | Treatment C     |\n\n*How to read*: The upper-right triangle shows the OR of the column treatment vs the row treatment. The lower-left triangle shows the inverse.\n\n### Probability of Being Best\n\nBayesian NMA allows us to calculate the probability that each treatment is the most effective.\n\n- **Treatment C**: \\~75%\n- **Treatment B**: \\~24%\n- **Treatment A**: \\~1%\n\n## Strategic Q&A: Interview Prep {#6-strategic-qa-interview-prep}\n\n::: {.callout-important collapse=\"true\"}\n# What is the difference between a Consistency Model and an Unrelated Mean Effects (UME) model?\n\nA consistency model forces all loops to close (e.g., $d_{BC} = d_{AC} - d_{AB}$). A UME model relaxes this assumption and estimates all relative effects independently. We compare the two to check for network inconsistency.\n:::\n\n::: {.callout-important collapse=\"true\"}\n# How do you handle a disconnected network in Standard NMA?\n\nStandard NMA cannot handle disconnected networks. You must either bridge the gap with a common comparator (if possible) or use population adjustment methods like MAIC or ML-NMR if you have IPD for at least one trial.\n:::\n\n## Strategic Conclusion {#7-strategic-conclusion}\n\nMastering Standard Bayesian NMA requires understanding the interplay between direct and indirect evidence. This minimal case demonstrates that when data forms a loop, consistency must be verified.\n\n**Guide Authored by**: Antigravity (Advanced Agentic Coding)\\\n**Methodological Reference**: NICE DSU TSD 2 & 4",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}