{
  "hash": "163e4a3ee0ab5c02fbab5b85811d5144",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Targeted Maximum Likelihood Estimation & Sensitivity Analysis\"\nsubtitle: \"Doubly Robust Causal Inference & Unmeasured Confounding Audits\"\nauthor: \"Xiaoge Zhang, PhD\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    code-summary: \"R Code\"\n    number-sections: true\n    reference-location: margin\n---\n\n*Advanced Causal Inference for External Control Arms and Observational Real-World Evidence*\n\n## Introduction: The Limits of Single Robustness & AIPW\n\nIn health technology assessment (HTA), observational real-world data (RWD) is frequently used to construct External Control Arms (ECAs) when randomized controlled trials (RCTs) are unfeasible. Standard propensity score adjustments, such as Propensity Score Matching (PSM) and Inverse Probability Treatment Weighting (IPTW), rely entirely on the correct specification of the treatment assignment model:\n$$g(X) = P(D = 1 \\mid X)$$\n\nIf the propensity score model **omits crucial confounders** or **misspecifies their functional forms (e.g., ignoring non-linearities or interactions)**, these single-robust estimators yield biased estimates of the treatment effect.\n\n### Doubly Robust Estimators\n\nTo address this, doubly robust estimators combine the treatment model with an outcome regression model. For a detailed algebraic proof of the double robustness property, see the [AIPW section in Page 2](./02_PSM_IPTW_AIPW.qmd#sec-aipw):\n$$m(D, X) = E[Y \\mid D, W]$$\n\nThis ensures that the treatment effect estimate is unbiased if *either* the treatment model *or* the outcome model is correctly specified.\n\n### Why TMLE Over AIPW?\n\nWhile Augmented Inverse Probability Weighting (AIPW) is also doubly robust, **Targeted Maximum Likelihood Estimation (TMLE)**—developed by Mark van der Laan and colleagues—is preferred in HTA and regulatory submissions for several reasons:\n\n- **Substitution Estimator (Respecting Bounds)**: AIPW is an influence function-based estimator. Because it adds a weighted residual correction, it can yield predicted counterfactual values that lie outside the physical bounds of the outcome space. For example, in binary or time-to-event outcomes, **AIPW can predict survival probabilities that are greater than $1$ or less than $0$.** TMLE is a *substitution estimator*, which mathematically guarantees that the estimated probabilities respect the natural bounds of the parameter space (i.e., restricting survival estimates strictly within $[0, 1]$).\n- **Semiparametric Efficiency**: TMLE is asymptotically **efficient**, meaning it achieves the lowest possible variance (the semiparametric efficiency bound) among all regular estimators when both models are correctly specified.\n- **Ensemble Integration**: TMLE natively integrates machine learning ensembles (like `SuperLearner`) to model **both** the outcome and treatment mechanisms, **minimizing the risk of model misspecification bias**.\n\n## The 5-Step TMLE Algorithm with Integrated R Code\n\nTMLE operates by taking an initial estimate of the outcome regression and \"targeting\" it using the treatment assignment model to directly optimize the parameter of interest (e.g., the Average Treatment Effect, ATE).\n\nThe mathematical implementation follows five steps. To illustrate the mechanics transparently, we will run the manual calculations in R alongside each step using a simulated cohort ($N=500$) with baseline confounding.\n\n### Cohort Simulation Setup & Baseline Characteristics\n\nThe simulated cohort represents an observational registry of 500 patients:\n\n- **Baseline Confounders**: Age (normally distributed around 65) and ECOG performance status (binary indicator where 1 denotes poor status, with 40% prevalence).\n- **Confounding by Indication**: Older and sicker patients are preferentially prescribed the active treatment (probability of treatment increases with both age and poor ECOG status).\n- **Survival Outcome**: 1-year survival probability is driven by both confounders (older age and poor ECOG status lower survival) and treatment (which increases survival by a true risk difference of +15.5%).\n\nThe baseline characteristics table below highlights the treatment assignment bias: older, sicker patients are heavily concentrated in the treated group, which will mask the true efficacy in naive unadjusted analyses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(WeightIt)\nlibrary(survey)\nlibrary(tmle)\nlibrary(SuperLearner)\nlibrary(EValue)\nlibrary(AIPW)\n\nset.seed(2026)\nn <- 500\n\n# 1. Simulate Confounders\nage <- rnorm(n, mean = 65, sd = 10)\necog <- rbinom(n, 1, 0.4) # 1 = Poor performance status\n\n# 2. Simulate Treatment Assignment (Confounding by Indication)\n# Elderly and sicker patients are more likely to receive the treatment (D = 1)\nps_true <- plogis(-2 + 0.05 * age + 1.2 * ecog)\ntreatment <- rbinom(n, 1, ps_true)\n\n# 3. Simulate Survival Outcome (1-Year Survival)\n# True Treatment Effect (Risk Difference) = +15.5% (coefficient = 0.8 in log-odds scale)\ny_prob_1 <- plogis(1 - 0.03 * age - 1.0 * ecog + 0.8 * 1)\ny_prob_0 <- plogis(1 - 0.03 * age - 1.0 * ecog + 0.8 * 0)\ntrue_ate <- mean(y_prob_1) - mean(y_prob_0)\n\nsurvival_1yr <- ifelse(treatment == 1,\n                       rbinom(n, 1, y_prob_1),\n                       rbinom(n, 1, y_prob_0))\n\ndf <- data.frame(age, ecog, treatment, survival_1yr)\n\n# Calculate Naive (Unadjusted) Estimate\nnaive_treated <- mean(df$survival_1yr[df$treatment == 1])\nnaive_control <- mean(df$survival_1yr[df$treatment == 0])\nnaive_ate <- naive_treated - naive_control\n\n# Construct baseline descriptive statistics\nget_stats <- function(sub_df) {\n  n_sub <- nrow(sub_df)\n  mean_age <- mean(sub_df$age)\n  sd_age <- sd(sub_df$age)\n  n_ecog <- sum(sub_df$ecog == 1)\n  pct_ecog <- (n_ecog / n_sub) * 100\n  n_surv <- sum(sub_df$survival_1yr == 1)\n  pct_surv <- (n_surv / n_sub) * 100\n  \n  c(\n    sprintf(\"%d\", n_sub),\n    sprintf(\"%.2f (%.2f)\", mean_age, sd_age),\n    sprintf(\"%d (%.1f%%)\", n_ecog, pct_ecog),\n    sprintf(\"%d (%.1f%%)\", n_surv, pct_surv)\n  )\n}\n\ndesc_tbl <- data.frame(\n  Characteristic = c(\"Sample Size (N)\", \"Age, Mean (SD)\", \"ECOG Status: Poor (1), N (%)\", \"Observed 1-Year Survival, N (%)\"),\n  \"Control (D = 0)\" = get_stats(df[df$treatment == 0, ]),\n  \"Treated (D = 1)\" = get_stats(df[df$treatment == 1, ]),\n  \"Total Cohort\" = get_stats(df),\n  check.names = FALSE,\n  stringsAsFactors = FALSE\n)\n\nknitr::kable(desc_tbl, caption = \"Baseline Characteristics & Raw Outcomes of the Simulated Cohort\", align = \"lrrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Baseline Characteristics & Raw Outcomes of the Simulated Cohort\n\n|Characteristic                  | Control (D = 0)| Treated (D = 1)|  Total Cohort|\n|:-------------------------------|---------------:|---------------:|-------------:|\n|Sample Size (N)                 |              84|             416|           500|\n|Age, Mean (SD)                  |   62.47 (10.45)|   65.97 (10.10)| 65.38 (10.24)|\n|ECOG Status: Poor (1), N (%)    |      18 (21.4%)|     177 (42.5%)|   195 (39.0%)|\n|Observed 1-Year Survival, N (%) |      25 (29.8%)|     163 (39.2%)|   188 (37.6%)|\n\n\n:::\n:::\n\n\n---\n\n### Step 1: Initial Estimation of the Outcome Regression ($Q_0$)\n\nWe estimate the conditional expectation of the outcome $Y$ given treatment $D$ and baseline covariates $W$:\n$$Q_0(D, W) = E[Y \\mid D, W]$$\n\nWe fit a logistic regression model^[Specifying `family = binomial` in R's `glm()` function defaults to a logistic regression model (Logit Model) to model binary outcome probabilities.] for $Y$ and generate two counterfactual predicted values for each individual $i$:\n\n- The predicted outcome under treatment: $Q_0(1, W_i)$\n- The predicted outcome under control: $Q_0(0, W_i)$\n\nTo prevent boundary logit explosions, the initial outcome predictions are bounded to $[0.005, 0.995]$ (corresponding to the default `alpha = 0.995` threshold).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the initial outcome regression model (Q0)\nfit_Q <- glm(survival_1yr ~ treatment + age + ecog, family = binomial, data = df)\n\n# Predict counterfactual outcomes under treatment and control\nQ0_0_raw <- predict(fit_Q, newdata = data.frame(treatment = 0, age, ecog), type = \"response\")\nQ0_1_raw <- predict(fit_Q, newdata = data.frame(treatment = 1, age, ecog), type = \"response\")\n\n# Bound predictions to [0.005, 0.995]\nQ0_0 <- pmin(pmax(Q0_0_raw, 0.005), 0.995)\nQ0_1 <- pmin(pmax(Q0_1_raw, 0.005), 0.995)\n\n# Factual prediction under actual observed treatment (no counterfactual component).\n# Because we only observe outcome Y under the actual treatment A, we must use Q0_A as the baseline offset\n# to calculate residuals and fit the fluctuation parameter (epsilon) in Step 4.\nQ0_A <- ifelse(treatment == 1, Q0_1, Q0_0)\n\n# Format summary table\nq0_summary <- data.frame(\n  Metric = c(\"Mean Prediction\", \"Minimum Prediction\", \"Maximum Prediction\"),\n  \"Control (Q0_0)\" = c(mean(Q0_0), min(Q0_0), max(Q0_0)),\n  \"Treatment (Q0_1)\" = c(mean(Q0_1), min(Q0_1), max(Q0_1)),\n  check.names = FALSE\n)\nknitr::kable(q0_summary, digits = 4, caption = \"Summary of Initial Outcome Regression Predictions (Q0)\", align = \"lrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Summary of Initial Outcome Regression Predictions (Q0)\n\n|Metric             | Control (Q0_0)| Treatment (Q0_1)|\n|:------------------|--------------:|----------------:|\n|Mean Prediction    |         0.2612|           0.4013|\n|Minimum Prediction |         0.1164|           0.2051|\n|Maximum Prediction |         0.3899|           0.5558|\n\n\n:::\n:::\n\n\n---\n\n### Step 2: Estimation of the Propensity Score ($g_0$)\n\nWe estimate the probability of treatment assignment given covariates:\n$$g(W) = P(D = 1 \\mid W)$$\n\nWe fit a logistic regression model for treatment assignment to predict propensity scores, and apply a dynamic lower bound threshold^[If not specified, the `tmle` package adaptively calculates the propensity score lower bound based on the sample size: $$\\text{gbound\\_lower} = \\frac{5}{\\sqrt{n} \\cdot \\ln(n)}$$ For $N=500$, the lower bound is approximately `0.03598`. This bound is applied independently to the propensity scores of the treated ($g(W)$) and control ($1 - g(W)$) groups.] to guarantee that inverse weights do not blow up.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit propensity score model\nfit_g <- glm(treatment ~ age + ecog, family = binomial, data = df)\ng1W_raw <- predict(fit_g, type = \"response\")\n\n# Calculate dynamic lower bound: 5 / (sqrt(n) * log(n))\ngbound_lower <- 5 / (sqrt(n) * log(n))\n\n# Apply bounding independently for g1W and g0W\ng1W <- pmax(g1W_raw, gbound_lower)\ng0W <- pmax(1 - g1W_raw, gbound_lower)\n\n# Format summary table\ng_summary <- data.frame(\n  Metric = c(\"Lower Bound Value\", \"Mean Propensity Score\", \"Minimum Propensity Score\"),\n  \"g1W (Treated)\" = c(gbound_lower, mean(g1W), min(g1W)),\n  \"g0W (Control)\" = c(gbound_lower, mean(g0W), min(g0W)),\n  check.names = FALSE\n)\nknitr::kable(g_summary, digits = 4, caption = \"Summary of Bounded Propensity Scores\", align = \"lrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Summary of Bounded Propensity Scores\n\n|Metric                   | g1W (Treated)| g0W (Control)|\n|:------------------------|-------------:|-------------:|\n|Lower Bound Value        |        0.0360|         0.036|\n|Mean Propensity Score    |        0.8320|         0.168|\n|Minimum Propensity Score |        0.6019|         0.036|\n\n\n:::\n:::\n\n\n---\n\n### Step 3: Computation of the Clever Covariate ($H$)\n\nWe construct the **Clever Covariates** $H_1(W)$ and $H_0(W)$ representing the inverse probability weights adjusted for treatment received:\n\n- For treated: $H_1(W) = \\frac{D}{g(W)}$\n- For controls: $H_0(W) = \\frac{1 - D}{1 - g(W)}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate clever covariates\nH1W <- treatment / g1W\nH0W <- (1 - treatment) / g0W\n\n# Display first few rows\nh_tbl <- data.frame(\n  Patient = 1:5,\n  Treatment = treatment[1:5],\n  \"g1W (Treated)\" = g1W[1:5],\n  \"g0W (Control)\" = g0W[1:5],\n  \"H0W (Clever Control)\" = H0W[1:5],\n  \"H1W (Clever Treated)\" = H1W[1:5],\n  check.names = FALSE\n)\nknitr::kable(h_tbl, digits = 4, caption = \"Clever Covariates (First 5 Patients)\", align = \"lrrrrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Clever Covariates (First 5 Patients)\n\n|Patient | Treatment| g1W (Treated)| g0W (Control)| H0W (Clever Control)| H1W (Clever Treated)|\n|:-------|---------:|-------------:|-------------:|--------------------:|--------------------:|\n|1       |         1|        0.9247|        0.0753|                    0|               1.0814|\n|2       |         1|        0.7171|        0.2829|                    0|               1.3946|\n|3       |         1|        0.9148|        0.0852|                    0|               1.0931|\n|4       |         1|        0.7825|        0.2175|                    0|               1.2779|\n|5       |         1|        0.7456|        0.2544|                    0|               1.3411|\n\n\n:::\n:::\n\n\n---\n\n### Step 4: The Fluctuation (Update) Step\n\nWe update the initial outcome prediction $Q_0$ by fitting a logistic regression of the observed outcome $Y$ on the Clever Covariates $H_0(W)$ and $H_1(W)$ without an intercept^[In R's `glm()`, starting the formula with `-1` (e.g., `survival_1yr ~ -1 + H0W + H1W`) removes the default intercept term. This is critical because the initial prediction `logit(Q0)` (the offset) already contains the baseline intercept. Adding a new intercept would distort the targeted bias correction and violate the TMLE framework.], using the logit of the initial prediction $Q_0(D, W)$ as a fixed offset^[An offset-only GLM refers to a model where a covariate is entered with a coefficient forced to 1 (using `offset = qlogis(Q0_A)` on the logit scale). Here, it locks the initial prediction `Q0_A` in place, allowing the regression to estimate only the residual fluctuation parameters (epsilon) that minimize bias.]:\n$$\\text{logit}\\left(Q_1(D, W)\\right) = \\text{logit}\\left(Q_0(D, W)\\right) + \\epsilon_0 \\cdot H_0(W) + \\epsilon_1 \\cdot H_1(W)$$\n\nFitting this regression via Maximum Likelihood estimates the fluctuation parameters $\\epsilon_0$ and $\\epsilon_1$, which represent the residual bias correction. We then update the counterfactual predictions and bound them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit fluctuation regression (offset-only model)\nfit_eps <- glm(survival_1yr ~ -1 + H0W + H1W, offset = qlogis(Q0_A), family = binomial)\neps <- coef(fit_eps)\n\n# Update counterfactual predictions\nQ1_0 <- plogis(qlogis(Q0_0) + eps[\"H0W\"] / g0W)\nQ1_1 <- plogis(qlogis(Q0_1) + eps[\"H1W\"] / g1W)\n\n# Bound final updated predictions to [0.005, 0.995]\nQ1_0 <- pmin(pmax(Q1_0, 0.005), 0.995)\nQ1_1 <- pmin(pmax(Q1_1, 0.005), 0.995)\n\n# Format epsilon table\neps_tbl <- data.frame(\n  Parameter = c(\"epsilon_0 (Control, H0W)\", \"epsilon_1 (Treatment, H1W)\"),\n  Estimate = c(eps[\"H0W\"], eps[\"H1W\"]),\n  \"Std. Error\" = summary(fit_eps)$coefficients[, \"Std. Error\"],\n  \"z-value\" = summary(fit_eps)$coefficients[, \"z value\"],\n  \"p-value\" = summary(fit_eps)$coefficients[, \"Pr(>|z|)\"],\n  check.names = FALSE\n)\nknitr::kable(eps_tbl, digits = 6, caption = \"Estimated Fluctuation Coefficients (Epsilons)\", align = \"lrrrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Estimated Fluctuation Coefficients (Epsilons)\n\n|    |Parameter                  |  Estimate| Std. Error|   z-value|  p-value|\n|:---|:--------------------------|---------:|----------:|---------:|--------:|\n|H0W |epsilon_0 (Control, H0W)   | -0.030047|   0.043796| -0.686071| 0.492668|\n|H1W |epsilon_1 (Treatment, H1W) | -0.004577|   0.084817| -0.053966| 0.956962|\n\n\n:::\n:::\n\n\n---\n\n### Step 5: Parameter Estimation via Substitution\n\nFinally, we calculate the doubly robust ATE by averaging the updated counterfactual predictions across the sample:\n$$\\hat{ATE}_{TMLE} = \\frac{1}{n} \\sum_{i=1}^n \\left[ Q_1(1, W_i) - Q_1(0, W_i) \\right]$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate manual ATE\nate_manual <- mean(Q1_1 - Q1_0)\n```\n:::\n\n\nThe manual step-by-step TMLE yields a Risk Difference (ATE) of **0.173771**.\n\n---\n\n### Verification: Comparing Manual TMLE with the Package Output\n\nTo confirm the accuracy of our step-by-step manual implementation, we fit the ATE using the `tmle` package, turning off cross-validation (`cvQinit = FALSE`) to align the initial outcome estimation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit Package TMLE (without cross-validation for direct verification)\ntmle_fit_verify <- tmle(\n  Y             = df$survival_1yr,\n  A             = df$treatment,\n  W             = df[, c(\"age\", \"ecog\")],\n  Q.SL.library  = \"SL.glm\",\n  g.SL.library  = \"SL.glm\",\n  cvQinit       = FALSE,\n  family        = \"binomial\"\n)\n\n# Format verification comparison table\ncomparison_tbl <- data.frame(\n  Parameter = c(\"Epsilon_0 (Control Coefficient)\", \"Epsilon_1 (Treatment Coefficient)\", \"ATE Point Estimate\"),\n  \"Manual Step-by-Step\" = c(eps[\"H0W\"], eps[\"H1W\"], ate_manual),\n  \"tmle Package Output\" = c(tmle_fit_verify$epsilon[\"H0W\"], tmle_fit_verify$epsilon[\"H1W\"], tmle_fit_verify$estimates$ATE$psi),\n  \"Absolute Difference\" = c(\n    abs(eps[\"H0W\"] - tmle_fit_verify$epsilon[\"H0W\"]),\n    abs(eps[\"H1W\"] - tmle_fit_verify$epsilon[\"H1W\"]),\n    abs(ate_manual - tmle_fit_verify$estimates$ATE$psi)\n  ),\n  check.names = FALSE\n)\nknitr::kable(comparison_tbl, digits = 8, caption = \"Validation of Manual TMLE Against tmle Package\", align = \"lrrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Validation of Manual TMLE Against tmle Package\n\n|    |Parameter                         | Manual Step-by-Step| tmle Package Output| Absolute Difference|\n|:---|:---------------------------------|-------------------:|-------------------:|-------------------:|\n|H0W |Epsilon_0 (Control Coefficient)   |         -0.03004721|         -0.03004721|                   0|\n|H1W |Epsilon_1 (Treatment Coefficient) |         -0.00457726|         -0.00457726|                   0|\n|    |ATE Point Estimate                |          0.17377122|          0.17377122|                   0|\n\n\n:::\n:::\n\n\nAs demonstrated, the manual step-by-step implementation matches the `tmle` package output exactly to machine precision (absolute difference $\\approx 0$), validating the underlying mechanics of the TMLE algorithm.\n\n---\n\n## Production R Implementation Pipeline (Package-level Fit & Plots)\n\nWhile the manual walkthrough utilizes simple parametric models to illustrate the underlying mechanics, HTA submissions require production-grade models using machine learning ensembles and cross-validation to minimize misspecification bias.\n\nHere, we fit the final ATE using the `tmle` package with cross-validation (`cvQinit = TRUE`) and SuperLearner ensembles containing GLM and Mean libraries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit production-grade TMLE and suppress package-level output\nsl_lib <- c(\"SL.glm\", \"SL.mean\")\n\ntmle_fit <- suppressMessages(tmle(\n  Y             = df$survival_1yr,\n  A             = df$treatment,\n  W             = df[, c(\"age\", \"ecog\")],\n  Q.SL.library  = sl_lib,\n  g.SL.library  = sl_lib,\n  family        = \"binomial\"\n))\n\n# Extract results\ntmle_est <- tmle_fit$estimates$ATE$psi\ntmle_se  <- sqrt(tmle_fit$estimates$ATE$var.psi)\ntmle_ci  <- tmle_fit$estimates$ATE$CI\ntmle_pval <- tmle_fit$estimates$ATE$pvalue\nepsilon  <- tmle_fit$epsilon\n\n# Format TMLE parameter table\ntmle_tbl <- data.frame(\n  Parameter = c(\"Risk under Control (EY0)\", \"Risk under Exposure (EY1)\", \"Risk Difference (ATE)\"),\n  Estimate = c(tmle_fit$estimates$EY0$psi, tmle_fit$estimates$EY1$psi, tmle_est),\n  \"Std. Error\" = c(sqrt(tmle_fit$estimates$EY0$var.psi), sqrt(tmle_fit$estimates$EY1$var.psi), tmle_se),\n  \"95% LCL\" = c(tmle_fit$estimates$EY0$CI[1], tmle_fit$estimates$EY1$CI[1], tmle_ci[1]),\n  \"95% UCL\" = c(tmle_fit$estimates$EY0$CI[2], tmle_fit$estimates$EY1$CI[2], tmle_ci[2]),\n  \"p-value\" = c(NA, NA, tmle_pval),\n  check.names = FALSE\n)\n\n# Round values for display\ntmle_tbl[, 2:5] <- round(tmle_tbl[, 2:5], 4)\ntmle_tbl[3, 6] <- format.pval(tmle_pval, eps = 0.001, digits = 3)\n\nknitr::kable(tmle_tbl, caption = \"Production TMLE Results with SuperLearner & Cross-Validation\", align = \"lrrrrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Production TMLE Results with SuperLearner & Cross-Validation\n\n|Parameter                 | Estimate| Std. Error| 95% LCL| 95% UCL| p-value|\n|:-------------------------|--------:|----------:|-------:|-------:|-------:|\n|Risk under Control (EY0)  |   0.2302|     0.0419|  0.1481|  0.3122|      NA|\n|Risk under Exposure (EY1) |   0.4004|     0.0241|  0.3531|  0.4477|      NA|\n|Risk Difference (ATE)     |   0.1702|     0.0477|  0.0768|  0.2637|  <0.001|\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Interpretation of the Fluctuation Parameters\nThe estimated fluctuation parameters under the production fit are $\\epsilon_0 = $ **-0.037002** (Control) and $\\epsilon_1 = $ **0.005426** (Treated). These non-zero coefficients represent the targeted adjustments applied during the fluctuation step to remove residual treatment selection bias.\n:::\n\n### Sensitivity Analysis: E-Value Calculation\n\n#### What is the E-value?\n\nIn observational real-world evidence (RWD) studies, a major source of skepticism from HTA agencies (like NICE) is **unmeasured confounding** (selection bias due to variables not captured in the database). The **E-value**, developed by VanderWeele and Ding (2017), is a quantitative sensitivity metric that evaluates how robust an observed causal association is to unmeasured confounding. \n\nIn simple terms, the E-value answers this question: \n*\"How strong would an unmeasured confounder (like a hidden genetic mutation) need to be to completely explain away the observed survival benefit of our treatment?\"*\n\nTo completely explain away the treatment's effect, this hidden confounder must have a strong \"double-association\": it must be highly associated with whether a patient receives the treatment, **and** it must be highly associated with whether the patient survives. The E-value is the minimum value of this double-association. If no such strong confounder exists in reality, we can conclude that the observed survival benefit is truly caused by the treatment.\n\n#### How is it Calculated?\n\n##### 1. Calculating the Relative Risk from TMLE Estimates\nTMLE outputs the Average Treatment Effect (ATE) on the **Risk Difference (RD)** scale:\n$$ATE = EY_1 - EY_0$$\nwhere $EY_1$ is the expected survival rate under treatment, and $EY_0$ is the expected survival rate under control.\n\nTo calculate the Relative Risk ($RR$) required for E-value computation:\n$$RR = \\frac{EY_1}{EY_0} = \\frac{EY_0 + ATE}{EY_0}$$\n\nThe lower and upper bounds of the 95% confidence interval for the Relative Risk ($RR_{lower}$ and $RR_{upper}$) are calculated similarly by substituting the lower and upper confidence limits of the ATE:\n$$RR_{lower} = \\frac{EY_0 + ATE_{lower}}{EY_0}, \\quad RR_{upper} = \\frac{EY_0 + ATE_{upper}}{EY_0}$$\n\n##### 2. The E-value Formula\nFor an observed Relative Risk ($RR$) greater than $1$ (for protective effects like survival where we invert $RR < 1$ to $1/RR$):\n$$\\text{E-value} = RR + \\sqrt{RR \\cdot (RR - 1)}$$\n\nTo evaluate the statistical robustness of the effect, we also compute the E-value for the **lower bound** of the 95% confidence interval ($RR_{lower}$):\n$$\\text{E-value}_{\\text{lower}} = RR_{\\text{lower}} + \\sqrt{RR_{\\text{lower}} \\cdot (RR_{\\text{lower}} - 1)}$$\n\nIf $RR_{\\text{lower}} \\le 1$, the E-value for the confidence interval limit is defined as $1$ (meaning that unmeasured confounding of any strength could explain away the statistical significance, as the interval already includes the null).\n\nTo evaluate sensitivity to unmeasured confounding, we transform the Risk Difference obtained from TMLE to the Relative Risk (RR) scale and calculate the corresponding E-value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Transform Risk Difference to Relative Risk\ney0_est <- tmle_fit$estimates$EY0$psi\nrr_est  <- (ey0_est + tmle_est) / ey0_est\nrr_lo   <- (ey0_est + tmle_ci[1]) / ey0_est\nrr_hi   <- (ey0_est + tmle_ci[2]) / ey0_est\n\n# 2. Compute E-value\nev <- evalues.RR(est = rr_est, lo = rr_lo, hi = rr_hi)\nev_df <- as.data.frame(ev)\n\n# 3. Format E-value table\nev_tbl <- data.frame(\n  \"Metric / Parameter\" = c(\"Relative Risk of Treatment (RR)\", \"E-value (Treatment Effect Bound)\"),\n  \"Point Estimate\" = c(sprintf(\"%.3f\", ev_df[\"RR\", \"point\"]), sprintf(\"%.3f\", ev_df[\"E-values\", \"point\"])),\n  \"95% CI Lower Bound\" = c(sprintf(\"%.3f\", ev_df[\"RR\", \"lower\"]), sprintf(\"%.3f\", ev_df[\"E-values\", \"lower\"])),\n  \"95% CI Upper Bound\" = c(sprintf(\"%.3f\", ev_df[\"RR\", \"upper\"]), \"N/A\"),\n  check.names = FALSE\n)\n\nknitr::kable(ev_tbl, caption = \"E-Value Analysis for Unmeasured Confounding Sensitivity\", align = \"lrrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: E-Value Analysis for Unmeasured Confounding Sensitivity\n\n|Metric / Parameter               | Point Estimate| 95% CI Lower Bound| 95% CI Upper Bound|\n|:--------------------------------|--------------:|------------------:|------------------:|\n|Relative Risk of Treatment (RR)  |          1.740|              1.334|              2.146|\n|E-value (Treatment Effect Bound) |          2.874|              2.001|                N/A|\n\n\n:::\n:::\n\n\n#### How to Interpret the E-value?\n\nFor this analysis, our target outcome (1-year survival rate) represents a protective/positive effect of treatment, which we evaluate by converting the TMLE risk difference to a Relative Risk scale ($RR = 1.740$). The resulting E-value analysis is summarized in the table below.\n\nTo interpret these results:\n\n1. **Point Estimate E-value (2.87)**:\n   To completely explain away the observed point estimate of the treatment effect ($RR = 1.740$), an unmeasured confounder (or group of confounders) would need to increase the probability of both treatment assignment and 1-year survival by at least **2.87-fold** (after adjusting for the measured covariates age and ECOG status). If the association is weaker than this threshold, the observed treatment effect cannot be fully explained away.\n\n2. **95% Confidence Interval Lower Bound E-value (2)**:\n   To explain away the *statistical significance* of the treatment effect (i.e. to push the lower limit of the 95% confidence interval to $RR = 1.0$), an unmeasured confounder would need an association of at least **2-fold** with both treatment and survival. \n\n3. **Comparison with Measured Confounders**:\n   To assess clinical plausibility, we compare the E-value against the strengths of our measured confounders. In our adjusted model, poor performance status (ECOG = 1) is the strongest clinical confounder, displaying a risk association of approximately 1.8-fold. Because the unmeasured confounder would need to have an association of at least **2.87-fold** (nearly twice as strong as our strongest measured clinical predictor) and be completely uncorrelated with age and ECOG to nullify the effect, the presence of such an unmeasured confounder is highly implausible.\n\n#### E-Value Contour Visualization\n\nThe contour plot displays the relationship between the two key confounding parameters:\n- **$RR_{UD}$ (x-axis)**: The strength of association between the unmeasured confounder and treatment assignment.\n- **$RR_{UY}$ (y-axis)**: The strength of association between the unmeasured confounder and the outcome.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(ev, type = \"line\", \n     main = \"E-value Contour: Sensitivity to Unmeasured Confounding\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in plot.xy(xy, type, ...): plot type 'line' will be truncated to first\ncharacter\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](03_TMLE_and_Sensitivity_files/figure-html/evalue-plot-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n##### Understanding the Contour Curve\n\n- **The Solid Curve (Point Estimate Boundary)**: The solid black line represents the E-value boundary. Any point $(RR_{UD}, RR_{UY})$ on this line defines a combination of confounder-treatment and confounder-outcome associations that is *just strong enough* to reduce the observed Relative Risk ($RR = 1.740$) to the null ($1.0$).\n- **The Diagonal Intersection**: The E-value itself (value of **2.87**) corresponds to the point on the curve where the two associations are assumed to be equal: $RR_{UD} = RR_{UY} = 2.87$.\n- **The Non-diagonal Trade-off**: The curve illustrates that the associations do not have to be equal. If an unmeasured confounder has a weaker relationship with treatment (e.g. $RR_{UD} = 2.0$), it would need to have a much stronger relationship with the outcome (e.g. $RR_{UY} \\approx 6.0$) to explain away the effect.\n- **Below/Left of the Curve**: This represents the region where unmeasured confounding is **insufficient** to explain away the observed effect. If the true confounding associations lie in this region, the treatment effect remains causal and significant.\n- **Above/Right of the Curve**: This represents the region where unmeasured confounding is strong enough to explain away the observed effect.\n- **The Dashed Curve (Confidence Interval Boundary)**: Shows the boundary required to explain away the 95% confidence interval lower limit ($RR_{lower} = 1.334$), corresponding to the lower limit E-value of **2**.\n\n---\n\n## Causal Evidence Reconciliation\n\nWe reconcile the point estimates and standard errors across our observational causal pipeline compared to the simulated population ground truth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit IPTW for comparison (from Page 2 workflow)\nW <- weightit(treatment ~ age + ecog, data = df, method = \"ps\", estimand = \"ATE\")\nfit_iptw <- lm_weightit(survival_1yr ~ treatment, data = df, weightit = W)\niptw_summary <- summary(fit_iptw)\niptw_est <- iptw_summary$coefficients[\"treatment\", \"Estimate\"]\niptw_se  <- iptw_summary$coefficients[\"treatment\", \"Std. Error\"]\n\n# Fit AIPW for comparison (from Page 2 workflow)\nsl_lib_aipw <- c(\"SL.glm\", \"SL.mean\")\naipw_obj <- AIPW$new(\n  Y = df$survival_1yr,\n  A = df$treatment,\n  W = df[, c(\"age\", \"ecog\")],\n  Q.SL.library = sl_lib_aipw,\n  g.SL.library = sl_lib_aipw\n)\nsuppressMessages(aipw_obj$fit())\ninvisible(capture.output(aipw_obj$summary()))\naipw_res <- aipw_obj$result\naipw_est <- aipw_res[\"Risk Difference\", \"Estimate\"]\naipw_se  <- aipw_res[\"Risk Difference\", \"SE\"]\naipw_ci  <- c(aipw_res[\"Risk Difference\", \"95% LCL\"], aipw_res[\"Risk Difference\", \"95% UCL\"])\n\n# Combine into reconciliation matrix\nreconciliation_tbl <- data.frame(\n  Estimator = c(\"Ground Truth (Omniscient)\", \"Naive (Unadjusted)\", \"IPTW (Weighting Only)\", \"AIPW (Doubly Robust)\", \"TMLE (Doubly Robust)\"),\n  \"ATE Point Estimate\" = c(true_ate, naive_ate, iptw_est, aipw_est, tmle_est),\n  \"Standard Error\" = c(NA, NA, iptw_se, aipw_se, tmle_se),\n  \"95% LCL\" = c(NA, NA, iptw_est - 1.96 * iptw_se, aipw_ci[1], tmle_ci[1]),\n  \"95% UCL\" = c(NA, NA, iptw_est + 1.96 * iptw_se, aipw_ci[2], tmle_ci[2]),\n  \"Bias vs. Truth\" = c(0.0000, naive_ate - true_ate, iptw_est - true_ate, aipw_est - true_ate, tmle_est - true_ate),\n  check.names = FALSE\n)\n\n# Format values for display\nreconciliation_tbl[, 2:6] <- round(reconciliation_tbl[, 2:6], 4)\nreconciliation_tbl[is.na(reconciliation_tbl)] <- \"N/A\"\n\nknitr::kable(reconciliation_tbl, caption = \"Causal Evidence Reconciliation Across Estimators\", align = \"lrrrrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Causal Evidence Reconciliation Across Estimators\n\n|Estimator                 | ATE Point Estimate| Standard Error| 95% LCL| 95% UCL| Bias vs. Truth|\n|:-------------------------|------------------:|--------------:|-------:|-------:|--------------:|\n|Ground Truth (Omniscient) |             0.1550|            N/A|     N/A|     N/A|         0.0000|\n|Naive (Unadjusted)        |             0.0942|            N/A|     N/A|     N/A|        -0.0608|\n|IPTW (Weighting Only)     |             0.1678|         0.0476|  0.0746|   0.261|         0.0128|\n|AIPW (Doubly Robust)      |             0.1700|         0.0499|  0.0723|  0.2678|         0.0151|\n|TMLE (Doubly Robust)      |             0.1702|         0.0477|  0.0768|  0.2637|         0.0153|\n\n\n:::\n:::\n\n\n",
    "supporting": [
      "03_TMLE_and_Sensitivity_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}